# ¿Para qué sirve la economía? {#Capitulo_13}

```{r, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "html", results='asis', echo=FALSE}
cat('<hr style="background-color:#03193b;height:2px">')
```

Los fundamentos metodológicos de cualquier disciplina científica están conformados por los objetivos hacia los que apunta dicha disciplina. Si bien se acepta casi universalmente que los objetivos de explicación y predicción de fenómenos naturales y no humanos se han cumplido con gran éxito desde la revolución científica, es casi igualmente universalmente aceptado que las ciencias sociales ni siquiera se han acercado a lograrlos. metas. Esto plantea la pregunta que se aborda en este artículo, a saber, ¿para qué sirven la economía y, en términos más generales, las ciencias sociales? ¿Cuál es su objetivo y en qué se parece y en qué se diferencia del de las ciencias naturales tal como las hemos llegado a clasificar? Tomo esta cuestión desde una perspectiva pragmática en este artículo, situando la economía dentro del contexto más amplio de la investigación social. Específicamente, me dirijo a Hilary Putnam y John Dewey como ejemplos de la crítica pragmática de cualquier economía que considere que sus objetivos están en línea con los de las ciencias naturales, es decir, que apuntan a la explicación y la predicción de acuerdo con las leyes que rigen el comportamiento humano.

## Introducción {-}

Los principios metodológicos que han llegado a enumerarse como los puntos de partida fundamentales de la economía neoclásica han sido objeto de crítica desde sus inicios en la Revolución Marginal. El agente racional, el carácter de maximización de la utilidad de sus elecciones y el individualismo metodológico que encajaba tan bien con los métodos avanzados de cuantificación han sido cuestionados, si no completamente refutados, desde una variedad de ámbitos^[Véase, por ejemplo, Anderson (2000).]. Estos críticos provienen de áreas de especialización intelectual como la filosofía de las ciencias sociales (especialmente su subrama la filosofía de la economía), disciplinas de las humanidades fuera de las ciencias e incluso dentro de la economía misma. El último grupo de críticos sufrió una marginación cada vez mayor a medida que el predominio de la economía neoclásica casó un fundamento filosófico positivista con las pretensiones científicas y las tendencias matematizadoras de la economía como disciplina. No es sin cierta ironía no intencionada, entonces, que los practicantes de esta ciencia tomaron prestada una distinción del discurso teológico y llamaron a los métodos de la corriente principal "ortodoxos" ya los que están fuera del discurso dominante, "heterodoxos".

Sin embargo, como dice una historia ahora bien contada en las explicaciones filosóficas de la economía, mientras que el positivismo y específicamente la filosofía de la ciencia encarnada en el empirismo lógico atravesaron tiempos difíciles a mediados del siglo XX y fueron pasados ​​por alto, los principales practicantes de la economía de al al menos dos escuelas parecían ignorar por completo el fracaso del positivismo en dar cuenta de una variedad de sus propios objetivos. Estos fracasos se reprodujeron en la economía neoclásica en términos de explicación, las elecciones irracionales que hacen los agentes y un fracaso constante para generar modelos que predecirían el comportamiento del mercado agregado^[La crisis financiera de 2008 es un ejemplo de este fracaso, un fracaso tan sorprendente como para patrocinar una comisión real de economistas destacados para explicar por qué los economistas no habían podido predecirlo en el Reino Unido. En Estados Unidos, el testimonio de Alan Greenspan ante un comité de la Cámara de Representantes se ha convertido en una piedra de toque para los llamamientos a la reforma económica. Véase en particular su intercambio con el representante Henry Waxman. https://www.c-span.org/video/?c3342718/waxman-greenspan-testimony]. Los economistas del comportamiento tomaron estos fracasos como su punto de partida para reintroducir la irracionalidad en su comprensión de las decisiones humanas y ahora se erige como uno de los principales competidores por la adecuación explicativa al proporcionar a la economía mejores bases científicas para su proyecto intelectual. También ha ganado una mayor tracción política en términos de política. Pero la cuestión de la relación entre los valores intrínsecos a la práctica de la ciencia y las descripciones generadas por esa actividad científica en sí todavía permanece fuera del Organonde estas dos grandes escuelas de pensamiento económico. Esta exclusión se manifiesta de dos formas. Primero, ambas escuelas básicamente aceptan que el fin de la actividad humana es la realización de las preferencias individuales. En el modelo neoclásico, esto implica el análisis de costo-beneficio de un algoritmo interno que calcula la acción en base a preferencias dadas y la información disponible con respecto a los medios para satisfacer esas preferencias. La economía del comportamiento introduce intervenciones paternalistas a nivel de prescripciones políticas para superar la irracionalidad de los individuos en las elecciones erróneas que hacen para satisfacer sus preferencias dadas. Los agentes exhiben irracionalidad derivada de una variedad de fuentes, incluidos los sesgos cognitivos y los efectos de encuadre que conducen a elecciones que no maximizan la utilidad. Por lo tanto, ambos ven la acción y la política económicamente informada como un medio para satisfacer las preferencias. Es decir, ya sea que modele la razón práctica como lo hacen los economistas neoclásicos, en lo que podría caracterizarse como un modelo humeano de deseo-creencia, o si sigue a los economistas conductuales para obtener los sesgos cognitivos inherentes que interfieren con nuestra satisfacción de preferencias, aísle la cuestión de la moralidad. de la disciplina de la investigación económica. Esto se muestra por primera vez en el intento de ambas escuelas de proporcionar una explicación predictiva y sin valores de la ciencia económica. aísla la cuestión de la moralidad de la disciplina de la investigación económica. Esto se muestra por primera vez en el intento de ambas escuelas de proporcionar una explicación predictiva y sin valores de la ciencia económica. aísla la cuestión de la moralidad de la disciplina de la investigación económica. Esto se muestra por primera vez en el intento de ambas escuelas de proporcionar una explicación predictiva y sin valores de la ciencia económica.

En este capítulo ofrezco un camino alternativo para caracterizar la práctica de la economía que se basa en una explicación pragmática de las ciencias sociales. Según este entendimiento, como han argumentado filósofos pragmáticos desde Charles Sanders Peirce hasta Hilary Putnam, los hechos y los valores están inextricablemente entrelazados en la práctica de toda la ciencia^[Putnam ha aclarado recientemente su posición sobre hechos y valores con respecto a la ontología, la lógica y las matemáticas como un caso especial de emplear, tomando prestado un término de Jennifer Case, “lenguajes opcionales”. Que estos enfoques conceptuales alternativos, lo que él llama su 'pluralismo conceptual', es el resultado de no tener un modo verdadero de describir el mundo, y que la elección se basa en intereses que tienen una base evaluativa y racional. Este pluralismo, sin embargo, no tiene la consecuencia del relativismo o del antirrealismo. Para su tardía articulación de esta tesis, ver Putnam (2016).]. Además, de acuerdo con la visión pragmática que se ofrece aquí, las ciencias en una comprensión pragmática se inspiran en el dicho aristotélico de que debemos ordenar nuestro método y el objetivo de nuestras indagaciones al objeto que estamos tratando de comprender. Sin embargo, un pragmatismo algo contrario a la intuición ofrece una teoría general de la investigación como resolución de problemas. De este híbrido de métodos específicos de objeto y un objetivo fundamental de resolución de problemas se deduce que si lo que estamos tratando de resolver no son solo problemas de física, por ejemplo, sino también la frustración de los valores e intereses de los seres humanos, la indagación misma adquirirá un carácter moral tanto en términos del vocabulario utilizado para abordar el problema como en términos del carácter de la investigación en sí. Por lo tanto, de acuerdo con la visión pragmática de este artículo, La economía no puede evitar ser una ciencia moral, ya que involucra cuestiones de trabajo, distribución, desigualdad y recursos escasos que afectan el florecimiento de la especie humana y, ahora mucho más ampliamente, el florecimiento de especies en el planeta. Una vez que se vuelve a dibujar la economía de esta manera, y se reconstruyen las pretensiones de la economía de ser una "ciencia" modelada sobre los objetivos científicos naturales de explicación y predicción, la pregunta "¿Para qué es la economía?" 'podría recibir una respuesta sólida desde el punto de vista moral y epistemológico. y se reconstruyen las pretensiones de la economía de ser una "ciencia" inspirada en los objetivos científicos naturales de la explicación y la predicción, la pregunta "¿Para qué sirve la economía?" 'podría recibir una respuesta sólida desde el punto de vista moral y epistemológico. y se reconstruyen las pretensiones de la economía de ser una "ciencia" inspirada en los objetivos científicos naturales de la explicación y la predicción, la pregunta "¿Para qué sirve la economía?" 'podría recibir una respuesta sólida desde el punto de vista moral y epistemológico.

Al pasar al pragmatismo, me gustaría centrarme en varias características que ponen de relieve la orientación general que proporciona el pragmatismo a nivel epistemológico y científico. En particular, y lo que contrasta radicalmente con lo que podrían verse como los dos principales contendientes por la supremacía en economía mencionados anteriormente, el pragmatismo incrusta valores en el proceso de investigación mismo hasta el punto de negar una dicotomía rígida hecho / valor incluso con respecto a paradigmas de neutralidad de valores como la física y el resto de las ciencias naturales. Hilary Putnam fue quizás la pragmática más vocal al destruir la idea de que los hechos y los valores son juicios, cuando se expresan como proposiciones, que pueden separarse completamente entre sí. No solo está presente en su obra quizás más famosa, Razón, verdad e historia, pero es el tema de un libro completamente separado, más de dos décadas después, El colapso de la dicotomía hecho / valor^[Ver Putnam (1980) y Putnam (2004)]. Estos trabajos sirven de base para su trabajo posterior en la filosofía de la economía. En The End of Value Free Economics con Vivian Walsh. Putnam escribe:

> Hay hechos (usando el término como normalmente lo hacemos, no como un término en la teoría metafísica, que ... es lo que hicieron los positivistas lógicos) que se manifiestan sólo a través de los lentes de una perspectiva evaluativa. Los términos de virtud, términos como 'valiente', 'sabio', compasivo ',' ingenioso 'y sus opuestos, han figurado en las discusiones filosóficas durante milenios precisamente por esta razón^[Putnam (2003, 396). Repr. en Putnam y Walsh (2012, 112)].

La consecuencia de este punto de vista es que el intento en economía de lograr un modelo libre de valores de la explicación científica del comportamiento humano es fundamentalmente defectuoso. Por lo tanto, incluso si la economía pudiera imitar a las ciencias naturales como les gustaría hacer, el lenguaje involucrado en la descripción de lo que se observa o los juicios de relevancia, para tomar dos elementos de la investigación científica, están cargados de valores. El tema es doblemente tenso para las ciencias del comportamiento humano, ya que los investigadores emplean suposiciones con respecto a los valores, además de usar un lenguaje que necesariamente entrelaza elementos descriptivos y normativos. Nuevamente Putnam:

> El mundo que habitamos cuando describimos el mundo con fines distintos a los de la física o la biología molecular o alguna otra ciencia exacta (ciertamente el mundo que habitamos cuando describimos el mundo para los fines que le interesan al economista) no se puede describir en ' términos de valor neutral. No sin descartar los hechos más significativos junto con los 'juicios de valor' (Putnam y Walsh2012, 112).

Además de las cuestiones con términos gruesos o descripciones que no permiten desenredar lo normativo de los elementos fácticos de las proposiciones, otra característica común de una variedad de pensadores pragmáticos con respecto a la investigación social son los intereses y valores que se hacen explícitos por el hecho de que algo es un problema en primer lugar. Es decir, no es solo una 'inyección' de valores a través de los argumentos conceptuales y lingüísticos sobre conceptos gruesos, el carácter entrelazado de hecho y valor en ciertos términos, sino que también es central que las situaciones problemáticas en sí mismas estén disponibles para los científicos sociales. indagación al estar constituidos en su tejido como situaciones por valores^[La afirmación clásica de esta posición en la literatura pragmática se encuentra en Experience and Nature de John Dewey . Allí escribe:

¿O hay un ingrediente de verdad en la metafísica antigua que pueda extraerse y reafirmarse? Empíricamente, no se puede negar la existencia de objetos de dominio, posesión, uso y disfrute directos. Empíricamente, las cosas son conmovedoras, trágicas, hermosas, divertidas, asentadas, perturbadas, cómodas, molestas, estériles, duras, consoladoras, espléndidas, aterradoras; lo son inmediatamente y por derecho propio y en nombre. Si aprovechamos la palabra estética en un sentido más amplio que el de aplicación a lo bello y lo feo, la cualidad estética, inmediata, final o encerrada en sí misma, caracteriza indudablemente las situaciones naturales tal como ocurren empíricamente. Estos rasgos se encuentran en sí mismos exactamente al mismo nivel que los colores, los sonidos, las cualidades de contacto, el gusto y el olfato. Cualquier criterio que considere que estos últimos son datos definitivos y "duros", se aplicará de manera imparcial, llegar a la misma conclusión sobre el primero. Cualquier cualidad como tal es definitiva; es a la vez inicial y terminal; lo que es tal como existe.

Está más allá del alcance de este artículo involucrar los recursos pragmáticos para este puesto. Es instructivo que después de décadas de explorar cuestiones tales como el papel de los datos sensoriales en nuestras teorías científicas y metafísicas, Putnam avanza cada vez más hacia esta posición en sus escritos. Vea especialmente sus debates con Bernard Williams como evidencia de este movimiento. En este giro confía en Dewey, sí, pero en su último trabajo recurre a las teorías y la investigación empírica en la percepción para ampliar su postura. Ver Dewey (1925, 82) y Putnam (2016).]. La explicación que el pragmatismo, a partir de Peirce, tiene de la indagación es como una actividad práctica de pasar del estado de duda al estado de creencia. Dewey transformó la matriz duda-creencia, manteniendo su carácter general, en una comprensión novedosa de la lógica como teoría de la investigación^[Para la declaración clásica de esta matriz, consulte "La fijación de la creencia" en Peirce y Buchler (1955).]. Esta extensión de la formulación original de Peirce es clave para comprender el carácter práctico de la actividad científica, pero también, de manera crucial, los resultados de esa actividad: la investigación está contextualizada y se basa en los recursos conceptuales disponibles para abordar las fallas de los hábitos a nivel individual, institucional. , y nivel social. Un elemento clave del carácter contextual de las situaciones problemáticas es lo que Dewey llamó su singularidad cualitativa. Si bien comparten muchos elementos y continuidades con respecto a contextos de problemas anteriores, son novedosos. Como novedosos, nuestros patrones de inferencia, ya sean deductivos o inductivos, no son suficientes para responder de una manera que pueda identificar, y mucho menos resolver, el problema en cuestión. Más bien, requiere una inferencia hipotética o una abducción y un experimento.

Además, en la comprensión pragmática de las ciencias sociales, el carácter práctico de esta actividad se extiende más allá de la supuesta neutralidad de valores de los marcos metodológicos hasta el fin hacia el que apuntan los economistas. Las prácticas son actividades gobernadas por reglas famosas que han incrustado dentro de ellas metas hacia las cuales están ordenadas. Pero, ¿cuál es el objetivo de la economía? De hecho, ¿para qué sirve la economía? El modelo de economía que ofrece el pragmatismo considera que esta cuestión es una de las principales características orientadoras de esta o cualquier práctica que califique como investigación científica. Brevemente, antes de abordar este objetivo, es útil destacar dos aspectos del pragmatismo que tienen profundas consecuencias en la forma en que abordamos los problemas sociales de manera más amplia: el carácter general del patrón de investigación y la naturaleza experimental de la investigación.

En la comprensión pragmática de la investigación, o la ciencia, o cómo logramos el conocimiento sobre el mundo (epistemología), el pragmatismo comparte al menos una similitud metodológica con el positivismo en al menos algunas de sus formas: la investigación científica tiene un patrón general. Los positivistas, en una de sus versiones más famosas, se exiliaron de todas las proposiciones de valor del lenguaje significativo tan insensatos como carecían de un procedimiento de verificación mediante el cual pudieran ser probados y asegurados en las ciencias físicas^[
Los dos objetivos principales en la literatura pragmática que abordan este argumento son el emotivismo en la ética y el eliminativismo fisicalista en la metafísica y la ontología.]. Esto, por supuesto, es lo opuesto a la posición pragmática, ya que los valores e intereses saturan las elecciones realizadas dentro de los contextos de resolución de problemas de toda investigación. Los criterios de coherencia, por ejemplo, implican la evaluación del ajuste introduciendo juicios normativos en los procedimientos científicos. Si bien el pragmatismo comparte con el positivismo la teoría de un patrón general de investigación, la práctica de hacer ciencia y su lenguaje está cargada de valores según el pragmatismo. Esto choca con el positivismo y, en consecuencia, con la autocomprensión de la economía dominante. Cuando se vuelve a las ciencias sociales (especialmente en el pragmatismo de Dewey y Putnam, para señalar los principales ejemplos en el fondo de este artículo, pero de ninguna manera se limita a estos dos) este patrón se adapta y se ordena a los objetos o sujetos que constituyen el contexto problemático y, además, se vuelve históricamente autoconsciente con respecto a los métodos anteriores. de indagación de forma acumulativa. Dewey, en particular, no es optimista acerca de las dificultades de cumplir con las normas de la investigación científica con respecto a las ciencias sociales, pero no obstante lo usa como un criterio normativo para analizar lo que cuenta como investigación social real y lo que son meras abstracciones intelectuales basadas enCompromisos teóricos a priori .

Esta autorreflexión metodológica está conformada a su vez por los contextos sociales e históricos en los que emerge. Dicho de manera más directa, los mismos conceptos e ideas que guían la investigación científica, así como lo que termina siendo aritculado como "hecho", se generan y activan dentro de un contexto. Más allá del carácter, entonces, de nuestro lenguaje, conceptos y juicios que traicionan la infusión de hechos y valores, los medios intelectuales a nuestra disposición operan dentro de un "trasfondo" que es específico de nuestra ubicación histórica y cultural. Ésta es una tesis familiar en la filosofía de la ciencia que se captura en un registro diferente como la teoría-dependencia de nuestros datos. La manera de Putnam de poner esto dentro de la circunscripción práctica de nuestras actividades científicas es declarando que “la ciencia instituye datos”^[Rorty y col. (2004). Esta conversación entre James Conant, Hilary Putnam y Richard Rorty proporciona una exploración accesible y esclarecedora de estos temas, junto con los desacuerdos de Putnam con Rorty.]. Es decir, los hechos que se articulan en el lenguaje de los científicos, por supuesto, se basan en la observación, pero la percepción para los pragmáticos es un asunto de interés, mediado a través de los recursos conceptuales disponibles para hacer explícito el material de nuestras percepciones^[Expongo el asunto de esta manera en aras de la conveniencia. Hay una historia pragmática mucho más larga que contar con respecto a la relación de conceptos, percepciones y estímulos.].

Además de estas características conceptuales de la comprensión pragmática de la indagación, el patrón general articulado por Dewey también enfatiza los efectos de la indagación de impacto existencial u objetivo. Es decir, la actividad de indagación reconstituye situaciones problemáticas mediante la intervención inteligente de humanos que buscan resolver sus problemas. Debido a que la indagación se genera a partir de la duda del indagador en Peirce, o la ruptura de nuestros hábitos proyectivos y anticipaciones en Dewey, su resolución consiste en reordenar el contexto práctico en el que el problema o la duda encontró su génesis. Es decir, y aquí nos apoyamos en Dewey para su afirmación más explícita, la indagación implica resolver los problemas que surgen de las averías de nuestras prácticas de tal forma que se reconstruya y restaure el medio ambiente:

> La indagación es la transformación controlada o dirigida de una situación indeterminada en una que está tan determinada en sus distinciones y relaciones constituyentes como para convertir los elementos de la situación original en un todo unificado^[Ver Dewey (1938, 109).].

Reclamo esta definición frecuentemente citada por dos razones. La primera es que plantea una gran cantidad de cuestiones sobre cómo comprender los propósitos de las ciencias mismas, y estas cuestiones solo se vuelven más complicadas cuando se trata de sujetos humanos. Lejos de limitar el propósito de la ciencia como la creación de un sistema verificado de proposiciones que describen el mundo natural de una manera neutral en cuanto a valores, la investigación pragmática está involucrada en la constitución activa de la situación problemática con respecto a los recursos conceptuales disponibles y luego participando en la actividad experimental. que intenta solucionar el problema. De hecho, es al discutir la investigación social como una instancia especial de investigación que Dewey se esfuerza por reiterar el carácter intervencionista o cambiador del mundo de la investigación científica natural.

## La filosofía de las ciencias sociales y el pragmatismo {-}

Aquí me gustaría retirarme a un nivel superior de abstracción, pero que permita comprender cuán crucial es la cuestión de esta reflexión para la práctica de la economía en sí desde una perspectiva pragmática. Cuando colocamos la economía como una disciplina que la agrupa bajo las ciencias sociales, podemos ayudar a iluminar una respuesta sobre para qué sirve desenterrando algunas de las características generales de la investigación en las ciencias sociales, tout court. El debate sobre para qué sirven las ciencias sociales se puede captar de manera muy general refiriéndonos a los tres extremos de la explicación, la comprensión y la emancipación^[Vea la declaración clásica de estas opciones ver Fay y Moon (1977).]. Es decir, lo que los científicos sociales generalmente consideran el objetivo de una actividad científica social han tendido a clasificar en tres líneas:

1. Las ciencias sociales apuntan a resultados similares a las explicaciones basadas en la causa-efecto que cubren modelos de derecho como en las ciencias naturales, o alguna versión menor de correlación inductiva.
2. Las ciencias sociales están orientadas hacia la comprensión mutua del carácter significativo y expresivo de un animal que es esencialmente autodefinido y autoarticulado a través de acciones que no se pueden reducir a un marco disponible para un observador independiente.
3. Las ciencias sociales son parte de una praxis general cuyo objetivo final es la emancipación de las dimensiones irreductibles del poder que hasta ahora han estratificado a las sociedades en formas que oprimen, dominan y disminuyen arbitrariamente la creatividad humana a través de la distorsión sistemática de las intenciones de los actores.

Las escuelas naturalistas, interpretativas y críticas de las ciencias sociales, entonces, son parte de la herencia conceptual de las ciencias sociales cuando se trata de la tarea intelectual y práctica de abordar los problemas económicos. Aquí volvemos al pluralismo del pragmatismo, y en particular a la filosofía de las ciencias sociales de John Dewey, para abordar el propósito de la economía, vis -a-vis la filosofía de las ciencias sociales.

Frente a fines tan diferentes y al principio incompatibles para la economía como un ejemplo especial de investigación social, el enfoque pragmático emplea lo que podría llamarse una estrategia hegeliana en una vena metafísicamente naturalista. Es decir, en lugar de seleccionar una de las plataformas metodológicas para el propósito de las ciencias sociales, el pragmatismo absorbe a cada una en un patrón de investigación que extrae las lecciones para hacer frente de manera práctica a los problemas que cada método se inspiró históricamente para abordar. Cada una de estas escuelas ayuda como etapa a articular y abordar el problema en cuestión. Además, debido a que las situaciones problemáticas son únicas y se componen de elementos variados en diferentes intensidades de influencia, ninguna plataforma metodológica tiene prioridad sobre otras a priori.Moda. En algunos casos, lo que observamos utilizando modelos de elección humana de maximización de la utilidad es correcto. En otros, sería engañoso imponerlos como explicaciones de la acción^[Clifford Geertz's (1973) “Juego profundo: notas sobre la pelea de gallos balinesa” sigue siendo una piedra de toque instructiva para los peligros de imponer modelos de elección racional a los fenómenos sociales.]. Esto hace que el empleo del método sea un asunto práctico que requiere una actitud experimental y falibilista: ¿Hay elementos causales en el comportamiento humano que deban obtenerse para ayudar a explicar la situación problemática? ¿Estoy realmente comprendiendo lo que está sucediendo en este contexto de acción sin involucrar a los participantes de manera que reconstruya con empatía sus intenciones para dar un sentido significativo a sus acciones? ¿Hay fuerzas en juego que distorsionan psicológicamente las prácticas y los marcos intencionales con fines de manipulación ideológica? Todas estas son preguntas que ayudarán a iluminar la acción humana en general, y lo que se ha llegado a definir como acción económica a lo largo del tiempo. Esta traducción o, si se prefiere, la superación de diferentes paradigmas de las ciencias sociales y, por extensión, Las escuelas económicas no se limitan a la filosofía pragmática en general a las cuestiones sociales de este tipo. Más bien, la estrategia general del pragmatismo es ver cada una de las alternativas desarrolladas en el pasado con respecto a la ética, la epistemología y la metafísica como marcos metodológicos para ayudar a reconstruir una situación problemática en el presente en un todo resuelto^[Me he referido a estas preguntas como informantes de diferentes momentos metodológicos de la investigación social en Hogan y Marcelle (2017). Esta estrategia pluralista tiene algunos practicantes actuales en la economía contemporánea. Ha-Joon Chang, por ejemplo, ha estado discutiendo tanto en publicaciones como haciendo videos populares que a la vez reorientan las abstracciones y el nivel experto de la economía y también desafía la ortodoxia que, aunque intelectualmente hablando, aún mantiene la política sociológica y política. dominio. Chang, de hecho, enumera 11 escuelas de economía diferentes. También resuena con pragmatismo la insistencia de Chang en que la experiencia de un individuo es un punto de partida suficiente para hacer juicios informados sobre los sistemas económicos y sus resultados. Ver a Ha Joon Chang (2011) y RSA- Animate: Economía para todos, una animación de pizarra cognitiva. https://www.youtube.com/watch?v=E9EzXHVYClI].

La contribución particularmente pragmática en las ciencias sociales, como un cuarto elemento potencial para la investigación social, es su carácter experimental. Dado que la filosofía de las ciencias sociales de Dewey sigue siendo la elaboración más detallada del giro pragmático de la filosofía con respecto a la investigación social, me basaré en su discusión sobre ella en su Lógica de 1938 : la teoría de la investigación . Allí, Dewey señala en términos definidos cuáles son las consecuencias de la reconstrucción pragmática de la historia de la investigación filosófica para las ciencias sociales en el penúltimo capítulo de esa obra. Afirma que la investigación social es especialmente vulnerable a la doctrina positivista de la estricta separación de hechos y valores y, por lo tanto, la independencia de las ciencias sociales de la práctica social:

> ... prevalece comúnmente la idea de que tal investigación es genuinamente científica sólo si se abstiene deliberada y sistemáticamente de toda preocupación por cuestiones de práctica social. La lección especial que la lógica de los métodos de investigación física debe enseñar a la investigación social es, en consecuencia, que la investigación social, como investigación , implica la necesidad de operaciones que modifican existencialmente condiciones reales que, tal como existen, son ocasiones de genuina investigación y que proporcionen su tema. Porque, como hemos visto, esta lección es la importancia lógica del método experimental^[Dewey1938, 486)].

Es decir, para la ciencia social pragmática, la acción social en aras de abordar un problema articulado en los diferentes procesos metodológicos de la investigación social es endógena a la investigación social misma.

La investigación social se trata de resolver problemas, como lo es toda investigación, y la solución de los problemas de los seres humanos requiere una acción social cooperativa. Un problema no se resuelve con un artículo de revista o una monografía, por brillante que sea. Es aquí donde los objetivos más amplios de la vida comunitaria se inscriben dentro de cada una de las ciencias sociales. Es decir, cada ciencia social tal como se ha desarrollado en realidad ni siquiera es científica, según el pragmatismo, a menos que implique una acción cooperativa y coordinada por parte de los individuos que viven dentro del contexto problemático para resolver el problema:

> Lo que se observa, no importa cuán cuidadosamente y no importa cuán exacto sea el registro, sólo puede entenderse en términos de las consecuencias proyectadas de las actividades. En resumen, los problemas que conciernen a la investigación de la materia social deben, si satisfacen las condiciones del método científico, (1) surgir de tensiones, necesidades, “problemas” sociales reales; (2) tener su objeto de estudio determinado por las condiciones que son medios materiales para producir una situación unificada, y (3) estar relacionado con alguna hipótesis, que es un plan y una política para la resolución existencial de la situación social conflictiva^[Dewey1938, 493)]. 

Sin embargo, nuestro único camino para confirmar nuestras hipótesis científicas sociales es a través de la acción coordinada. El requisito epistemológico de resolver el problema en primer lugar incluye la verificación pública o práctica del problema a través de canales de comunicación que incorporan al proceso de formación del problema las perspectivas de los propios sujetos^[
Sobre el concepto de verificación práctica, ver Bohman (2003).].

Este aspecto de la investigación social amplía los requisitos prácticos de las ciencias sociales para formar un público que se convierte en una característica constitutiva de la formación de problemas. A diferencia de las apelaciones a la gestión tecnocrática de las políticas políticas y la legislación, los problemas de la vida política, económica y social se entienden aquí como productos de la articulación y comunicación de aquellos individuos que están experimentando el problema ellos mismos. Debido a que las situaciones problemáticas no exhiben sus características constitutivas de manera que sean fácilmente legibles para un observador, la exigencia de descubrir cuál es el problema en primera instancia es primordial. Pero en lugar de que estos problemas sean de la naturaleza de diferentes compuestos químicos y su reacción entre sí, o el movimiento de los cuerpos planetarios, los problemas sociales involucran a agentes que no están de acuerdo, entran en conflicto, recurren a la violencia y tienen interpretaciones muy variadas de los procesos de causa y efecto y los poderes que gobiernan sus oportunidades de vida. Si los científicos sociales van a tener la oportunidad de resolver el problema correctamente, ellos mismos deben suspender sua prioripredilecciones por definir problemas sociales de acuerdo con un vocabulario y metodología que funcionó en una instancia histórica previa. No se trata de eludir lo que antes llamé el carácter contextual e históricamente específico de nuestros empleos conceptuales. Es reconocer el carácter falible y situado de nuestras proyecciones conceptuales a la luz de una situación novedosa. La singularidad cualitativa, sin embargo, que es la marca de las situaciones problemáticas impide que los investigadores aprehendan de una manera cognitivamente completa los entornos que exhiben estas diversas características únicas, energías espontáneas y nuevas constelaciones de fuerzas en acción. En breve,

> La conexión de la investigación social, en cuanto a datos sociales y en cuanto a generalizaciones conceptuales, con la práctica es intrínseca, no externa. Cualquier problema de investigación científica que no surja de las condiciones sociales reales (o “prácticas”) es facticio; es establecido arbitrariamente por el investigador en lugar de ser producido y controlado objetivamente. Todas las técnicas de observación empleadas en las ciencias avanzadas pueden ajustarse, incluido el uso de los mejores métodos estadísticos para calcular errores probables, etc., y sin embargo, el material comprobado esté científicamente "muerto", es decir, irrelevante para un problema genuino. de modo que preocuparse por él es poco más que una forma de trabajo intelectual ocupado. Lo que se observa, no importa cuán cuidadosamente y no importa cuán exacto sea el registro, es capaz de ser entendido.sólo en términos de las consecuencias proyectadas de las actividades^[Dewey1938, 492)].

Una de las limitaciones, entonces, de esta comprensión de las ciencias sociales es que la propia formación del problema se basa en la articulación de la frustración de intereses y daños experimentados por los individuos, de modo que nuestra comprensión del problema puede ser tan epistemológicamente robusta como sea posible. Por supuesto, es posible que los propios sujetos articulen sus perspectivas saturadas de desinformación, prejuicio o ignorancia. Sin embargo, el proceso de investigación social involucra al público de una manera autorreflexiva precisamente para descubrir y abordar estos déficits, y para ver cómo estos mismos errores contribuyen al problema en cuestión.

En este sentido, la crítica del carácter unidimensional de las escuelas económicas dominantes es moral. La economía sirve para resolver problemas económicos, y el camino para resolver estos problemas, como lo entiende el pragmatismo, requiere una amplia gama de métodos y enfoques para comenzar incluso a resolver los problemas de la economía correctamente. Los problemas se definen en conjunto con la articulación y acción de los sujetos en el contexto problemático. Aunque ahora se ha vuelto cada vez más popular criticar las ramas de la economía dominante y que impulsan las políticas, Dewey articuló su crítica y visión de las ciencias sociales en la década de 1930 que culminó en 1938, y no es coincidencia que el contexto en el que Dewey estaba escribiendo fuera la Depresión. y el surgimiento concomitante del fascismo y la solidificación del comunismo soviético.explanandum de la historia al explanans de la agencia económica.

Si bien este comentario histórico es ilustrativo, tiene un propósito tanto conceptual como ejemplar. Porque si la investigación pragmática, como investigación, ha de resolver un problema, se requiere la crítica implacable de todas las formas de metodología económica y práctica científica que hipostan los principios de la investigación en certezas a priori que controlan la selección y formulación de datos. Así, mientras Dewey articuló claramente una crítica devastadora del economismo soviético en su Freedom and Culture (1939) y se refirió a lo que había sido del pensamiento de Marx al servicio de la revolución rusa como "economía totalitaria", no fue menos penetrante en su crítica de las doctrinas políticas y económicas concomitantes con las economías políticas liberales en el mundo industrializado^[Para la crítica de Dewey al liberalismo y las variedades de metodologías económicas del laissez-faire que informaron la política pública en su tiempo, ver Dewey (1935) y Dewey (1930). Está más allá del alcance de este artículo articular en detalle las críticas de Dewey. Sin embargo, ofrecen un ejemplo claro de cómo la lógica pragmática de la investigación social maneja los supuestos básicos de una variedad de elementos en el enfoque neoclásico de la economía, así como los fundamentos conceptuales del liberalismo en general.].

Para terminar, me he centrado en las características generales de aquellos aspectos del pragmatismo que solidifican su enfoque de la economía como ciencia moral. Me he referido a la distinción hecho / valor, la filosofía de las ciencias sociales y el carácter experimental de la investigación que exige la filosofía pragmática de las ciencias sociales para demostrar este vínculo. La forma precisa en que esto se convierte en una cuestión moral es a través de la necesidad de incorporar los valores y perspectivas de los propios sujetos en la constitución de los problemas que la investigación social aborda bajo la rúbrica de "economía". Estos elementos conceptuales y prácticos no son las únicas formas en que los modelos pragmáticos de investigación social son relevantes para un proyecto de reconstrucción de la economía para dejar en claro su propósito moral. Específicamente, el modelo de los agentes y la disponibilidad de preferencias para la evaluación racional en situaciones de elección es otro camino rico que Putnam y otros han tomado al combinar la ética y la economía. Esta es otra forma en la que dos de las escuelas de economía dominantes que ejercen poder en la política y la cultura intelectual, la economía neoclásica y del comportamiento, se quedan cortas desde una perspectiva moral en la práctica de la economía.