# Economía, agencia y explicación causal {#Capitulo_04}

```{r, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "html", results='asis', echo=FALSE}
cat('<hr style="background-color:#03193b;height:2px">')
```

El documento considera tres preguntas. Primero, ¿cuál es la conexión entre economía y agencia? Se argumenta que la causalidad y la explicación en economía dependen fundamentalmente de la agencia. Por tanto, una comprensión filosófica de la explicación económica debe ser sensible a una comprensión de la agencia. En segundo lugar, ¿cuál es la conexión entre agencia y causalidad? Una visión causal de la explicación que involucra la agencia se defiende contra una serie de argumentos de la tradición no causalista resurgente en la literatura sobre agencia y acción-explicación. Si la agencia es fundamental para la explicación económica, se argumenta, entonces también lo es la causalidad. En tercer lugar, ¿cuál es la conexión entre la explicación causal y las ciencias naturales? Se argumenta que, aunque las explicaciones dadas en economía y otras ciencias sociales son explicaciones causales, son de diferente naturaleza a las explicaciones causales de las ciencias naturales. Por un lado, entonces, las explicaciones causales de las ciencias sociales son irreductibles a las que se encuentran en las ciencias naturales. Por otro lado, las relaciones causales descritas por las ciencias sociales no son completamente autónomas; no flotan libres de, ni operan independientemente de, las relaciones causales trazadas por las ciencias naturales.

## Economía y agencia {-}

Comenzaré defendiendo la tesis de que la explicación en economía siempre depende de, o está mediada por, fenómenos que involucran esencialmente a la agencia. Cuando detallamos las relaciones causales que se trazan en la economía, argumentaré, podemos ver que los mecanismos por los cuales las causas económicas producen sus efectos son siempre, en última instancia, dependientes de la acción humana.

En algunos casos, la dependencia de las explicaciones económicas de la agencia es muy obvia, porque lo que se explica es en sí mismo una acción o un conjunto de acciones. Si explicamos por qué los británicos generalmente ahorran menos que los japoneses, por ejemplo, debemos explicar por qué ciertas personas toman ciertas decisiones o actúan de cierta manera. Y no podemos hacer eso sin emplear los conceptos de agente y acción.

En otros casos, las consideraciones de agencia no están tan cerca de la superficie. Así, hay explicaciones económicas en las que ni el explanandum ni el explanans mencionan directamente acciones o agentes. Sin embargo, cuando explicamos el mecanismo por el cual se produjo el efecto en tales casos, la agencia entra rápidamente en escena. Considere, por ejemplo, la afirmación de que la inflación en Inglaterra en la década de 1580 fue causada por un aumento en la oferta monetaria. Esa afirmación no hace referencia inmediata a ninguna acción humana o instancia de agencia. Pero cuando preguntamos cómo, o por qué, la inflación fue causada por un aumento en la oferta monetaria, es fácil ver que la explicación depende de fenómenos que involucran a la agencia. Para simplificar: la afluencia de oro de las Américas condujo a un aumento en la cantidad de oro en manos de los consumidores y, por lo tanto, aumentó la oferta monetaria; cuando los comerciantes intentaron subir los precios de los bienes, por lo tanto, los clientes pudieron pagar los precios más altos en lugar de decidir no comprar los bienes en absoluto, como lo hubieran hecho anteriormente; de modo que los precios que la gente fijaba y pagaba por los bienes aumentaban en general; es decir, hubo inflación. O nuevamente, tomemos la afirmación de que la economía del Reino Unido se contrajo ligeramente en el segundo trimestre de 2018 porque hubo tormentas severas en abril. Una vez más, esa explicación en sí misma no menciona acciones o agencia. Pero vemos cómo la explicación depende de los hechos sobre las acciones y la agencia cuando explicamos cómo fue que el mal tiempo hizo que la economía se contrajera. Debido a las tormentas, mucha gente decidió quedarse en casa y no comprar los bienes y servicios que de otro modo esperarían comprar en la primavera: ropa de verano, barbacoas, material deportivo, vacaciones al aire libre, etc. Entonces, las empresas no vendieron tanto como habían planeado y el nivel general de actividad económica disminuyó: la economía se contrajo.

Ese es el patrón general. Vale la pena mencionar dos aparentes excepciones: casos en los que podría parecer que hay explicaciones en economía que no están respaldadas por la agencia. La primera es la teoría de juegos, que es, por supuesto, un área importante de actividad dentro de la disciplina de la economía. Las explicaciones dentro de la teoría de juegos no mencionan las acciones humanas en absoluto. La teoría de juegos es el estudio de la racionalidad pura: lo que sería racional para un agente creer, preferir o elegir en tales o cuales circunstancias, dada la información, los objetivos y las preferencias especificadas. Ésta es una empresa teórica puramente abstracta. Explicar por qué tal o cual acción sería racional en tales y tales circunstancias es una forma genuina de explicación. Pero no tiene nada que ver con explicar causalmente nada. Ni, a fortiori, ¿hay alguna cuestión de detallar los mecanismos que sustentan tales explicaciones y revelarlos como que involucran instancias de agencia? Sin embargo, cuando aplicamos la estructura teórica de la teoría de juegos a casos reales, asumiendo que las personas reales son más o menos racionales, y usando la teoría para predecir o explicar su comportamiento en situaciones de elección, entonces estamos tratando una vez más con la agencia y nuestras Las explicaciones estarán respaldadas por hechos sobre los agentes y sus acciones. Las afirmaciones de la teoría de juegos en sí, entonces, no tienen que ver con la acción o la agencia. Pero eso no es un contraejemplo de la afirmación general de que la explicación económica depende esencialmente de fenómenos que involucran a la agencia. Porque, aunque la teoría de juegos en sí misma no pretende explicar ningún fenómeno real, cuando las conclusiones de la teoría de juegos se aplican a fenómenos del mundo real,

Una segunda aparente excepción a nuestro principio general se relaciona con la compra y venta automatizadas. Supongamos que el mercado de valores cayó porque hubo un empeoramiento repentino del tipo de cambio. ¿Cuál fue el mecanismo que produjo ese efecto? ¿Cómo el empeoramiento del tipo de cambio provocó una caída en el mercado de valores? Antes del advenimiento del comercio automatizado, el mecanismo habría involucrado, como hemos dicho, la agencia humana: personas que toman decisiones para comprar y vender, a la luz de sus conocimientos, expectativas y preferencias. Pero en circunstancias en las que los cambios en el mercado de valores son producidos por altos volúmenes de operaciones automáticas, un cambio en el tipo de cambio puede desencadenar una caída en el mercado al desencadenar ventas automatizadas masivas, sin la participación de ningún proceso de razonamiento o agencia en absoluto. Hasta ese punto, algunos de los procesos causales estudiados por la economía pueden operar sin ningún proceso de acción humana. Pero ese fenómeno no socava el principio general de que la causalidad y la explicación en economía dependen de la agencia. En primer lugar, no podría haber una economía que funcionara de forma completamente automática, con cada caso de compra y venta operando independientemente de cualquier agencia humana. Si va a contar como parte de una economía, la estructura de las transacciones automatizadas debe en algún momento entrar en contacto con decisiones y acciones humanas reales. En segundo lugar, la agencia está involucrada en el diseño e implementación de los programas que realizan transacciones automatizadas. Entonces, parte de la respuesta a la pregunta, por qué la caída del tipo de cambio provocó una caída en el mercado de valores, implica un llamado a la agencia:

La explicación en economía, entonces, depende esencialmente de la agencia.

## Agencia y causalidad {-}

Muchos filósofos se han sentido atraídos por la idea de que la explicación en las ciencias sociales es radicalmente diferente de la explicación en las ciencias naturales. Algunos de esos filósofos han sostenido que la diferencia esencial entre los dos es que, mientras que las ciencias naturales ofrecen explicaciones causales, las ciencias sociales ofrecen explicaciones interpretativas o hermenéuticas que, se dice, no son causales. Y, a la luz de Sect. 4.1, una forma de desarrollar esa posición es argumentar que la explicación que apela a la agencia es una forma de explicación no causal. Argumentaré, en contra de ese punto de vista, que no hay tensión entre agencia y causalidad. La agencia es un fenómeno causal. Y explicar una acción en términos de las razones del agente para realizarla es una especie de explicación causal. Defenderé ese punto de vista contra una serie de argumentos de la tradición no causalista. Si la agencia es fundamental para la explicación económica, como he argumentado en la Secta. 4.1 , entonces también lo es la causalidad.

Se han asociado muchas posiciones diferentes con la frase "teoría causal de la acción". Y las afirmaciones que rechazan los críticos del causalismo a menudo resultan ser diferentes de las que defienden los propios causalistas. Por tanto, es importante tener claro lo que implica una visión causal de la acción o agencia. La afirmación central, según yo la entiendo, es que la explicación de la razón es una forma de explicación causal; explicar una acción citando las razones del agente para realizarla es una forma de explicar causalmente la acción. (Lo mismo se aplica, mutatis mutandis, para explicar las creencias o intenciones de un agente citando sus razones para formarlas o retenerlas.) A menudo se considera que los causalistas sobre la acción están haciendo una afirmación diferente y más ambiciosa: que podemos dar un análisis no circular de lo que es para algo. ser una acción en términos de los conceptos de movimiento corporal, creencia, deseo o actitud proactiva y causalidad. Pero eso no forma parte de la teoría causal tal como yo la entiendo. Supongamos que Sarah levanta el brazo. La afirmación central es, como he dicho, que explicar por qué Sarah levantó el brazo citando su razón para hacerlo es una forma de explicación causal. El objetivo de la teoría causal es comprender la forma de ese tipo de explicación; no se ocupa de analizar el fenómeno de la acción en partes más simples. De modo que los argumentos en contra de la posibilidad de una explicación reductiva de lo que significa que algo sea una acción no son en sí mismos argumentos en contra de una visión causal de la razón-explicación. El teórico causal puede aceptar que "Sarah levantó el brazo" y "la acción de Sarah de levantar el brazo" son básicas e inanalizables.

Defenderé la visión causal de la razón-explicación contra dos críticas que son prominentes en la tradición no causalista. La primera es que no hay una buena razón para aceptar el punto de vista causal y, en particular, que el argumento clásico de Donald Davidson para un punto de vista causal de la acción es ineficaz^[Para el argumento de Davidson, vea Davidson 1963.]. El segundo es que el punto de vista causal no puede ser verdadero porque el carácter de la explicación de la razón es inconsistente con los requisitos de la explicación causal. Responderé a esas críticas a su vez.

### Defensa del argumento básico para una visión causal de la razón-explicación {-}

¿Cuál es el argumento de Davidson a favor de una visión causal de la razón-explicación? Aquí hay dos pasajes famosos de 'Acciones, razones y causas':

> una persona puede tener una razón para una acción y realizar la acción, y, sin embargo, esta razón no puede ser la razón por la que lo hizo. En el centro de la relación entre una razón y una acción que explica es la idea de que el agente realizó la acción porque tenía la razón (Davidson1963, 9).
>
> Una forma en que podemos explicar un evento es colocándolo en el contexto de su causa; la causa y el efecto forman el tipo de patrón que explica el efecto, en un sentido de "explicar" que entendemos tan bien como cualquiera. Si la razón y la acción ilustran un patrón diferente de explicación, ese patrón debe identificarse (Davidson1963, 10).

Podemos resumir el punto de Davidson de esta manera. Podemos explicar el $\phi$-ing de S citando su razón para $\phi$-ing. Suponga que R fue la razón de S para $\phi$-ing. Entonces podemos decir que S $\phi$-d porque R, o porque ella tenía R. Para entender qué tipo de explicación es esa, necesitamos entender la fuerza del 'porque' que contiene. Y la reflexión muestra que no existe una alternativa seria para entender el "porque" como un "porque" causal. Entonces, explicar una acción citando la razón del agente es una forma de explicación causal.

Una respuesta natural al argumento de Davidson es preguntarse si nos ha dado alguna razón para pensar que el "porque" en la explicación-razón tiene que ser un "porque" causal. Después de todo, "porque" se usa a menudo de formas que no tienen nada que ver con la causalidad. Considere los siguientes casos: '7 es un número primo porque es divisible solo entre 1 y él mismo', 'La delantera estaba en fuera de juego porque no había defensores entre ella y el portero cuando se pasó el balón', 'María es mi hermana- suegra porque está casada con mi hermano '. En cada una de esas oraciones, "porque" aparece en una explicación. Pero ninguna de esas explicaciones implica causalidad, y ninguno de esos casos de "porque" es un "porque" causal. Entonces, ¿qué hay en el "porque" en la explicación-razón que justifica la afirmación de que es un "porque" causal? Para responder a esa pregunta, necesitamos considerar qué es lo que explica una explicación-razón. Cuando explico por qué alguien hizo algo, estoy explicando un cambio u ocurrencia en el mundo natural: estoy explicando por qué sucedió algo; por qué ocurrió un evento. Y explicar por qué sucedió o sucedió algo, está en su naturaleza dar una explicación causal. Los usos no causales de "porque" pueden explicar muchas cosas. Pueden explicar por qué un número, algo que no tiene causas ni efectos, es un número primo, mostrando cómo se ajusta a la definición de primo; pueden explicar por qué un jugador, cuya existencia y posición en el campo se dan por dadas, cuenta como fuera de juego, mostrando cómo cumple las condiciones para estar fuera de juego; pueden explicar por qué una persona, cuya existencia y estado civil se dan por dados, cuenta como mi cuñada, mostrando cómo cumple con las condiciones para ser mi cuñada (califica como mi cuñada por estar casada con mi hermano, en lugar de ser la hermana de mi esposa). Pero una explicación no causal nunca puede explicar por qué algo sucedió o llegó a existir, o por qué algo cambió en el mundo. Para explicar esas cosas, necesitamos una explicación causal^[Puede haber eventos o cambios que no tengan causas. No son contraejemplos del principio general de que explicar por qué sucedió u ocurrió algo requiere una explicación causal. Si un evento no tiene causas, entonces su ocurrencia no puede explicarse de alguna manera no causal; al contrario, no se puede explicar en absoluto.].

Con eso en mente, podemos considerar una versión particular de la objeción actual al argumento del causalismo. A veces se afirma que el argumento de Davidson a favor del causalismo depende del supuesto gratuito de que solo hay un tipo de explicación: explicación causal. Y, se dice, no hay razón para aceptar eso. De modo que podemos responder al argumento de Davidson insistiendo en que, contrariamente a lo que él afirma, existe una forma alternativa, no causal, de entender el "porque" en la explicación-razón; puede entenderse en términos de la relación primitiva e inanalizable de actuar por una razón. Aquí hay dos ejemplos de ese tipo de argumento:

> La respuesta más directa a Davidson [es] que la diferencia entre las razones por las que el agente actuó de hecho y aquellas por las que podría haber actuado, pero no lo hizo, no es una diferencia en absoluto en el papel causal. Es sólo la diferencia entre las consideraciones a la luz de las cuales actuó y otras consideraciones que tomó para favorecer actuar como lo hizo, pero que en realidad no fueron las que a la luz de las cuales decidió hacer lo que hizo. (Dancy2000, 163)
>
> Presionado para establecer en otros términos la diferencia entre tener una justificación para actuar y actuar en consecuencia, una respuesta es que no se puede y no tiene que ser. Así, Dancy toma la relación, sobre la base de eso , como primitiva. Davidson no da ningún argumento en contra de esto. (Setiya2009, 145)

La sugerencia, entonces, es que podemos simplemente tratar el 'porque' en 'Ella $\phi$-d porque ella tenía R' como si escogiera una relación primitiva. De modo que los fundamentos de Davidson para una visión causal de la explicación de la razón `` son radicalmente inadecuados '' (Wilson1985, 40); no hay ningún caso para el causalismo en absoluto. Pero esta línea de respuesta al argumento de Davidson es completamente ineficaz. No comprende la estructura y la fuerza del argumento.

El causalista acerca de la razón-explicación puede estar de acuerdo en que podemos pensar en el 'porque' en 'Ella $\phi$-d porque tenía razón R' en términos de la relación de actuar por una razón o actuar a la luz de una razón . Si ella $\phi$-d porque tenía razón R, entonces es cierto que ella $\phi$-d a la luz de la razón R o, más simplemente, por la razón R. El causalista también puede estar de acuerdo en que la relación de actuar por una razón, oa la luz de una razónes primitivo; no puede analizarse reductivamente, en otros términos. Pero nada de eso debilita la fuerza del argumento del causalismo. El punto fundamental del argumento es este: la reflexión sobre la forma de explicación-razón muestra que el 'porque' en 'Ella $\phi$-d porque tenía R' es un 'porque' causal debido a lo que explica una explicación-razón: es decir, un cambio u ocurrencia en el mundo natural. Y ese punto fundamental no se ve afectado por estos argumentos. Los críticos insisten en que la relación entre una razón y una acción que se explica por esa razón es simplemente la relación de actuar por la razón. Pero esa no es una alternativa a la visión causal. Porque la fuerza del argumento original de Davidson todavía se aplica a la relación de actuar por una razón. El argumento muestra que la noción de actuar por razón R es en sí misma una noción causal; y explicar una acción citando una razón por la que actuó el agente es en sí misma una forma de explicación causal.

Por supuesto, como he dicho, no todo "porque" es un porque causal, y no todo tipo de explicación es una forma de explicación causal. Entonces, en algunos casos, sería perfectamente correcto responder a un argumento con la apariencia superficial del argumento de Davidson insistiendo en que el "porque" en cuestión marca una relación primitiva, no causal. Supongamos que estoy considerando posibles razones para que el Museo Británico devuelva los mármoles del Partenón a Atenas. Aquí hay tres de esas razones:

> (I) El Museo Británico dañó los Mármoles en la década de 1930 por una limpieza inadecuada;
>
> (II) Las personas que vendieron los Mármoles a Lord Elgin eran gobernantes coloniales, no griegos;
>
> (III) Atenas sería un sitio cultural y físicamente superior para exhibir los mármoles.

Supongamos que tengo las siguientes opiniones. Los Mármoles deberían devolverse a Atenas. Cada uno de (i) - (iii) es verdadero. Cada uno de (i) - (iii) da una razón genuina para devolver las Canicas; todos cuentan a favor de la devolución de las canicas. Pero, considerando todo, la razón por la que las canicas deben ser devueltas es (iii), y no (i) o (ii): todavía sería correcto devolver las canicas incluso si (i) y (ii) fueran falsas; y no sería correcto devolver las canicas si (iii) fuera falso, incluso si (i) y (ii) todavía fueran verdaderos.

Ahora, podemos preguntarnos cuál es la diferencia entre 'Los Mármoles deberían devolverse y Atenas sería un sitio mejor para exhibirlos que Londres' y 'Los Mármoles deberían devolverse porque Atenas sería un sitio mejor para exhibirlos que Londres'; ¿Cuál es la fuerza del "porque" en la última proposición? En este caso, sería claramente un error concluir que la diferencia entre 'p y q' y 'p debido a q' es una diferencia causal. En consecuencia, es bastante correcto decir que el 'porque' en 'Los Mármoles debería devolverse porque Atenas sería un sitio mejor para exhibirlos' expresa una relación primitiva, no causal: la relación de ser la razón por la cualse debe hacer algo. La razón para decir que el "porque" en este caso no es causal es, como antes, la naturaleza de lo que se explica. Cuando explico por qué los mármoles del Partenón deberían devolverse a Atenas, no estoy explicando por qué sucedió algo; No estoy explicando la ocurrencia de nada: un cambio o un evento en el mundo. Estoy explicando por qué sería correcto un curso de acción en particular. Y hacer eso no es dar una explicación causal.

La intuición detrás de la respuesta al argumento de Davidson que dan Dancy y otros es que la diferencia entre 'pyq' y 'p porque q' no siempre es una diferencia causal. Pero, como he dicho, el defensor del argumento de Davidson está de acuerdo con ese punto. Si un "porque" particular es o no causal depende del tipo de explicación involucrada en el caso particular. Parece claro que, cuando explicamos que alguien está haciendo algo citando su razón para hacerlo, estamos explicando por qué sucedió algo o por qué ocurrió un evento. Y hacer eso es dar una explicación causal.

### Las muchas caras de la explicación causal {-}

Muchos escritores de la tradición no causalista han argumentado que la razón-explicación no puede ser una forma de explicación causal porque no encaja en el patrón de explicar algo en términos de sus causas. Doy tres ejemplos de argumentos de este tipo.

> Las razones de las acciones no son estados mentales, como creencias, deseos, intenciones, etc. Más bien, son hechos sobre el mundo no mental. Por lo tanto, son el tipo de cosas incorrectas para ser las causas de la acción^[Para el punto de vista de que las razones de un agente para actuar como lo hace son típicamente hechos sobre el mundo externo, en lugar de estados mentales, ver, por ejemplo, Alvarez. 2010, cap. 6. La propia Álvarez permanece neutral sobre las implicaciones de su visión de las razones para la tesis de que la explicación de la razón es una forma de explicación causal (ver Álvarez 2010, págs. 199-200). Pero otros son menos cautelosos y consideran que el punto de vista del "hecho" de las razones es incompatible con un punto de vista causal de la explicación de la razón.].
>
> La explicación de la razón funciona al hacer que las acciones sean inteligibles al ponerlas en un contexto que les da sentido. No funciona citando las causas de las acciones^[Para una declaración reciente de esta posición, vea Tanney 2009. Como dice Tanney, este tipo de visión se remonta al menos a Ryle. 1949, así como a Anscombe 1959, Melden 1961y otros trabajos de la tradición wittgensteiniana de los años cincuenta y sesenta.].
>
> Explicar el $\phi$-ing de S citando su razón para $\phi$-ing es dar el propósito con el que ella $\phi$-d: decir lo que estaba tratando de hacer con $\phi$-ing. Pero el propósito con el que alguien actuó no es la causa de su actuación. Supongamos que Bob se pone de cabeza para impresionar a Claudia. Impresionar a Claudia era su propósito al ponerse cabeza abajo; estaba tratando de impresionar a Claudia poniéndose de cabeza. Pero su intento de impresionar a Claudia fue simplemente estar de cabeza; no fue otra cosa, lo que precedió a su cabeza. Por lo que no podría ser la causa de su acción^[Para este argumento, vea McLaughlin 2013.].

Estas objeciones anticausalistas, y otras similares, argumentaré, funcionan asumiendo una concepción muy restringida de la forma que puede tomar una explicación causal. En particular, adoptan una visión muy restringida de cómo debería ser la razón-explicación para ser una forma de explicación causal. Muy crudamente, asumen que algo solo calificará como una explicación causal de una acción si funciona citando estados o eventos dentro de un agente que causan los movimientos de su cuerpo. Pero las explicaciones causales son mucho más diversas. Una vez que se aprecia ese punto, podemos ver que mucho de lo que los críticos han insistido sobre las formas en que funcionan las explicaciones-razón es de hecho perfectamente consistente con una visión causal de la explicación-razón.

Las explicaciones causales en general pueden tomar muchas formas. Dar una explicación causal es simplemente contar, o sugerir, una historia causal que ayuda a hacer algo inteligible. Pero hay muchas formas en las que podemos contar una historia causal. Y algo puede ser una historia causal sin citar explícitamente la causa de un efecto. Podemos ilustrar ese punto con un ejemplo. Se rompe una copa de vino. Preguntamos por qué se rompió. Aquí hay algunas posibles respuestas:

> (a) Fue golpeado con un martillo
>
> (b) era frágil
>
> (c) Estaba hecho de material inferior
>
> (d) La voz de la soprano era tan penetrante
>
> (e) El agua de lavar estaba demasiado caliente.

Todas esas son, en las circunstancias pertinentes, explicaciones legítimas de la rotura del vidrio. Y todas son explicaciones causales. Pero toman diferentes formas. En (a), un evento (la rotura del vidrio) se explica citando su causa (haber sido golpeado por un martillo). En (b) y (c), no se nos dice exactamente qué fue lo que causó la rotura del vidrio. En cambio, se nos habla de una propiedad del vidrio (era frágil; estaba hecho de vidrio inferior). Eso explica el efecto (la rotura del vidrio) al hacerlo inteligible por qué algún evento (que no está especificado y puede ser desconocido) causó el efecto que causó. Si el vidrio no hubiera sido frágil, o no hubiera sido hecho de un material inferior, el evento que realmente causó su rotura no lo habría hecho. En (d) y (e) se nos dice acerca de una característica de la causa ,o de las circunstancias circundantes, que, como antes, explica el evento al permitirnos ver por qué la causa tuvo el efecto que tuvo. En (d), está implícito que la causa de la rotura del vidrio fue el canto de la soprano; pero si su voz no hubiera sido tan penetrante, su canto no habría tenido el efecto que tuvo. En (e) está implícito que la causa de la rotura fue que el vaso se puso en el lavaplatos; pero si el agua no hubiera estado tan caliente como estaba, esa causa no habría producido el efecto que produjo.

De la misma manera, una explicación de una acción puede tomar muchas formas, de acuerdo con que sea una explicación causal. Podemos ilustrar ese punto en relación con dos de las sugerencias sobre formas de explicación de la razón que se mencionaron anteriormente.

Supongamos que estamos de acuerdo en que las explicaciones de la razón a menudo explican las acciones citando hechos sobre el mundo externo, en lugar de mencionar los estados mentales del agente. Así, por ejemplo, salió por la ventana porque la puerta estaba cerrada (no: porque creía que la puerta estaba cerrada). Eligió la ensalada porque era más saludable que las otras opciones.(no: porque creía que era más saludable). Los hechos a los que se apela en esas explicaciones no son hechos sobre el estado mental de los agentes. Pero eso no es una barrera para entender estas explicaciones como explicaciones causales. Porque los hechos sobre el mundo no mental pueden explicar causalmente que los agentes hagan cosas. Tomemos el caso en el que alguien salió por la ventana porque la puerta estaba cerrada. Esa explicación no nos dice cuál fue la causa desencadenante de su acción. Pero nos dice algo sobre el contexto que hace inteligible por qué la causa desencadenante, cualquiera que sea, produjo el tipo de efecto que tuvo: un acto de salir por la ventana, en lugar de un acto de salir por la puerta. Supongamos que la causa desencadenante de su salida de la habitación fue, por ejemplo, que se dio cuenta de que eran las 3 de la tarde o que recibió un mensaje pidiéndole que asistiera a una reunión. Citamos el hecho de que la puerta estaba cerrada para explicar por qué salió de la habitación por la ventana en lugar de por la puerta. Y esa es una explicación causal. El hecho de que la puerta estuviera cerrada solo explica que saliera por la ventana si salía por la ventana.porque la puerta estaba cerrada. (Supongamos que ella se hubiera escapado por la ventana de todos modos, tanto si la puerta estaba cerrada como si no. Entonces no es cierto que ella saliera por la ventana porque la puerta estaba cerrada). Y existen las razones habituales para decir eso ' porque 'es casual.

De manera similar, el causalista aceptará que cuando explicamos una acción dando las razones del agente para realizarla, la estamos explicando en términos del objetivo o propósito del agente. 'Estaba tratando de impresionar a Claudia', o 'Para impresionar a Claudia', son respuestas legítimas a la pregunta, '¿Por qué se puso cabeza abajo?' Explican por qué hizo lo que hizo. Pero, dirá el causalista, eso es totalmente compatible con la afirmación de que la explicación que da razón es una forma de explicación causal. Como antes, ni 'Intentaba impresionar a Claudia' ni 'Para impresionar a Claudia' nos dicen la causa desencadenante de su acción de ponerse de cabeza. Pero sí nos dicen algo sobre las propiedades mentales del agente: que tenía la intención de impresionar a Claudia y creía que ponerse cabeza abajo sería una forma de hacerlo. Y eso hace inteligible por qué la causa desencadenante de su acción, cualquiera que fuera (por ejemplo, notar que Claudia se acercaba), produjo el efecto que produjo: un acto de ponerse de cabeza. Ese es un tipo de historia causal que hace inteligible la ocurrencia de una acción; es una forma de explicar causalmente la acción.

### Conclusión {-}

No hemos encontrado ninguna razón para abandonar la opinión de que explicar una acción dando las razones del agente para realizarla es una forma de explicación causal. En primer lugar, la sugerencia de que podemos simplemente pasar por alto el argumento de Davidson sobre el causalismo al tratar la relación de actuar por una razón como una relación básica no causal no comprende la fuerza del argumento. Puede haber buenas razones para tratar la actuación por la razón Rcomo una relación básica e inanalizable. Pero si lo hacemos, debemos reconocer que la noción de actuar por una razón es en sí misma una noción causal. En segundo lugar, la sugerencia de que las explicaciones que dan razones no encajan en el modelo de la explicación causal no logra apreciar la diversidad de los tipos de explicación causal. Concluyo que no hay posibilidad de distinguir la explicación en economía (y otras ciencias sociales) de la explicación en las ciencias naturales aceptando (i) que la explicación económica depende de la agencia, pero sosteniendo (ii) que las explicaciones que apelan a la agencia no son causales. explicaciones. De hecho, la explicación científica social es diferente de la explicación científica natural. Pero la razón de esto no es que la explicación científica social no sea causal. Es, más bien, que la explicación científica social se basa enexplicación causal que da razón en lugar de explicación causal meramente física, que no da razón.

## La causalidad en las ciencias sociales y en las ciencias naturales {-}

A veces se dice que las relaciones causales de las ciencias naturales son un paradigma mal concebido para las ciencias sociales. Si tratamos las ciencias sociales como una forma de ciencia causal, se dice, reducimos a los seres humanos a objetos naturales; Drenamos la agencia humana de contenido moral. Y eso distorsiona y falsea la ontología de agentes y acciones que es fundamental para las ciencias sociales. Estoy de acuerdo en que la explicación en las ciencias sociales es ciertamente distintiva; es de un tipo diferente de la explicación en las ciencias naturales. Pero eso no impide que la explicación científico-social sea una forma de explicación causal; esa era la carga de la Secta. 4.2, encima. Tampoco significa que los fenómenos y procesos causales que estudian las ciencias sociales sean completamente independientes de los fenómenos y procesos causales que son objeto de estudio de las ciencias naturales. Esa es la posición que defiendo en el apartado actual.

Por un lado, entonces, los fenómenos y las explicaciones de las ciencias sociales son irreductibles a los fenómenos y explicaciones que se encuentran en las ciencias naturales. Por otro lado, existe una estrecha relación entre los fenómenos causales estudiados en las ciencias sociales y los fenómenos causales estudiados por las ciencias naturales. Podemos poner esa relación en términos de determinación. Los hechos físicos de bajo nivel determinan todos los hechos. Si determina completamente la estructura física del mundo y las leyes científicas naturales, entonces determina completamente todos los fenómenos: incluidas todas las propiedades mentales, morales, económicas, sociológicas, etc. de los seres humanos. Lo mismo ocurre con la causalidad. Si determina completamente todos los hechos causales de bajo nivel, determina todos los hechos causales: incluidos los hechos causales sobre agentes y acciones.

¿Qué deberíamos decir sobre la queja de que la interpretación de las ciencias sociales como una forma de ciencia causal implica reducir a los seres humanos a objetos naturales? Bueno, los seres humanos somosobjetos naturales. Estamos completamente compuestos de materia, cuyo comportamiento, en el nivel micro, no es diferente del comportamiento de otros fragmentos de materia natural y, en principio, puede describirse y explicarse completamente sin apelar a los conceptos de agencia o razones para actuar. Nuestra visión de la agencia y la razón-explicación no debe entrar en conflicto con esa obviedad. Pero la perogrullada no implica que todo lo relacionado con los seres humanos pueda entenderse si describimos a las personas al nivel de su diminuta composición física. No puede ser. Reconocer el carácter distintivo de la agencia y la razón-explicación, sin embargo, es consistente con aceptar, primero, que los seres humanos son seres naturales y materiales, y segundo, que fijar los hechos causales de bajo nivel arregla los hechos sobre la agencia. En ese sentido,

¿Qué deberíamos decir sobre la queja de que tratar las ciencias sociales como una especie de ciencia causal distorsiona o falsifica la ontología de agentes y acciones? La mera idea de que la explicación de la razón es una forma de explicación causal no tiene efectos de revisión sobre la ontología de las ciencias sociales. Las historias causales involucradas en las explicaciones de la agencia, y en las ciencias sociales en general, son historias sobre agentes que hacen cosas y toman decisiones a la luz de sus creencias, preferencias, circunstancias, etc. Y, como sostuve en la Secta. 4.1, los mecanismos causales que sustentan la explicación económica involucran esencialmente a las personas. No hay nada de distorsionador o revisionista en eso. Pero ¿habrá consecuencias revisionistas para la ontología de las ciencias sociales si también aceptamos, como he sugerido, que todos los hechos causales están determinados por los hechos de bajo nivel de la causalidad física? Eso depende de cómo se diga exactamente que funcionan las relaciones entre niveles.

Desde un punto de vista, la ontología de las ciencias sociales es la misma que la ontología de las ciencias físicas. La realidad causal, desde ese punto de vista, comprende una red de eventos causalmente interrelacionados, que constituyen la ontología común de toda investigación humana. Cada historia causal selecciona y describe eventos que pertenecen a este conjunto de eventos común y neutral en cuanto al tema. Pero las historias causales en diferentes dominios (el dominio de las ciencias naturales y el dominio de las ciencias sociales, por ejemplo) las seleccionan de diferentes maneras y las organizan en diferentes clases o patrones. Entonces, en particular, aunque las descripciones y explicaciones de la psicología del sentido común o las ciencias sociales no pueden reducirse a las de las ciencias naturales, seleccionan los mismos eventos. En ese sentido, las ciencias sociales y las ciencias naturales tienen una ontología común^[Esa es esencialmente la imagen que ofrece el monismo anómalo de Davidson (ver Davidson 1970, 1973, 1974).].

Pero esa no es una visión plausible de la relación entre los diferentes dominios. Considere la relación entre lo mental y lo físico. Parece claro que los sucesos mentales individuales, del tipo descrito en el vocabulario de la psicología del sentido común, no son idénticos a los sucesos microfísicos individuales, de los tipos descritos por la neurociencia, la química o la física. Porque los eventos microfísicos particulares son mucho más pequeños, tanto espacial como temporalmente, que cualquier evento mental individual. Una respuesta natural a ese punto es decir que los eventos mentales se componen deeventos microfísicos; dondequiera que haya un evento mental particular, podríamos, en principio, reunir una colección de eventos microfísicos que ocupen colectivamente la misma región espaciotemporal que ese evento mental. Eso es verdad. Pero no salva la imagen de la realidad como un conjunto único de eventos neutros sobre el tema que son comunes a todas las áreas de investigación. Porque la colección de eventos microfísicos que componen conjuntamente un evento mental particular no es en sí misma un evento físico individual: no existe una forma natural de distinguirlo en el vocabulario de las ciencias físicas; no tiene ningún interés particular desde el punto de vista de las ciencias físicas; no figura en esas ciencias como causa o efecto. La existencia de eventos mentales no requiere la existencia de nada más que la totalidad de eventos microfísicos. Pero, por las razones que acabamos de dar, eso no significa que la psicología del sentido común y las ciencias físicas tengan una ontología común de eventos. Lo mismo ocurre con las ciencias sociales y humanas en general^[Para el argumento resumido en este párrafo, vea Hornsby 1980–81.].

Necesitamos una imagen más flexible de la relación entre diferentes tipos o niveles de descripción y explicación. Así es como creo que funcionan las cosas. Existen numerosos niveles diferentes de descripción que podemos ocupar cuando describimos el mundo: el nivel de física fundamental; el nivel de química; los niveles de psicología, economía, etc. Y existen numerosas explicaciones causales diferentes, que podemos dar cuando ocupamos estos diferentes niveles. Supongamos, por ejemplo, que alguien compra un boleto en una máquina de estacionamiento. Podemos contar una historia física sobre las causas de los movimientos de su cuerpo que están involucrados en que ella haga lo que hizo. Y podemos contar una historia psicológica de sentido común sobre su actuación por una razón. Ambas son explicaciones causales. Pero explican cosas diferentes. La historia física explica el movimiento de un trozo de cuerpo humano. La historia psicológica explica que una persona está haciendo algo. Pero, aunque las dos historias causales son diferentes, la historia psicológica no es completamente independiente de los procesos causales de bajo nivel descritos por la historia física. Cuando alguien compra un boleto para estacionar su automóvil, los procesos causales físicos continúan en su cuerpo. Si ese proceso físico no se llevó a cabo, no habría ninguna acción de comprar un boleto. La causalidad mental, como hemos dicho, no flota libre de la causalidad física. los procesos causales físicos continúan en su cuerpo. Si ese proceso físico no se llevó a cabo, no habría ninguna acción de comprar un boleto. La causalidad mental, como hemos dicho, no flota libre de la causalidad física. los procesos causales físicos continúan en su cuerpo. Si ese proceso físico no se llevó a cabo, no habría ninguna acción de comprar un boleto. La causalidad mental, como hemos dicho, no flota libre de la causalidad física.

Pero si insistimos en que todos los hechos causales están determinados por los hechos causales físicos de bajo nivel, ¿no tenemos que decir algo más sobre la relación entre las historias causales de alto nivel y las de bajo nivel: sobre cómo se casan exactamente las dos historias? ¿arriba? Algunos han argumentado que solo puede haber explicaciones causales genuinas en psicología y ciencias sociales si existen correlaciones detalladas, similares a leyes, entre los fenómenos de nivel superior identificados por la psicología o las ciencias sociales y los fenómenos microfísicos de bajo nivel que determinan el nivel superior. -Nivel de hechos causales. Si no existen correlaciones similares a leyes entre los diferentes niveles, se argumenta, entonces las explicaciones ofrecidas por la psicología o las ciencias sociales no serán mejores que las pseudoexplicaciones presentadas por la astrología o la homeopatía. Serán historias que nos contamos a nosotros mismos: formas que tenemos de tratar de darle sentido al mundo. Pero no tendrán nada que ver con por qué suceden realmente las cosas; no serán explicaciones causales verdaderas o correctas.

Una respuesta a ese pensamiento debe abordar dos preguntas. Primero, ¿qué razón hay para pensar que la explicación en psicología y ciencias sociales es una forma genuina de explicación causal? En segundo lugar, ¿qué debe ser cierto de la relación entre hechos de nivel superior y hechos de nivel inferior para que sea cierto que los hechos de nivel superior son causalmente explicativos? Tomo esos puntos en orden.

Podemos tener buenas razones para pensar que la psicología y las ciencias sociales dan explicaciones causales genuinas, mientras que la astrología y la homeopatía no lo hacen, sin conocer nada en detalle acerca de las correlaciones específicas entre hechos científicos psicológicos o sociales, por un lado, y de nivel inferior. hechos físicos, por el otro. En primer lugar, la psicología y las ciencias sociales son prácticas explicativas exitosas, cuyas afirmaciones cumplen con los estándares normales de explicabilidad. Presentan afirmaciones causales sustanciales cuya verdad es susceptible de confirmación o refutación sobre la base de la experiencia. Y lo que es más importante, las explicaciones en psicología y ciencias sociales no compiten con explicaciones causales físicas de nivel inferior; operan a un nivel diferente y tienen diferentes explicaciones y. Entonces, los fenómenos que pretenden explicar, que tienen que ver con las elecciones y acciones de los agentes, no se explican mejor en términos más básicos, de nivel inferior: por el contrario, no se pueden explicar en absoluto en ese nivel. Eso contrasta con las supuestas explicaciones de la astrología o la homeopatía, que compiten con otras explicaciones. La astrología tiene como objetivo explicar las características de una persona y el éxito o fracaso de sus relaciones y carrera haciendo referencia a las posiciones de los planetas. Pero los mismos fenómenos pueden explicarse completamente de otras formas sin apelar a las posiciones de ningún cuerpo celeste. La homeopatía tiene como objetivo producir y explicar mejoras en el estado de salud de una persona haciendo referencia, por ejemplo, a las cualidades de sustancias que están demasiado diluidas para contener cualquier rastro físico de su ingrediente supuestamente activo.

Por tanto, hay buenas razones, sobre la base de nuestro conocimiento ordinario, para considerar las explicaciones científicas psicológicas y sociales como explicaciones causales genuinas. Al mismo tiempo, he sugerido, debemos aceptar un compromiso básico y de fondo con la idea de que todos los hechos causales están determinados por hechos causales de bajo nivel del tipo trazado por las ciencias naturales. Y si eso es cierto, entonces para que las explicaciones científicas psicológicas y sociales sean genuinamente explicativas causalmente, debe haber alguna conexión entre las propiedades de nivel superior que citamos al dar tales explicaciones y los hechos causales subyacentes de nivel inferior que, en última instancia, determinar todos los hechos causales. Si no hubiera ninguna conexión, No habría forma en que la posesión de una cosa de propiedades psicológicas o científico-sociales de alto nivel pudiera afectar su comportamiento causal. Pero la conexión no tiene por qué ser estrecha o sistemática. Lo que se requiere es simplemente que las propiedades de nivel superior sobrevengan a las propiedades de nivel inferior: es decir, que, si dos mundos son iguales con respecto a todas las propiedades de nivel inferior, también deben ser iguales con respecto a todas las propiedades de nivel superior. propiedades de nivel, psicológicas, económicas, sociológicas, etc.

El hecho de la superveniencia por sí solo no es suficiente, en sí mismo, para mostrar que las propiedades psicológicas, digamos, son genuinamente explicativas causalmente. El argumento para pensar que son genuinamente explicativas de forma causal proviene del punto esbozado en el párrafo anterior: que la psicología del sentido común ofrece explicaciones causales que cumplen con los estándares normales de una práctica explicativa exitosa. Pero para que las explicaciones de la psicología sean genuinamente explicativas causalmente, como sabemos que son, la afirmación de superveniencia debe ser cierta. Pues considere cómo serían las cosas si la afirmación de superveniencia no fuera cierta. Dos mundos podrían diferir en aspectos mentales sin diferir con respecto a propiedades físicas de nivel inferior. Pero en ese caso, esas diferencias mentales no podrían hacer ninguna diferencia en el comportamiento de las personas. Porque, hemos dicho, los hechos causales están completamente determinados por los hechos físicos de bajo nivel. Si las propiedades mentales han de tener implicaciones causales, entonces deben superponerse a los hechos físicos de bajo nivel. Pero no es necesario que exista una relación más sólida o sistemática entre los dos niveles que esa. Aceptar que todos los hechos causales están determinados por hechos físicos de nivel inferior es compatible con insistir en el carácter distintivo de las ciencias sociales y humanas y su irreductibilidad a las ciencias físicas^[Una versión anterior de este documento se presentó en el simposio, 'Causation, Agency, and Supervenience', en Las Casas Institute, Blackfriars Hall, Oxford en julio de 2018. Parte del material también se presentó en un taller, 'Ascription, Causation , and the Mind ', en la Universidad de Utrecht en mayo de 2016. Agradezco a los participantes en ambas ocasiones sus útiles comentarios y discusiones.].