# (PART) Parte III: Palabras, objetos y eventos en economía {-}
# Hecho con palabras {#Capitulo_11}

```{r, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "html", results='asis', echo=FALSE}
cat('<hr style="background-color:#03193b;height:2px">')
```

Las ciencias naturales estudian objetos; las ciencias sociales se ocupan de los acontecimientos. Los objetos tienen propiedades, los eventos son producto de la intencionalidad humana. La economía moderna se basa en el supuesto de que los eventos pueden transformarse mediante un proceso de abstracción en cosas con propiedades del tipo que permite la formulación de generalidades similares a leyes. Estos supuestos han dado lugar al paradigma del agente económico libre de valores. Este artículo rechaza este paradigma y defiende la afirmación de que la domesticación de la metodología de las ciencias naturales en la economía es un error de categoría. En cambio, la economía debería desarrollar una metodología que sea adecuada para su tema.

> "Y me pregunto si la conciencia del hombre fue un error de Dios".
>
> (Thomas Hardy, ahora viajo como un fantasma )

## Introducción {-}

La ambición de la economía moderna de parecerse en la mayor medida posible a las ciencias naturales implica la reconstrucción de los procesos económicos en objetos que se asemejen a los objetos de las ciencias naturales. Este movimiento permite el uso de teorías de causalidad que son análogas a la causalidad en las ciencias naturales donde la causalidad depende de las propiedades de los objetos que participan en el fenómeno en estudio. Pero los acontecimientos económicos, a diferencia de los objetos de la naturaleza, se producen a través del esfuerzo y la intención humanos. Sus características no las da la naturaleza sino el agente humano. Los objetos naturales no tienen significado; Las intenciones humanas están cargadas de valor inherente, producto de la voluntad y el intelecto humanos. La economía moderna elimina la voluntad y el intelecto humanos del dominio que estudia y trata el resto como si fuera el tipo de objeto que se encuentra en la naturaleza, como moléculas, compuestos, árboles o la corriente eléctrica. Con la ayuda indispensable de esta escisión, la economía moderna formula generalizaciones similares a leyes que describen los acontecimientos económicos como fenómenos sin contenido moral. Pero este resultado está fundamentalmente en desacuerdo con la experiencia humana, y ciertamente no está respaldado por su historial predictivo o explicativo. El resultado es que los procesos reales de la vida económica, que descansan como lo hacen en la voluntad y el intelecto humanos, derrotan regularmente el poder predictivo y explicativo de la economía moderna, construida para ser inocente de esa voluntad e intelecto. La tensión es obvia. O existen leyes económicas de aplicabilidad universal o la vida económica es, al menos en parte, la vida de la mente y la voluntad humanas. La tercera alternativa, a saber, que toda la humanidad es de la misma mente y voluntad, no requiere el asentimiento de nadie que no sea un economista profesional.

El título de este artículo, “Hecho con palabras” proviene de Thomas Hobbes y de una época muy consciente de la diferencia ontológica entre las ciencias naturales y morales, en la que la primera se ocupa de las propiedades de los objetos corporales en oposición al comportamiento de los seres humanos. entidades incorpóreas o morales^[La frase de Hobbes fue ampliamente explorada en el contexto de la teoría política por Pettit (2008).]. El siglo XVII y los dos primeros tercios del siglo XVIII, todavía bajo la influencia del dualismo cartesiano, creían firmemente en la existencia de un mundo tanto físico como no físico, pero a finales del siglo XVIII la unidad de la naturaleza se había convertido en axiomático, y la idea de que el método científico de las ciencias naturales podría extenderse a la realidad social ya fue propuesta por Newton y respaldada de todo corazón por, entre otros, Diderot y D'Alembert. Como dijo Newton, "si la filosofía natural en todas sus partes, siguiendo este Método, se perfeccionara finalmente, los límites de la filosofía moral también se ampliarían". A lo largo del siglo XIX y XX, la economía, nacida con Adam Smith y los albores del Racionalismo, Volvió a la noción de la unidad de la naturaleza y la aplicabilidad de los métodos de las ciencias naturales a toda la realidad con un fervor cada vez más ingobernable. Einstein afirmó que la economía podría reducirse a la microfísica, y algunos positivistas lógicos pensaron que la sociología no era más que una instanciación particular de la genética molecular. El axioma de la unidad de la naturaleza supuso durante gran parte de los siglos XIX y XX el eclipse de la ontología y, en consecuencia, introdujo un largo período durante el cual lanaturaleza de la materia objeto de estudio, el examen de sus propiedades se ignoró en gran medida. La eminente filósofa de Harvard, Hilary Putnam llegó a escribir tan recientemente como en 2004 que la ontología era “un cadáver apestoso” que necesitaba un entierro urgente.

Pero seguramente, si Galileo Galilei tenía razón al afirmar, como lo hizo en su The Assayer, que el libro de la naturaleza está escrito en el lenguaje de las matemáticas, hay otros libros sobre otras realidades y sobre la experiencia humana que no están escritos en ese lenguaje. . (Eugene Wigner demostró brillantemente que no tenía razón en 1959, pero esa es otra historia)^[Wigner (1960, 1-14).]. Entonces, ¿cuál es la naturaleza de la realidad económica y en qué se diferencia de los objetos naturales?

## Los objetos de la naturaleza y los objetos del pensamiento {-}

Los objetos de la naturaleza existen independientemente de cualquier teoría o hipótesis sobre ellos. Sus propiedades no se ven afectadas por ningún pensamiento o acción humana. Es esta característica de los objetos naturales - su independencia e indiferencia hacia cualquier teoría sobre ellos - lo que hace posible formular teorías verificables sobre ellos. Las sustancias existen independientemente de lo que hagamos con ellas, y su transformación en diversas circunstancias es la consecuencia de que sus propiedades interactúan con las propiedades de otros objetos naturales en lugar de la atribución humana de tales propiedades. Su naturaleza no puede cambiarse mediante regulación o persuasión. Son insensibles a los incentivos. Es un requisito fundamental para la validez de cualquier teoría científica que el objeto de la teoría esté separado de la teoría sobre ella. Los experimentos científicos son repetibles precisamente porque las propiedades del objeto del experimento son constantes y, además, son universales. Las valencias de los elementos de la tabla de Mendeleev son las mismas en Dinamarca, Argentina o Filipinas.

En marcado contraste, los objetos de la actividad económica son objetos de pensamiento. Son la mente, o como Russell dice, dependientes de la representación^[Russell (1919)], creado a través de la intencionalidad colectiva. Aunque los objetos del pensamiento pueden resultar en la producción, distribución y consumo de objetos corporales tangibles, el objeto del pensamiento económico en sí mismo es incorpóreo. Un "mercado" puede ser un espacio físico, pero el aspecto económicamente significativo de un mercado no es su configuración física, ni sus propiedades físicas, sino, más bien, las propiedades de las actividades que se desarrollan en él. Las propiedades económicamente significativas de los objetos físicos no son sus propiedades físicas, sino los términos y condiciones para su propiedad, intercambio y las condiciones para la determinación de su valor. Estos intangibles no sonpropiedades de los objetos mismos, sino más bien son las condiciones sociales generalmente aceptadas para su creación, propiedad, uso y consumo. Los objetos económicos nacen como fruto del pensamiento humano relacionado tanto con su concepción como objetos como con la organización social que permite su creación y sustento. Estos objetos son hechos sociales, encarnaciones de la intencionalidad colectiva, que surgen de un ethos colectivo y nacen a través del lenguaje, reflejando el pensamiento que les da origen. Debido a que son producto de la intención humana, son inherentemente subjetivos y reflejan la intención de quienes los crean. Así, 'dinero', una hoja de papel con un tamaño específico, el diseño y la impresión del color están dotados de propiedades y funciones específicas por la intencionalidad colectiva con la que está constituido y con el que se redefine continuamente. La hoja de papel es un objeto objetivo o corpóreo, pero su significado y función no están en función de su ser físico. De hecho, el dinero ya no necesita tener ninguna forma física.

## ¿Qué es la intencionalidad? {-}

La intención, incluida la acción intencional, es una de las cuestiones más complejas de la filosofía, que involucra el problema mente / cuerpo, la causalidad, el conocimiento, la verdad, el razonamiento práctico, la ética y la ontología. Los eventos económicos, el complejo producto agregado de la intencionalidad, incluidas las intenciones opuestas o contradictorias, son el producto de la acción humana intencional.

El interés filosófico por la intencionalidad, desarrollado primero por los seguidores medievales de Aristóteles, sobre todo Santo Tomás de Aquino, fue olvidado en gran medida hasta que Brentano, Husserl y Meinong lo revivieron. La publicación de la Intención^[
Anscombe1957)] de GEM Anscombe combinó la tradición aristotélica-tomista con la filosofía analítica en lugar del empirismo de Brentano. Desde entonces, la filosofía de la intencionalidad se ha expandido enormemente, entre otros, por Peter Geach^[Geach (1967, 627–32)], John Searle^[Searle (1983)], Graham Priest^[Sacerdote (2005)] y Tim Crane^[Grua (2013)].

Una revisión de las muchas teorías y sutilezas de la intencionalidad está más allá del alcance de este artículo, y para nuestros propósitos, la definición más simple de la noción será suficiente. Es la capacidad de la mente para dirigirse a cualquier objeto, ya sea existente o no, ya sea un concepto o una cosa. Para los propósitos más limitados de este artículo, intencionalidad es el nombre de la constitución mental y la representación de los hábitos, creencias y reglas con las que los objetos están dotados de valor intercambiable, cómo ese valor se crea, conserva, disminuye e intercambia, en resumen, el famoso libro de Adam Smith. "propensión humana al camión, al trueque y al intercambio".

Mientras que los economistas modernos, como el premio Nobel N. Gregory Mankiw, creen que los economistas “abordan el tema de la economía de la misma manera que un físico aborda el estudio de la materia y un biólogo aborda el estudio de la vida ... (economistas) idear teorías, recopilar datos y analizar estos datos en un intento de verificar sus teorías "^[Mankiw2011)], Smith ve el meollo del asunto en" ofrecer un argumento para persuadir a uno de hacer esto y aquello "^[Herrero (1978)]. Estas dos concepciones de la economía no pueden estar más separadas. Según Mankiw, el tema se parece mucho a la materia, que alberga datos que deben recopilarse para la verificación de alguna generalización causal. Para Adam Smith se trata del argumento de persuadir, dada nuestra propensión a los camiones, el trueque y el intercambio. Mankiw cree que los objetos económicos tienen una existencia objetiva e independiente. Smith, por el contrario, cree que existen solo en virtud de las propensiones humanas, que la economía no es una colección de objetos sino una serie de propensiones humanas.

Una especificación adicional es que la intencionalidad en juego en la economía es colectiva. Las intenciones del agente individual operan en el contexto de una intencionalidad colectiva, socialmente construida y socialmente legitimada. No hay eventos económicos dentro del dominio de una sola persona. Mientras que el protagonista de la economía moderna es la utilidad que maximiza el homo oeconomicus con un solo motivo para sus acciones y la prerrogativa exclusiva de determinar sus utilidades, de hecho, las utilidades son construcciones sociales y también lo son las reglas con las que se puede elegir entre las utilidades disponibles.

Los objetos intencionales de la actividad económica humana, las propensiones de Smith, son incorpóreos, lo que vuelve problemáticas las técnicas habituales de abstracción e idealización empleadas habitualmente en las ciencias naturales. La eliminación de las "causas perturbadoras", para usar la famosa frase de Mill, deja después de la eliminación un objeto corporalmente identificable con propiedades verificables. Pero en el caso de los objetos incorpóreos esto no es posible. La conceptualización de la experiencia puede producir una metáfora o un icono útil para la suma de esa experiencia, pero no es su destilación mediante la eliminación de componentes eliminables porque dichos componentes son en sí mismos abstracciones. Una curva de demanda es una representación visual efectiva de la abstracción llamada demanda, pero no es la suma y no puede ser la suma de datos empíricos. Como señaló Nicholas Kaldor, el enemigo que derrota al resumen exitoso es el tiempo. La demanda de un bien toma forma con el tiempo, pero durante el mismo período otros factores relevantes, como la disponibilidad de bienes sustitutos, un cambio en las tasas de interés o el nivel de confianza, el funcionamiento de la política monetaria, etc. la demanda tiene lugar y la curva de demanda no puede dar cuenta de tales cambios. Los economistas abordan este problema con la ayuda deceteris paribus , pero la presunción de que todo lo demás permanece constante es sólo eso, una presunción arbitraria. La intuición de que existe una relación de algún tipo entre precios y cantidades es sin duda una generalización útil, pero no tiene el tipo de valor de verdad que conlleva una ley típica de la física o cualquier rama de las ciencias naturales.

## ¿Es esto solo una cuestión de complejidad? {-}

Con frecuencia se afirma que la diferencia entre los hechos de la naturaleza y los hechos sociales es de cantidad más que de calidad. Los hechos que conducen a la formación de precios, según este punto de vista, son cualitativamente los mismos que los que producen la fisión nuclear. La diferencia es solo que hay más de ellos. Los hechos sociales involucran mayores complejidades porque son la combinación de un número mucho mayor de componentes que los hechos de la naturaleza. Pero esta afirmación se confunde por dos razones bastante fundamentales. Primero, los hechos sociales son hechos intencionales, que dependen de la intencionalidad humana, mientras que los hechos naturales no contienen intencionalidad alguna. En segundo lugar, los hechos sociales operan en un mundo abierto donde los nuevos hechos vienen y los viejos se van sin que exista ningún principio que regule el ir y venir, en contraste con los hechos naturales donde el contexto, como en un experimento de laboratorio, se puede determinar. La diferencia entre los hechos que surgen a través del acuerdo y la costumbre humanos y los hechos que son totalmente independientes de nosotros es bastante básica para la ciencia. Es la condición previa para la separación de la teoría verificable experimentalmente de su objeto. Si la teoría monetaria se refiriera a las propiedades del papel que sirve como billete de diez libras, no tendría ninguna dificultad en parecerse a las ciencias naturales. Pero no se trata de ese papel. La teoría monetaria tiene como objetivo Si la teoría monetaria se refiriera a las propiedades del papel que sirve como billete de diez libras, no tendría ninguna dificultad en parecerse a las ciencias naturales. Pero no se trata de ese papel. La teoría monetaria tiene como objetivo Si la teoría monetaria se refiriera a las propiedades del papel que sirve como billete de diez libras, no tendría ninguna dificultad en parecerse a las ciencias naturales. Pero no se trata de ese papel. La teoría monetaria tiene como objetivofunciones, propósitos, efectos y respuestas en el comportamiento individual y colectivo que asignamos colectivamente al billete de diez libras junto con las reglas, los términos y condiciones que postulamos explícita e implícitamente que hacen que el billete sea operativo. Esa incesante variación en el valor de ese billete de diez libras es consecuencia de la subjetividad ontológica del objeto intencional colectivo que llamamos dinero. Como lo dijo Adam Smith, el valor de ese billete de diez libras es una cuestión de persuasión, una cuestión de cómo, a través de ese diálogo entre el comprador y el vendedor y la interacción incesante dentro de la sociedad en general, se llega a un acuerdo, cómo se llega a un acuerdo de que el el billete vale más o menos o casi lo mismo que el objeto por el que se intercambia.

## ¿Existen los objetos económicos? {-}

Uno de los temas más debatidos en la filosofía de la intencionalidad es si el objeto del pensamiento debe existir, de hecho, para ser objeto de la intencionalidad. La visión materialista responde a la pregunta afirmativamente, afirmando que la existencia de objetos imaginados es un tipo de existencia completamente diferente de la existencia real. Otros, como Tim Crane, sostienen que, dado que los objetos inexistentes pueden tener propiedades específicas, pueden ser objetos de intencionalidad. Si es la realidad la que fundamenta la verdad de una afirmación y si la realidad no contiene más de lo que existe, la cuestión de qué objetos existen se vuelve bastante importante. Si los objetos económicos existen en el mismo sentido que las moléculas, el determinismo de la economía moderna está bien fundado. Los economistas pueden entonces afirmar que están haciendo descubrimientos sobre el mundo como cualquier científico natural. Pero si los objetos económicos no existen, no hay nada que pueda descubrirse sobre ellos y la pretensión de ciencia se derrumba. Los objetos inexistentes no tienen leyes de la naturaleza y no pueden tener poderes causales porque los poderes causales requieren ubicaciones espacio-temporales, algo que los objetos inexistentes no tienen.

La inexistencia de objetos económicos, su falta de objetividad ontológica, no excluye, sin embargo, la posibilidad de construir objetos con una ontología subjetiva. Sherlock Holmes, Pegasus y el planeta Vulcano son todos objetos inexistentes y, sin embargo, es posible hacer declaraciones verdaderas y falsas sobre ellos. Es cierto, por ejemplo, que Sherlock Holmes era detective, y no es cierto que fuera instructor de aeróbic. Es cierto que Pegasus tiene dos alas, pero no es cierto que ganó el Derby de Kentucky, etc. De la misma manera, las curvas de demanda, los 'mercados' o las 'propensiones marginales no son más fáciles de ubicar en el mundo real que Sherlock Holmes, pero Es muy posible hacer declaraciones verdaderas o falsas sobre ellos. La curva de demanda es una línea en un libro de texto cuya forma no es propiedad de ningún objeto, sino más bien, la representación visual de una colección de características generalizadas de la relación entre precios y cantidades. Un mercado puede ser un lugar - y por lo tanto un objeto real - pero no necesita serlo para poseer características de los procesos que tienen lugar en mercados reales. El problema al que se enfrenta la economía se ve agravado por el hecho de que, mientras que los tres objetos inexistentes mencionados anteriormente son corporales, esta forma de corporeidad ficticia no suele estar disponible para los objetos económicos. Esa corporeidad se vuelve importante cuando las afirmaciones de verdad sobre Sherlock Holmes pueden tener valor de verdad si son consistentes con los axiomas postulados sobre él. La afirmación de que puede volar no satisfará esta condición. Pegasus, por otro lado, puede volar, pero no puede fumar en pipa, conversar con Watson o resolver un crimen. Por lo tanto, la cuestión para la economía es cómo determinar el valor de verdad de las afirmaciones sobre objetos intencionales inexistentes donde el objeto sería ontológicamente objetivo si existiera, pero donde el objeto no solo no existe, sino que ni siquiera tiene corporeidad ficticia. La respuesta corta es que no se puede hacer de acuerdo con los requisitos de valor de verdad en las ciencias naturales porqueEl valor de verdad en las ciencias naturales es una función de la confirmación experimental, mientras que el valor de verdad de los objetos inexistentes es una cuestión de coherencia con los supuestos y postulados. (Una ilustración concreta se dará a continuación en la discusión de Walras).

La incertidumbre acerca de la objetividad ontológica de la entidad en estudio conduce a una falla en la delimitación de la distinción entre teoría y su tema. Este fracaso priva a la teoría de su estatus científico y conduce al tipo de circularidad señalada por Joan Robinson: “La utilidad es un concepto metafísico de circularidad inexpugnable; La utilidad es la calidad de los productos básicos que hace que los individuos quieran comprarlos, pero el hecho de que los individuos quieran comprarlos demuestra que tienen utilidad . "^[Robinson1962)] Una comparación de la definición de química establecida por Robert Findlay Henry con las dos propuestas por Adam Smith y Mankiw citadas anteriormente reforzará este punto. Según Henry, "la química intenta comprender las transformaciones entre sustancias"^[Hendry2008)]. Si seguimos a Adam Smith al intentar formular una definición similar de economía y afirmamos que "la economía intenta comprender la naturaleza y las causas de la riqueza de las naciones", surge la pregunta de si 'sustancias' son lo mismo que 'riqueza', y si las "transformaciones" plantean un desafío análogo a la "naturaleza y causas" de Smith y si el tipo de comprensión planteada por Hendry es la clase de comprensión que se puede tener de la riqueza.

Las sustancias existen independientemente de lo que hagamos con ellas, de la utilidad que aprehendamos en ellas, y su transformación en diversas circunstancias tiene lugar con bastante independencia de la acción humana. Pero la riqueza, la utilidad, el equilibrio, la inflación, etc., se construyen socialmente - son "hechos sociales"^[Gilbert (1989)]  - sujetos a una reconstitución significativa y más o menos continua. Los hechos sociales no pueden separarse de la teoría o las reglas bajo las cuales se formulan.

La dificultad de separar el sujeto de la teoría cuando el sujeto no tiene una ontología independiente también es evidente en la famosa definición de Lionel Robbins: "La economía es la ciencia que estudia el comportamiento humano como una relación entre fines y medios escasos que tienen usos alternativos"^[Robbins1932). En una versión posterior, la desconcertante frase "comportamiento como relación" fue reemplazada por la noción de "asignación".]. Pero los 'fines' y los 'medios escasos' son objetos inexistentes construidos socialmente y el 'comportamiento humano' que se estudia es una parte integral de esa construcción social. Es el comportamiento humano el que construye tanto el fin como la escasez, y son los fines y la escasez lo que construye el comportamiento humano. Volvemos a la “circularidad inexpugnable” de Joan Robinson.

Los objetos físicos, como los elementos del químico, no tienen un propósito, un fin, un telos . La finalidad con la que se les puede dotar, el uso que se les da no es propiedad de estos elementos. El famoso problema no resuelto de Aristóteles de la inconmensurabilidad del valor de uso y el valor de cambio —como de hecho el problema constante de la inconmensurabilidad en economía— no puede resolverse si buscamos un "valor" que sea común a ambos^[Meikle1955)]. Sus camas y zapatos no tienen valor de uso ni de cambio. Dichos valores se atribuyen a estos objetos por la intencionalidad del intercambiador o usuario. Considerando que la valencia de un elemento químico es una propiedadde ese elemento, los valores de cambio y uso son atribuciones que dependen de la intención del agente. El valor está en la intencionalidad en contraposición a la valencia que está en el objeto. Keynes era muy consciente del problema, pero no sabía muy bien qué hacer al respecto. En una carta a Roy Harrod, escribió:

> En química, física y otras ciencias naturales, el objeto del experimento es completar los valores reales de las diversas cantidades y factores que aparecen en una ecuación o una fórmula; y el trabajo cuando esté hecho es de una vez por todas. En economía ese no es el caso, y convertir un modelo en una fórmula cuantitativa es destruir su utilidad como instrumento de pensamiento ... También quiero enfatizar fuertemente el punto de que la economía es una ciencia moral. Mencioné antes que se trata de introspección y valores. Podría haber agregado que se trata de motivos, expectativas, incertidumbres psicológicas. Hay que estar constantemente en guardia para no tratar el material como constante y homogéneo, así como el material de las otras ciencias, a pesar de su complejidad, es constante y homogéneo^[Carta a Roy Harrod, del 10 de julio de 1938 (fechada incorrectamente el 16 de julio) en Collected Letters of John Maynard Keynes Vol XlX, 299-301.].

Aunque Keynes se acerca mucho a reconocer la intencionalidad como la diferencia ontológicamente decisiva entre las ciencias morales y las naturales, no resuelve el dilema implícito en la economía moderna^[Para ser justos con Keynes, escribió esta carta durante los días gloriosos del positivismo lógico, cuando la ontología era vista como la rama de la filosofía completamente de mala reputación. Es una señal de su genio que nadaba contra esta corriente.].: son objetos económicos como la manzana de Newton que arrojan datos con los que se pueden completar los valores reales de las diversas cantidades y factores en una ecuación o una fórmula, o es la idea de un objeto inexistente cargado de valores, introspección, motivos y expectativas. totalmente absurdo? Si las manzanas no se pueden combinar con motivos, expectativas e incertidumbres psicológicas, pero la economía debe, no obstante, lidiar con ellas, ¿deben desecharse las manzanas o hay una manera de tener sus manzanas y no tenerlas al fingir que lo que usted tiene no es un problema? manzana, pero como una? Esta, por supuesto, es la ruta propuesta por Adam Smith y los economistas clásicos, incluido Marx, cuando atribuyen un carácter abstracto al trabajo para llegar a una explicación de cómo diferentes e inconmensurables tipos de trabajo pueden, no obstante, tener el tipo de homogeneidad con la que se puede unir una teoría del intercambio. Smith escribe:

> También la mayor parte de la gente comprende mejor lo que se entiende por cantidad de una mercancía particular que por cantidad de trabajo. Uno es un objeto simple y palpable; el otro, una noción abstracta que, aunque puede hacerse suficientemente inteligible, no es del todo tan natural y obvia.

Al ver la diferencia entre la cantidad de mercancías y una cantidad (inexistente) de trabajo como una cuestión de grado de naturalidad u obviedad, Smith pasa por alto la diferencia ontológica fundamental.

La noción de Mill de que hay objetos parecidos a manzanas que se pueden entender si se separan de las "causas perturbadoras" persigue el razonamiento de Keynes. Por un lado, en esta misma carta lo considera "más importante ... investigar estadísticamente el orden de magnitud del Multiplicador" como si el Multiplicador fuera un objeto parecido a una manzana, pero por el otro, ve que el " El material ”de la economía, a diferencia del de las ciencias naturales, no es“ ni constante ni homogéneo ”. ¿Es el Multiplicador entonces una manzana, o es uno de esos materiales que, por estar infectado con motivos, no es constante ni homogéneo? ¿O no es ninguno de los dos? ¿Qué debería hacer uno? Alcanzar la homogeneidad con el dispositivo de Mill de eliminar como "causa perturbadora" cualquier cosa que obstruya la homogeneidad y la constancia o admitir que la inconstancia y heterogeneidad del "material" lo hace inadecuado para el tratamiento científico. Keynes parpadea.

Habiendo postulado como objetivo singular el logro del estatus científico, gran parte de la economía moderna se ha centrado en las posibles formas de superar este dilema. El camino fue trazado por primera vez de manera sistemática por Léon Walras y, en su mayor parte, sigue siendo el paradigma básico de la economía. Walras ofrece su definición básica de "economía pura" en el Prefacio a la cuarta y definitiva edición de sus Elementos de economía pura^[Walras1954)] con engañosa claridad: " La economía pura es, en esencia, la teoría de la determinación de precios bajo un régimen hipotético de competencia perfectamente libre ". Tenga en cuenta que, a diferencia de Hendry, que está interesado en comprender la realidadtransformación de sustancias, Walras quiere construir una teoría sobre la determinación de precios en circunstancias hipotéticas. Con esta simple afirmación, Walras deja en claro que el tema de la teoría económica, por así decir su manzana, la determinación de los precios, es un objeto imaginado que sólo existe bajo un régimen hipotético inexistente. Y, sin embargo, él y sus sucesores creen que se puede hacer ciencia sin la manzana.

En un pasaje de enorme importancia para el desarrollo de la teoría económica moderna, anticipando tanto a Milton Friedman como a Paul Samuelson, expone su afirmación con gran claridad.

> ...Las ciencias físico-matemáticas, como las ciencias matemáticas en sentido estricto, van más allá de la experiencia tan pronto como han extraído sus conceptos tipo de ella. A partir de conceptos de tipo real, estas ciencias abstraen conceptos de tipo ideal que definen, y sobre la base de estas definiciones construyen a prioritodo el marco de sus teoremas y demostraciones ... la teoría pura de la economía debería tomar el relevo de la experiencia de ciertos conceptos de tipo, como los de intercambio, oferta, demanda, mercado, capital, renta, servicios productivos y productos. A partir de estos conceptos de tipo real, la ciencia económica pura debería abstraer y definir conceptos de tipo ideal en términos de los cuales lleva a cabo su razonamiento. El regreso a la realidad no debe tener lugar hasta que se complete la ciencia y solo con vistas a aplicaciones prácticas. Por lo tanto, en un mercado ideal tenemos precios ideales que están en relación exacta con una oferta y demanda ideales.

Sorprendentemente, agrega unas líneas más tarde: "después de eso, ellos (los científicos) vuelven a la experiencia no para confirmar, sino para aplicar sus conclusiones". (Énfasis agregado.) Concluye su declaración triunfal con el destronamiento de Ricardo y Mill y la coronación de las matemáticas:

> En cuanto al lenguaje matemático, ¿por qué deberíamos persistir en utilizar el lenguaje cotidiano para explicar las cosas de la manera más engorrosa e incorrecta, como ha hecho a menudo Ricardo y como lo hace repetidamente John Stuart Mill en sus Principios de economía política , cuando estas mismas cosas se pueden afirmar? mucho más sucinta, precisa y clara en el lenguaje de las matemáticas?

El a prioriEl marco de la teoría económica es, desde este punto de vista, el producto de dos abstracciones. La primera abstracción produce conceptos de "tipo real" a partir de la experiencia, seguida de una segunda abstracción, que produce conceptos de "tipo ideal". Aunque Walras no especifica qué puede implicar cada uno de estos pasos, parece razonable suponer del texto que el primero de estos pasos implica algún tipo de aislamiento y / o reducción, algo comparable a la eliminación de las causas perturbadoras de Mill, mientras que el segundo ordinariamente se llama idealización. Ambas operaciones encuentran serias dificultades cuando se realizan sobre objetos de pensamiento. Además, Walras, como de hecho todos sus sucesores, nos dejan sin una explicación de cómo podría validarse la representación del concepto de tipo ideal mediante números o símbolos. Cuando sustituimos esa C por un número, representando capital en una ecuación, ¿qué es exactamente ese capital y en qué sentido ese número comprende esa C? La propiedad principal, a menudo la única, conocida del concepto de tipo ideal es que tiene una relación expresada matemáticamente con otra cosa. A menos que tomemos como axioma el punto de vista propuesto por Russell o Ryle de que solo existen cosas cuantificables, de alguna manera debemos dar cuenta de la intencionalidad. ¿Los números o símbolos con los que se representa el tipo ideal ya están incrustados en la experiencia, o se materializan de la nada en el curso de la abstracción como el tipo real y luego emergen los conceptos del tipo ideal? y ¿en qué sentido ese número comprende esa C? La propiedad principal, a menudo la única, conocida del concepto de tipo ideal es que tiene una relación expresada matemáticamente con otra cosa. A menos que tomemos como axioma el punto de vista propuesto por Russell o Ryle de que solo existen cosas cuantificables, de alguna manera debemos dar cuenta de la intencionalidad. ¿Los números o símbolos con los que se representa el tipo ideal ya están incrustados en la experiencia, o se materializan de la nada en el curso de la abstracción como el tipo real y luego emergen los conceptos del tipo ideal? y ¿en qué sentido ese número comprende esa C? La propiedad principal, a menudo la única, conocida del concepto de tipo ideal es que tiene una relación expresada matemáticamente con otra cosa. A menos que tomemos como axioma el punto de vista propuesto por Russell o Ryle de que solo existen cosas cuantificables, de alguna manera debemos dar cuenta de la intencionalidad. ¿Los números o símbolos con los que se representa el tipo ideal ya están incrustados en la experiencia, o se materializan de la nada en el curso de la abstracción como el tipo real y luego emergen los conceptos del tipo ideal?

Se podría continuar con una explicación de las otras grandes figuras de las ciencias sociales, como Max Weber, John Stuart Mill o Carl Menger, pero el denominador común es obvio: la metodología de las ciencias sociales pretende crear un objeto ontológicamente objetivo, pero el objeto con el que termina no es un objeto adecuado para un tratamiento científico. Al mismo tiempo, a pesar de su inadecuación para la ciencia, estos objetos sustitutos, como alegorías, metáforas y símiles, pueden revelar con gran poder alguna verdad sobre una realidad compleja y confusa. No esrelación entre oferta y demanda, entre precios y cantidades, y las dos curvas de Alfred Marshall revelan algo importante sobre esa relación. Pero la formación de precios en el mundo real es mucho más compleja y elusiva y, lo que es más importante, depende mucho más de la interacción de un número indeterminado de factores de lo que permiten las curvas de Marshall. Es perfectamente razonable construir modelos idealizados con la esperanza de obtener algo de conocimiento, pero es un gran error pretender que el tema de la economía puede ser análogo al de las ciencias naturales. A diferencia de este último, en las famosas palabras de Thomas Hobbes, está "hecho con palabras".

Quizás la consecuencia más importante de esta visión de la economía es que el juicio moral es una parte inextricable de su tema, que la construcción de modelos e hipótesis sin tener en cuenta ese juicio moral no conduce a la comprensión de algún tipo de realidad natural que opera de acuerdo con las leyes de la naturaleza, sino, más bien, a una ideología que se exhibe como ciencia para ser aún más convincente.