# Ética de la investigación en economía: ¿qué pasa si los economistas y sus asignaturas no son racionales? {#Capitulo_17}

```{r, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "html", results='asis', echo=FALSE}
cat('<hr style="background-color:#03193b;height:2px">')
```

Los economistas y sus sujetos no siempre son racionales. El problema es tan significativo que la economía no puede satisfacer el criterio principal para la ciencia que varios filósofos de la ciencia han formulado desde los positivistas lógicos en el Círculo de Viena en la década de 1920: para que un teorema sea significativo, debe ser confirmado. por los hechos del mundo. La creciente frecuencia de teorías no verificadas e invalidadas en economía sugiere que la economía sufre las consecuencias de una práctica de investigación cuestionable en los procesos de producción de conocimiento científico: la práctica de negarse a rechazar teorías invalidadas por pruebas contundentes y contraargumentos.

## Introducción {-}

> En respuesta a la observación de que los choques son imaginarios, una defensa estándar invoca a Milton Friedman (1953) afirmación metodológica de una autoridad anónima de que "cuanto más significativa es la teoría, menos realistas son los supuestos". Más recientemente, "todos los modelos son falsos" parece haberse convertido en la onda de mano universal para descartar cualquier hecho que no se ajuste a un modelo favorito. La relación evasiva con la verdad revelada por estas evasiones metodológicas y el rechazo "menos que totalmente convencido ..." de los hechos va más allá de la ironía posmoderna que merece su propia etiqueta. Sugiero "post-real". Romer (2016a)

En un artículo muy conocido, Thomas Herndon et al. (2013a) replicó dos de los artículos de Reinhart y Rogoff (2010a, B). En sus artículos, Reinhart y Rogoff argumentaron que “las tasas de crecimiento medianas de los países con una deuda pública superior al 90% del PIB son aproximadamente un 1% más bajas que en otros países; las tasas de crecimiento promedio (promedio) son varios por ciento más bajas ". Herndon, Ash y Pollin encontraron que los trabajos de Reinhart y Rogoff presentaban errores de codificación (especialmente cuando no había datos disponibles para algunos de los países europeos), exclusión de datos (de Australia, Austria, Bélgica, Canadá y Dinamarca) y estadísticas resumidas no convencionales. Afirmaron que “la exclusión selectiva de los datos disponibles, los errores de codificación y la ponderación inadecuada de las estadísticas resumidas conducen a graves errores de cálculo que representan de manera inexacta la relación entre la deuda pública y el crecimiento del PIB entre economías avanzadas^[Romer (1990).] ... cuando se calculan correctamente, La tasa media de crecimiento del PIB real de los países que tienen una relación deuda pública / PIB superior al 90% es en realidad del 2,2%, no del −0,1% como se publica en Reinhart y Rogoff. Es decir, contrariamente a [Reinhart y Rogoff], el crecimiento medio del PIB con una relación deuda pública / PIB superior al 90% no es dramáticamente diferente que cuando la relación deuda / PIB es más baja ". Las políticas de austeridad, concluyeron, eran innecesarias. Los artículos de Reinhart y Rogoff han sido dos de los artículos a los que se hace referencia con frecuencia por quienes abogaron por los planes de austeridad en Europa y Estados Unidos después de la crisis financiera de 2008. En otras palabras, las propuestas sobre la necesidad de planes de austeridad se basaron en un documento lleno de errores y errores de cálculo. Reinhart y Rogoff ( el crecimiento medio del PIB con una relación deuda pública / PIB superior al 90% no es dramáticamente diferente que cuando la relación deuda / PIB es más baja ". Las políticas de austeridad, concluyeron, eran innecesarias. Los artículos de Reinhart y Rogoff han sido dos de los artículos a los que se hace referencia con frecuencia por quienes abogaron por los planes de austeridad en Europa y Estados Unidos después de la crisis financiera de 2008. En otras palabras, las propuestas sobre la necesidad de planes de austeridad se basaron en un documento lleno de errores y errores de cálculo. Reinhart y Rogoff ( el crecimiento medio del PIB con una relación deuda pública / PIB superior al 90% no es dramáticamente diferente que cuando la relación deuda / PIB es más baja ". Las políticas de austeridad, concluyeron, eran innecesarias. Los artículos de Reinhart y Rogoff han sido dos de los artículos a los que se hace referencia con frecuencia por quienes abogaron por los planes de austeridad en Europa y Estados Unidos después de la crisis financiera de 2008. En otras palabras, las propuestas sobre la necesidad de planes de austeridad se basaron en un documento lleno de errores y errores de cálculo. Reinhart y Rogoff ( las propuestas sobre la necesidad de planes de austeridad se basaron en un documento lleno de errores y errores de cálculo. Reinhart y Rogoff ( las propuestas sobre la necesidad de planes de austeridad se basaron en un documento lleno de errores y errores de cálculo. Reinhart y Rogoff (2013) respondieron a sus críticos en un artículo periodístico y aceptaron que sus trabajos incluían errores. Sin embargo, los artículos no se retiraron del American Economic Review ni del National Bureau of Economic Research Working Papers . Los editores de American Economic Review rechazaron su trabajo^[Correspondencia personal con Thomas Herndon (septiembre de 2018). Véase también el editorial de Jakob Kapeller en Heterodox Economics Newsletter, 3 de marzo de 2014.]. Herndon y col. (2013b) publicaron su artículo en el Cambridge Journal of Economics en 2013.

## Primum Non Nocere {-}

Los científicos pueden causar daño de muchas formas^[El plagio, la falsificación de (datos) y la fabricación (o fabricación) de (datos) se han considerado las formas más comunes y significativas de investigación mal realizadas por las autoridades de integridad de la investigación en todo el mundo, incluida la Oficina de Integridad de la Investigación (EE. UU.), La Institutos Nacionales de Salud (Reino Unido) y ALLEA: todas las universidades europeas (UE).]. Plagian^[Consulte la página de plagio de RePEc disponible en línea en https://plagiarism.repec.org [Consultado en marzo de 2019]. Véase también Enders y Hoover (2004) y Karabag y Berggren (2012).]. También fabrican y falsifican datos (Fanelli2009). Si cree que esto es todo lo que un economista necesita saber sobre los daños en la ciencia, es posible que esté muy equivocado (Necker2014). Los documentos de trabajo publicados en los sitios web de Replication Network^[Red de replicación: https://replicationnetwork.com ; [Consultado en marzo de 2019].] y Replication Wiki^[Wiki de replicación: http://replication.uni-goettingen.de/wiki/index.php/Main_Page [Consultado en marzo de 2019].] han demostrado que los autores de un número significativo de artículos en economía no han revelado sus datos y códigos informáticos para que investigadores independientes prueben el modelo del artículo original. Los artículos presentados en conferencias^[Véase, por ejemplo, el “Taller internacional sobre mala conducta científica y ética de la investigación en economía” (organizado por la Asociación de Economía Social y la Universidad de Ankara, celebrado en Izmir, Turquía, agosto de 2014), “Replicación en microeconomía”, “Metaanálisis de reproducibilidad en Economics Research ”y“ Replication and Ethics in Economics: Treinta años después de Dewald, Thursday y Anderson ”(organizado por la American Economic Association, celebrado en Chicago, IL, enero de 2017), y muchos otros eventos organizados por la Association for Integrity y liderazgo responsable en economía y disciplinas asociadas. Consulte el sitio web de AIRLEAP en http://www.airleap.org [Consultado en octubre de 2018].] y números especiales de revistas de economía^[Véase, por ejemplo, Review of Social Economy , número especial sobre "Conducta científica indebida y ética de la investigación en economía" (2016). Véanse también las convocatorias de artículos de Energy Economics y el Journal of Economic Psychology que publicarán números especiales sobre estudios de replicación en 2018 o posteriormente.] informan que una parte significativa de los trabajos publicados anteriormente que son replicables no se pueden verificar o están invalidados. Los blogs publicados por Retraction Watch^[Retraction Watch: https://retractionwatch.com/category/by-subject/economics/ [Consultado en octubre de 2018].] sugieren que los economistas han seguido citando los artículos que fueron retirados por las revistas en las que se publicaron los artículos.

El número de artículos académicos y libros sobre ética de la investigación en economía crece continuamente. Desde la década de 1990, los metodólogos económicos como Deirdre N. McCloskey, Arjo Klamer, Stephen T. Ziliak, James R. Wible y George F. DeMartino, entre otros, han expresado su preocupación por un problema persistente en la economía aplicada. Argumentaron que la profesión económica ha ignorado "los desafíos éticos que acompañan a la influencia de la profesión sobre la vida de los demás"^[DeMartino y McCloskey (2015).]. Los metodólogos económicos también han afirmado que las cuestiones relacionadas con la integridad científica en la economía se han convertido en una cuestión urgente desde la crisis financiera de 2008^[DeMartino (2011a, B), Dow (2013).]. Los fundamentos de la ciencia económica se ven ahora seriamente desafiados por las consecuencias acumulativas de una ausencia general de rendición de cuentas y responsabilidad en la investigación económica. Un creciente interés entre los economistas por la integridad de la investigación en economía sugiere que la ética de la investigación pronto será el próximo giro en la metodología económica donde se discutirán y analizarán las consecuencias de prácticas de investigación cuestionables^[Wible2016), Yalcintas y Wible (2016).].

Nuestro objetivo principal en este documento es presentar y desarrollar este nuevo enfoque. Pensamos que las teorías que no pueden ser verificadas y validadas por datos empíricos deben ser abandonadas (Yalcintas2016). Los economistas que no abandonan las teorías no verificadas e invalidadas dan lugar a un problema ético en la profesión. Los economistas que no abandonan las teorías cuando las teorías no están verificadas o invalidadas por hechos empíricos no se comportan de acuerdo con los "estándares de honestidad intelectual", como Imre Lakatos (1970) una vez que lo puso. Sin embargo, como muestra el caso de Reinhart y Rogoff, los economistas se mantienen firmes cuando son desafiados por pruebas contrarias y argumentaciones que refutan.

Afirmamos que la economía debería ser parte de un sistema de ética de la investigación^[Véase Kapp (1963, 3-4), quien fue uno de los primeros economistas que propuso este argumento.]. La ética de la investigación es un campo de estudio en el que los académicos examinan las consecuencias dañinas de los investigadores que participan en prácticas de investigación cuestionables. Como David B. Resnik (2015) sostiene que “[m] todas las diferentes disciplinas, instituciones y profesiones tienen normas de comportamiento que se adaptan a sus objetivos y metas particulares. Estas normas también ayudan a los miembros de la disciplina a coordinar sus acciones o actividades y a establecer la confianza del público en la disciplina ”. En ausencia de normas académicas, los investigadores interesados ​​en sí mismos no siempre hacen crecer el bienestar epistémico de otros académicos. Las normas académicas incluyen responsabilidad, rendición de cuentas, respeto, confiabilidad y otras virtudes científicas que conducen a un proceso sostenible de producción de conocimiento. Un proceso sostenible en la ciencia equivale a corregir errores en primer lugar. Sin embargo, la autocorrección no está integrada de forma natural en las prácticas académicas. Para corregir los errores, la comunidad académica no solo necesita poder criticar las obras de otros. Entre otras cosas, los académicos también deberían poder abandonar las teorías que son invalidadas por la evidencia contraria y la argumentación refutada.

En las ciencias médicas, donde hay varios institutos profesionales que investigan sobre prácticas de investigación cuestionables, los investigadores reciben una formación exhaustiva antes de participar en nuevos proyectos. Las prestigiosas revistas médicas también publican artículos sobre ética de la investigación. Los economistas se han inspirado en los científicos biomédicos de muchas formas. Sin embargo, la investigación sobre prácticas de investigación cuestionables en economía no ha sido común. Desde el siglo XVIII, los economistas han imitado las formas en que los físicos llevaron a cabo la investigación científica. Los economistas también han copiado y reproducido varios tipos de prácticas de investigación en ciencias biomédicas. Desde el Dr. Quesnay que publicó su Tableau Économiqueen 1758, un libro en el que la invención de la circulación sanguínea de William Harvey jugó un papel importante, economistas como William Petty, John Locke, Joseph Clément Juglar, entre muchos otros, han sido entrenados o fuertemente influenciados por las ciencias médicas^[Groenewegen (2001), Clément (2003).]. Hoy, la biomedicina está en proceso de convertirse en un paradigma dominante en economía. Los economistas utilizan metáforas que extraen de las ciencias médicas, como crisis económicas, activos tóxicos, programas de recuperación, economías saludables y recetas económicas escritas por el FMI y el Banco Mundial. Más importante aún, las formas en que los economistas llevan a cabo la investigación se asemejan a las formas en que los científicos biomédicos llevan a cabo las suyas. Los economistas publican cada vez menos libros que artículos en los que un número cada vez mayor de ellos tienen varios autores en lugar de un solo autor. El número de citas al trabajo de un economista es tan importante como el argumento del trabajo. Dado que se ha vuelto más visible para el público en general desde la crisis financiera de 2008, Las cantidades de dinero para investigación otorgadas a los economistas y los salarios pagados a los economistas que forman parte de los consejos asesores de las grandes empresas de la industria bancaria en todo el mundo sin rendir cuentas al público son más o menos idénticos a los de los farmacólogos, investigadores del cáncer, etc. En otras palabras, los tipos de prácticas de investigación cuestionables en economía son similares a los tipos de las ciencias biomédicas, pero no hay ningún signo poderoso de preocupación entre los economistas por internalizar los efectos indirectos de las prácticas de investigación cuestionables. Afirmamos que Los tipos de prácticas de investigación cuestionables en economía son similares a los tipos de las ciencias biomédicas, pero no hay ningún signo poderoso de preocupación entre los economistas por internalizar los efectos indirectos de las prácticas de investigación cuestionables. Afirmamos que Los tipos de prácticas de investigación cuestionables en economía son similares a los tipos de las ciencias biomédicas, pero no hay ningún signo poderoso de preocupación entre los economistas por internalizar los efectos indirectos de las prácticas de investigación cuestionables. Afirmamos queprimum non nocere (“primero, no hacer daño”) no es solo uno de los principios que se les enseña a los estudiantes de medicina en las instituciones de salud. También debería ser una condición para que los economistas alcancen sus ideales. Vemos la moralidad como una condición imprescindible para la economía basada en hechos.

Por tanto, nos preguntamos: ¿qué pasa si los economistas y sus sujetos no son racionales? Mientras formulábamos la pregunta de investigación, nos inspiramos en una de las obras de Arjo Klamer, titulada “Como si los economistas y su tema fueran racionales” (1987), en la que argumentó que “[e] l objetivo real no es saber cómo… podemos diseñar criterios racionales de veracidad; en cambio, es para comprender cómo los economistas realmente discuten y cómo funciona su argumentación ". Afirma que la economía es un arte de persuasión y el supuesto de racionalidad es una metáfora en la que los economistas estudian su tema de investigación (es decir, los humanos) como si fueran racionales. La mayoría de nosotros diría que los humanos no sonsiempre racional. Klamer estaría de acuerdo. "Hablar basado en la pretensión de que todo el mundo es racional", dice Klamer, "puede que simplemente no sea tan interesante". Sin embargo, una de las consecuencias de no diseñar criterios racionales de veracidad es la pérdida de verificación y verificación de hechos. En su artículo, Klamer no confronta los resultados de un mundo libre de hechos. Es obvio que una economía post-hecho no es lo que pretendía Klamer cuando argumentó en contra de los criterios racionales de veracidad. Entonces, la pregunta de investigación pasa a ser la siguiente: ¿Cuáles son las consecuencias del comportamiento de los economistas que no son racionales?

Creemos que se han subestimado las consecuencias del hecho de que los economistas y sus sujetos no siempre sean racionales^[Necker2016), Aspiradora (2006).]. El problema es tan significativo que la economía no puede satisfacer el criterio principal para la ciencia y las teorías científicas que varios filósofos de la ciencia han formulado desde los positivistas lógicos en el Círculo de Viena en la década de 1920: para que un teorema sea significativo, tiene que ser confirmado por los hechos del mundo. Hoy en día, el positivismo lógico (o "verificacionismo", como a muchos filósofos de la ciencia les gustaría llamarlo) se "percibe casi universalmente como un villano", Wade Hands (2001, 72) argumenta, "un movimiento en falso que es responsable de gran parte de lo que está mal en casi todas las disciplinas intelectuales". Como resultado, solo un número limitado de metodólogos económicos^[Pabellón (1972), Hutchison (1984), Machlup (1955 y 1984).] ha estudiado la naturaleza y las consecuencias de la ausencia de verificación, una ideología que Karl Popper (1935/ 2002, 18) una vez pensado es "lógicamente inadmisible". No estamos de acuerdo. Argumentamos que la creciente frecuencia de teorías no verificadas e invalidadas en economía sugiere que la economía sufre las consecuencias de una práctica de investigación cuestionable en los procesos de producción de conocimiento científico: la práctica de negarse a rechazar teorías que son invalidadas por evidencia sólida y contraargumentos.

## Economía posterior a los hechos {-}

Ha pasado más de una década desde que la crisis financiera de 2008 golpeó la economía mundial. En la actualidad, existe una literatura económica cada vez mayor sobre la naturaleza y las consecuencias de la crisis. Una de las opiniones ampliamente aceptadas sobre la crisis ha sido que no fue solo una crisis de la economía global; también fue una crisis de la profesión económica^[Colander y col. (2009), Kirman (2010), Elliot (2010), Lawson (2009), Harvey (2012).]. Los economistas han jugado un papel en el surgimiento de la crisis.

Sin embargo, hemos descubierto que la ética de la investigación no se ha enseñado comúnmente en los departamentos de economía de todo el mundo desde entonces. El número de artículos publicados en la revista de educación económica y metodología económica también es muy limitado^[
Yalcintas y Selçuk (2016).]. En nuestra opinión, no es injusto decir que el tema de la inmoralidad entre los economistas se ha disfrazado en los debates abstractos en metodología económica desde la crisis financiera de 2008^[Maziarz2017).]. Creemos que sospechar de los hechos concretos y la evidencia ha jugado un papel en la exclusión de la ética de los debates metodológicos en economía. Como Boumans y Davis (2010, 171) argumentan que “[l] os juicios de valor metodológicos más importantes en economía involucran tres tipos de elecciones hechas por los economistas con respecto a cómo debe llevarse a cabo la economía: (i) la elección del tema a investigar; (ii) el método que se utilizará para investigar ese tema; y (iii) los criterios y normas utilizados para evaluar y juzgar la validez de los resultados de la investigación ”. De hecho, el rechazo de la teoría es tan importante como la elección de la teoría. La primera es una cuestión ética, mientras que la segunda es metodológica.

Una de las primeras fuentes que ayudó a los economistas a centrar su atención en la naturaleza de la crisis financiera de 2008 fue Inside Job (2010), un documental de Hollywood, dirigido por Charles Ferguson. Este documental no solo explicó cómo funcionaban las complejas herramientas financieras. También ofreció un panorama general del período de desregulación desde la década de 1980 hasta la fecha. La opinión que sostenía el documental era que grandes empresas como Goldman Sachs, Morgan Stanley y Lehman Brothers sabían que la crisis se avecinaba; pero no hicieron nada al respecto. El documental se proyectó en los festivales de cine de Cannes, Toronto y Nueva York en 2010. También ganó el Premio de la Academia de 2010.

Inside Job es la primera producción de Hollywood que aborda el tema de la ética de la investigación en economía. Ferguson sostiene que la profesión económica está totalmente corrompida. El documental proporciona evidencia de que los economistas escriben informes a empresas financieras y agencias de consultoría, pero no siempre expresan abiertamente que lo hacen. Según Ferguson, esto conduce al problema del conflicto de intereses en la economía.

El conflicto de intereses en la academia es un gran problema^[Valdés (1995), Mirowski (2002), Perkins (2004), Oriental (2006).]. Pero no es la única forma de prácticas de investigación cuestionables. La matematización, entre otros, también ha sido un tema en el que los metodólogos económicos han centrado su atención en sus críticas. Por ejemplo, Jesus M. Zaratiegui (1999) sostiene que “las matemáticas son un símbolo poderoso de la consistencia lógica interna que la economía ha desarrollado durante este siglo. Sin embargo, se le ha acusado de hacer un uso no crítico de los métodos matemáticos y de convertir estos métodos en un arma del imperialismo económico ”. Asimismo, en dos de sus artículos más recientes, Paul Romer, premio Nobel en Memoria de 2018, sostiene que la teoría macroeconómica adolece de la falta de evidencia empírica que sustente los modelos matemáticos de crecimiento económico. Él lo llama "matemáticas". Mathiness, según Romer, es un mal uso de las matemáticas en el que los economistas no proporcionan al lector los hechos del mundo para respaldar el modelo teórico. Romer (2016b) piensa que el contenido empírico inexistente en economía "indica un cambio de la ciencia a la política académica", lo que provoca un fracaso científico:

> El estilo que llamo matemáticas permite que la política académica se disfrace de ciencia. Al igual que la teoría matemática, la matemática usa una mezcla de palabras y símbolos, pero en lugar de establecer vínculos estrechos, deja un amplio espacio para el deslizamiento entre declaraciones en lenguaje natural versus formal y entre declaraciones con contenido teórico en lugar de empírico.

Romer no está en contra del uso de supuestos poco realistas en economía. Sin embargo, le preocupa el hecho de que los modelos macroeconómicos matemáticos no pueden verificarse porque no se comprueba si se ajustan a los hechos reales del mundo. Los puntos de vista de Romer sobre la teoría macroeconómica, según nuestro entendimiento, son una reformulación del descontento general entre muchos metodólogos económicos que han señalado los riesgos del uso excesivo y mal uso de las técnicas matemáticas en la economía aplicada desde la Segunda Guerra Mundial. Paul Romer, un macroeconomista que ha sido conocido por sus contribuciones matemáticas a la literatura sobre la teoría del crecimiento endógeno, lo señaló aunque no proporcionó evidencia en algunos de sus artículos más citados, como “Endogenous Technical Change” 20e “Integración económica y crecimiento económico”^[Rivera-Batiz y Romer (1991).], para sustentar sus modelos matemáticos, tampoco. Pero es tan claro como cualquier metodólogo económico profesional:

> Mi conjetura es que la teoría de cuerdas y la macroeconomía post-real ilustran un modo de falla general de un campo científico que se basa en la teoría matemática ... la conformidad con los hechos ya no es necesaria como un dispositivo de coordinación. En consecuencia, si los hechos contradicen la visión teórica oficialmente sancionada, quedan subordinados. Eventualmente, la evidencia deja de ser relevante (Romer 2016b).

## La "nueva" dicotomía {-}

La profesión económica ha sufrido durante mucho tiempo la teorización libre de hechos. Los argumentos “probados” con algunas pruebas de significación estadística bajo ciertas (e improbables) circunstancias han sido aceptados y ampliamente utilizados como si los modelos fueran verificados por hechos y datos^[Ziliak y McCloskey (1996, 2004, 2008).]. Como Toby Young (2016) dijo "todos somos post-verdaderos y probablemente siempre lo hemos sido".

"Vivimos en un mundo de posverdad", dice Ralph Keyes en su libro, The Post Truth-Era: Dishonesty and Deception in Contemporary Life (2004) “La posverdad existe en una zona de penumbra ética. Nos permite fingir sin considerarnos deshonestos ". La prevalencia de conclusiones fácticas inexactas en economía también ha llamado la atención de muchos economistas desde la crisis financiera de 2008. El problema que creemos que ha llevado a la teorización post-fáctica en economía es que los economistas no se comportan de manera responsable mientras realizan investigaciones. La principal fuente de la falta de responsabilidad es que

- los economistas no se refieren a datos y hechos
- no abandonan las teorías cuando las teorías son refutadas por datos y hechos

Originalmente, una comprensión de la ética en la ciencia se refiere al debate de la normatividad sobre la dicotomía entre "declaraciones-es" y "declaraciones-debería". La siguiente declaración es una declaración de tipo is: "La tasa promedio de crecimiento anual de EE. UU. Fue superior al 4% entre 1983 y 1988". La declaración es replicable y es producida por los investigadores que supuestamente son responsables ante el Banco Mundial^[Fuente: https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG?locations=US [Consultado en marzo de 2019].]. Sin embargo, la siguiente declaración es una declaración obligatoria donde la proposición es prescriptiva y se origina en una opinión: "Para que la economía global logre un crecimiento sostenible, debe introducir las políticas de libre mercado de los EE. UU." El debate sobre la normatividad ha sido popular en la metodología económica desde que David Hume lo formuló por primera vez en su Tratado sobre la naturaleza humana.(1739). Muchos metodólogos económicos se han referido a él a menudo cuando hablaban de "juicios de valor" y "moralidad"^[Por ejemplo Blaug (1980, 49-134).].

Aquí, afirmamos que para que los economistas solucionen los problemas de la era de la economía post-factual, los economistas deberían reconsiderar la vieja dicotomía con nuevos lentes. La dicotomía "nueva" se refiere a la distinción lógica entre una declaración correcta (o "declaración-es") y una declaración incorrecta (o "declaración-no-es"). Los economistas deberían insistir en trabajar con declaraciones de is-not (como "Según el FMI, la economía mundial creció al 3,5% en 2017")^[Fuente: https : //www.imf.org/external/datamapper/NGDP_RPCH@WEO/OEMDC/ADVEC/WEOWORLD Consultado en marzo de 2019.], mientras que deberían rechazar las declaraciones de is-not (como "... tasas de crecimiento medianas para países con deuda pública más de aproximadamente el 90% del PIB son aproximadamente un 1% más bajas que de otra manera; las tasas de crecimiento promedio (promedio) son varios por ciento más bajas ”)^[La declaración pertenece a (Reinhart y Rogoff 2010b) y es refutado por Herndon et al. (2013b).]. No distinguir entre un enunciado es y un enunciado que no es, que de hecho es una condición lógica, da lugar a problemas éticos en la investigación científica. Una declaración-is es una declaración en la que el modelo o la explicación se evidencia con datos y se verifica con los hechos del mundo. Una declaración es-no, por otro lado, es una declaración en la que el modelo no puede estar respaldado por datos y hechos. Hoy en día, la comprensión de la ética equivale a traer datos y hechos de nuevo a la ciencia para que podamos distinguir entre declaraciones correctas e incorrectas.

Cuando los economistas no rechazan una teoría refutada, no se comportan de manera responsable con la audiencia porque los economistas que siguen usando una declaración de "no es" infligen daño a otros investigadores. La condición para que los economistas den cuenta del mundo de manera significativa es que deben ceñirse a los enunciados que son y rechazar los enunciados que no son. Para que una teoría produzca una explicación significativa, la teoría debe verificarse con hechos en primer lugar. Solo las teorías verificadas por hechos pueden dar lugar a explicaciones significativas. En otras palabras, la economía no solo está cargada de valores, también está cargada de hechos.

La carga de hechos de una teoría es una condición para que el proceso de producción de conocimiento opere sin interrupciones. La interrupción puede ocurrir cuando los economistas no pueden corregir inconsistencias y manipulaciones. Si una teoría está libre de hechos, es poco probable que una crítica pueda eliminar la naturaleza abstracta de la teoría cuando la teoría no puede explicar las causas de un evento. En tales condiciones, las conversaciones académicas pueden encerrarse fácilmente en tonterías ideológicas donde la explicación no tiene ninguna relevancia para los hechos del mundo. En otras palabras, las teorías libres de hechos no siempre producen resultados pragmáticos sobre el mundo en el que vivimos.

Las teorías que están libres de hechos hacen que las opiniones reemplacen la evidencia en la investigación científica. Un economista que solo se refiere a opiniones puede construir modelos ficticios en los que los críticos podrían ser incapaces de detectar contenidos erróneos. Los modelos ficticios a menudo pueden dar cuenta de los hechos del mundo. Aunque el problema principal no son necesariamente los modelos ficticios per se , como sugiere el caso de Reinhart y Rogoff; Las declaraciones de "no es" que son invalidadas por evidencia infligen daño a la comunidad de investigadores, así como al público en general.

## Mirando hacia el futuro {-}

Los economistas llevan mucho tiempo interesados ​​en el estado de la economía^[Babbage1830), Marx (1859), Veblen (1909), Aspiradora (1926).]. En la década de 1970, Wassily Leontief se centró en el mal uso de las matemáticas en la economía. En sus "Supuestos teóricos y hechos no observados" (1971), afirmó que “[e] n la presentación de un nuevo modelo, la atención hoy en día suele centrarse en una derivación paso a paso de sus propiedades formales ... En el momento en que se llega a la interpretación de las conclusiones sustantivas, los supuestos sobre en los que se ha basado el modelo se olvidan fácilmente ... Lo que realmente se necesita, en la mayoría de los casos, es una evaluación y verificación muy difícil y rara vez muy clara de estos supuestos en términos de hechos observados ". De hecho, el hallazgo de Reinhart y Rogoff de que “la mediana de las tasas de crecimiento de los países con una deuda pública superior al 90% del PIB es aproximadamente un 1% más baja que en otros países; las tasas de crecimiento promedio (promedio) son varios por ciento más bajas ”fue, en términos de Leontief, un“ hecho no observado ”. Por tanto, una de las preguntas que suelen plantearse los metodólogos económicos es la siguiente: ¿Qué hay de malo en la economía?^[Fullbrook (2004), Coy (2009), Bell y Kristol (1981), Krugman (2009).] Los economistas, en gran medida, creen que la ética es irrelevante para lo que están haciendo en los laboratorios, aulas y salas de conferencias. Los campos de la economía especialmente aplicados en los que los economistas utilizan datos y algoritmos para dar cuenta de lo que creen que es importante para la economía es donde menos se piden la moral y la ética.

Como The Economist (2016) lo expresó sin rodeos, “los humanos no buscan la verdad de forma natural. De hecho, como muestran muchas investigaciones, tienden a evitarlo ". Históricamente, pensamos que la abstención de datos y hechos ha comenzado con David Ricardo. Ricardo fue uno de los primeros pasos para alejarse también de las filosofías morales de Adam Smith y David Hume. Cuando Ricardo pensó que refutaba la teoría del valor de Smith, de hecho refutó la moralidad que implicaba la teoría de Smith.

Los métodos abstractos, dirían muchos economistas aplicados, no requieren ética y moralidad. Por ejemplo, en Los elementos de la economía pura (1874), una de las obras más influyentes en la historia de la economía, Léon Walras (1874, 39) afirmaba así: "No debemos preocuparnos por la moralidad o inmoralidad de ningún deseo al que una cosa útil responda o sirva para satisfacer". Milton Friedman (1953, 180-213) estuvo de acuerdo con Walras cuando argumentó que: "La economía positiva es en principio independiente de cualquier juicio ético o normativo particular". La economía requiere excelencia en el uso de las herramientas con las que está equipado un economista. Además de todo, existen ciertos mecanismos que se ocupan de las consecuencias del comportamiento inmoral. Si eres un estudiante de doctorado, tu asesor supervisará tus acciones. Pero si eres economista profesional, ¿tu departamento o tu facultad te responsabilizan de tus acciones en las universidades en todo momento? La evidencia sugiere que este es siempre el caso. Creemos que la falta de respuesta de los economistas tiene mucho que ver con la creencia de que "la verdad saldrá a la luz". De hecho, ¿por qué los economistas deben preocuparse por "la moralidad o la inmoralidad" de un tema si la verdad,Poirot de Agatha Christie (2013), "tiene la costumbre de revelarse"? Es esta creencia lo que los metodólogos económicos deberían cuestionar.