# (PART) Parte I: Teoría {-}
# Libre albedrío y argumentos empíricos a favor del epifenomenalismo {#Capitulo_01}

```{r, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "html", results='asis', echo=FALSE}
cat('<hr style="background-color:#03193b;height:2px">')
```

Si bien los filósofos se han preocupado por la causalidad mental durante siglos, las preocupaciones sobre la relevancia causal de los fenómenos conscientes también aparecen cada vez más en la literatura neurocientífica. Los neurocientíficos han considerado interesante la amenaza del epifenomenalismo principalmente porque han supuesto que implica escepticismo del libre albedrío. Sin embargo, los pasos que nos llevan de una premisa sobre la irrelevancia causal de los fenómenos conscientes a una conclusión sobre el libre albedrío no están del todo claros. De hecho, si examinamos las explicaciones filosóficas populares del libre albedrío, encontramos, en su mayor parte, nada que sugiera que el libre albedrío sea inconsistente con la presencia de precursores neuronales inconscientes de las elecciones. Solo si adoptamos supuestos altamente no naturalistas sobre la mente (por ejemplo, si adoptamos el dualismo cartesiano y ubicamos la libre elección en el ámbito no físico) parece plausible suponer que los datos neurocientíficos generan una amenaza para el libre albedrío.

## Introducción {-}

En filosofía, mientras que las preocupaciones sobre la causalidad mental se remontan a siglos atrás, la cuestión de si el epifenomenalismo socava el libre albedrío es sorprendentemente poco explorada. En la literatura contemporánea, las preocupaciones sobre la causalidad mental tienden a derivar de la preocupación de que, si existe una explicación física adecuada para cada evento, esto hace que lo mental sea causalmente superfluo (Malcolm1968, Kim 1989, 1993, 1998, 2005; O'Connor y Churchill2010). Los filósofos se han preguntado sobre las implicaciones de este problema para la viabilidad de las teorías de la mente no reduccionistas, emergentistas o dualistas, pero ha habido poca conexión entre esta disputa y el problema tradicional del libre albedrío.

Por el contrario, en las neurociencias, los investigadores suponen típicamente que cualquier amenaza a la eficacia causal de la mente consciente es también una amenaza al libre albedrío. Las investigaciones que sugieren que nuestra conciencia de las opciones se produce demasiado tarde para influir en ellas causalmente (Libet et al.1979; Libetmil novecientos ochenta y dos, 1985; Soon et al.2008; Wegner2002, 2004) se ha considerado interesante principalmente porque tiene implicaciones drásticas para el libre albedrío.

Hay tres posibles explicaciones para esta curiosa disparidad:

1. El caso empírico del epifenomenalismo revela una clara amenaza epifenomenal; uno que tiene implicaciones más serias para la libertad que cualquier amenaza identificada por los argumentos filosóficos a favor del epifenomenalismo.

2. Los filósofos son ajenos a la amenaza que representa el epifenomenalismo para el libre albedrío.

3. Los investigadores empíricos se equivocan al suponer que la amenaza epifenomenalista que identifican realmente tiene serias implicaciones para el libre albedrío.

Argumentaré que la explicación (3) es correcta. No es obvio que los argumentos empíricos para epifenomenismo realmente no tienen graves consecuencias para la libertad y la responsabilidad moral.

## Las preocupaciones filosóficas {-}

Los rompecabezas sobre cómo la mente y el cuerpo interactúan causalmente se han discutido al menos desde la famosa correspondencia de Elisabeth de Bohemia con Descartes en 1643 (Atherton 1994, págs. 11-21). Tales acertijos llevaron a los teóricos, incluso cercanos a la época de Descartes, a buscar alternativas al interaccionismo cartesiano, como el ocasionalismo (por ejemplo, Malebranche1674, 1997), paralelismo (p. Ej., Leibniz 1695, 1989), y el monismo, ambos idealistas (por ejemplo, Berkeley 1710, 1982) y materialista (por ejemplo, Hobbes 1651, 1994; Cavendish1664, 2017). Y al menos desde Hodgson (1880) algunos filósofos han abrazado el epifenomenalismo.

Mientras que los filósofos contemporáneos han esperado predominantemente (al igual que Hobbes y Cavendish en la época de Descartes) que podamos dar sentido a la causalidad mental rechazando el dualismo a favor del fisicalismo, muchos han sido pesimistas sobre las perspectivas de reducir completamente lo mental a lo físico ( Putnam1967; Fodor1974; Bloque y Fodor1972; Pylyshyn1984). Y los argumentos de la "exclusión causal" pretenden mostrar que los fisicalistas no reduccionistas (no menos que los dualistas) pueden estar estancados con problemas de causalidad mental.

Como sostiene Kim, si la física es "causalmente completa", cada evento físico tiene una explicación causal suficiente que apela sólo a otros eventos físicos. Esto plantea un problema: si tenemos una explicación causal suficiente de un evento en términos físicos, esto parece hacer que los fenómenos mentales sean causalmente redundantes. A menos que estemos dispuestos (inverosímilmente) a postular una sobredeterminación constante, el reino mental resultará ser un epifenómeno (Kim1989, 1993, 1998).

Los fisicalistas no reduccionistas han supuesto que cada evento mental es realizado por un evento físico y, por lo tanto, los eventos mentales pueden ser causalmente efectivos debido a sus fundamentos físicos (por ejemplo, Davidson 1970). Pero incluso si esto hace que los eventos mentales sean causalmente efectivos, no los hace causalmente efectivos en cuanto a sus características mentales (Stoutland1980; Honderichmil novecientos ochenta y dos; Sosa1984).

Supongamos que el evento A es que Zina deja caer una estatua en un estanque con rencor y el evento B es que la estatua se hunde. El evento A tiene ciertas características, entre ellas su rencor. Pero esto parece irrelevante para cualquier explicación de por qué A causó B . El despecho con el que Zina dejó caer la estatua no es parte de la razón por la que se hundió. De manera similar, si los realizadores físicos de un evento explican suficientemente por qué el evento causó otro evento, el hecho de que estos eventos también realicen propiedades mentales parecerá irrelevante. Si bien los eventos mentales parecen realizarse mediante eventos físicos causalmente efectivos, estos eventos no parecen ser causalmente efectivos en virtud de sus cualidades mentales.

Estos temas se debaten acaloradamente y no se explorarán más a fondo. El epifenomenalismo sigue siendo una tesis filosófica muy controvertida.

## Las preocupaciones neurocientíficas {-}

Las preocupaciones sobre la irrelevancia de la mente consciente en la toma de decisiones surgieron con el famoso estudio de Libet, que pretende mostrar que las elecciones son iniciadas por eventos neuronales inconscientes antes de que los agentes se vuelvan conscientes de formar una intención de actuar (Libet et al. 1979; Libetmil novecientos ochenta y dos, 1985). Variaciones recientes de experimentos de estilo Libet (Soon et al.2008) proporcionan pruebas aún más contundentes de precursores neuronales inconscientes de las decisiones, y a menudo se supone que tal investigación suscita serias dudas sobre el libre albedrío (p. ej., Wegner 2002, 2004).

La supuesta amenaza surge de la sugerencia de que nuestro sentido de la voluntad consciente es un epifenómeno. Sin embargo, existen algunos problemas graves para llegar a esta conclusión sobre la base de los datos. En primer lugar, los precursores neuronales no se correlacionan perfectamente con las decisiones que les siguen. El propio Libet especuló que los agentes tenían algún poder de veto consciente hasta el último momento, y que esto nos da razones para rechazar la conclusión epifenomenalista (Libet1985, 2003). Pero el razonamiento de Libet sobre este asunto ha recibido serias críticas (por ejemplo, Gallagher2006).

Los estudios también se han centrado en lograr que los participantes tomen una decisión arbitraria sobre cuándo presionar un botón o cuál de los dos botones presionar, sin que existan consideraciones importantes a favor de ninguna de las dos acciones. Esta situación experimental está bastante alejada de las decisiones de la vida real. Quizás podamos delegar este tipo de toma de decisiones a procesos inconscientes más fácilmente que decisiones con consecuencias reales, que pueden requerir un compromiso más consciente (Waller2012).

Waller sugirió que los estudios podrían rediseñarse para probar si las decisiones moralmente significativas se iniciarían de manera inconsciente de manera similar, pidiendo a los participantes que tomen decisiones con resultados significativos. Por ejemplo, juegos de azar con fondos que se destinarán a una causa benéfica. Desde entonces, esto ha sido probado experimentalmente (Maoz et al.próximo) y los resultados corroboran la afirmación de Waller de que en el caso de elecciones moralmente significativas puede haber un aporte consciente mayor que el que está presente en el caso de elecciones totalmente arbitrarias. Esto arroja dudas sobre cualquier inferencia de la configuración experimental tradicional a conclusiones sobre la naturaleza epifenoménica de la conciencia de manera más amplia.

Además, incluso en el caso de una elección arbitraria, no está claro si puede haber una actividad consciente causalmente relevante correlacionada con los precursores neuronales de la conciencia consciente de la elección. Si estos precursores neuronales se correlacionan con otra actividad consciente que típicamente precede a una elección - contemplar presionar el botón, deliberar sobre presionar el botón, etc. - no sería sorprendente que tales eventos tendieran a preceder las elecciones e influir en las posibilidades de que el agente tome una decisión. elección particular. Esto no demostraría obviamente que la mente consciente fuera irrelevante para las elecciones que se tomaron posteriormente (Nahmias2010; Baumeister y col.2011).

Sería prematuro concluir que la conciencia no tiene un papel causal que desempeñar en la iniciación de elecciones, dado el estado actual de la investigación. Aunque es posible que a medida que avanza dicha investigación, puedan surgir pruebas neurocientíficas más sólidas.

### ¿Qué es la “voluntad consciente”? {-}

Supongamos que nos tomamos en serio esta supuesta amenaza epifenoménica. Todavía hay cierta falta de claridad en cuanto a cómo los datos experimentales nos permiten llegar a la conclusión de que el libre albedrío es ilusorio.

En primer lugar, la noción de "voluntad consciente" es vaga. El lenguaje de la "voluntad consciente" oscurece un poco el hecho de que por lo general se entiende que la voluntad, al menos en el pensamiento contemporáneo, es una especie de estado mental y no una facultad especial que posee el agente. El término "conciencia" también necesita desambiguación. Cuando decimos que la "conciencia" o la "voluntad consciente" es un epifenómeno, ¿qué queremos decir con esto?

Existen numerosas formas diferentes en las que los estados mentales pueden considerarse "conscientes". Al menos tres categorías parecen directamente relevantes:

1. Conciencia fenomenal :
 
 Para los propósitos actuales, podemos agrupar cosas tales como estados cualitativos , estados fenoménicos , sensaciones crudas y estados de lo que es . Parece haber cualidades directamente sensibles a algunos de nuestros estados mentales, que proporcionan el carácter de nuestras experiencias subjetivas. Los ejemplos comunes incluyen sensaciones de emoción, color, sabor o dolor. Además de 'qualia' o 'sensaciones crudas', esta categoría puede incluir otras dimensiones de cómo es una experiencia para su sujeto. Son estos aspectos fenomenales de la conciencia los que a veces se piensa que son difíciles de captar en términos objetivos o físicos (1958, Nagel1974; Jacksonmil novecientos ochenta y dos, 1986, Cuadra 1990).

2. Acceder a la conciencia :

 Para los propósitos actuales, podemos agrupar la conciencia de acceso , la conciencia informativa y los estados mentales que están disponibles personalmente para la conciencia . Estas categorías implican ser conscientes de que estamos sujetos a un estado mental de tal manera que podemos informar que estamos en tal estado y ser capaces de tener en cuenta el estado en nuestros pensamientos y deliberaciones. No es obvio que, para tener este tipo de acceso a un estado, debe haber algún carácter particular a la experiencia, por lo que la conciencia de acceso se distingue típicamente de la conciencia fenoménica (Block1995).
 
3. Contenido intencional / representativo:

 La literatura filosófica, en contraste con la literatura neurocientífica, a menudo se centra en los contenidos intencionales o representativos de los estados mentales; de qué se tratan nuestras creencias y deseos . A veces se piensa que el epifenomenalismo hace que estos contenidos sean causalmente irrelevantes. Esto parece ortogonal a los problemas de conciencia entendidos en términos de acceso o fenomenales. Incluso los estados inconscientes pueden tener un contenido intencional. Y algunos filósofos sugieren que las características fenoménicas de la conciencia son completamente distintas de las intencionales (Peacocke1983; Cuadra1996).

La idea de "voluntad consciente" tiende a invocarse con frecuencia, pero mal definida. No es obvio qué tipo de conciencia se supone que (a) tiene que ser causalmente eficaz para que el libre albedrío sea posible y (b) los datos la convierten en un epifenómeno.

## Epifenomenalismo y libertad de voluntad {-}

Supongamos que tenemos motivos para tomarnos en serio las amenazas a la eficacia causal de la conciencia identificadas en la literatura neurocientífica. No resulta inmediatamente obvio cuáles son las implicaciones para el libre albedrío. Para evaluar estas implicaciones, necesitamos una idea de lo que implica el libre albedrío. Echemos un vistazo breve a algunas de las principales explicaciones del libre albedrío y al tipo de requisitos que normalmente se consideran precondiciones necesarias.

Como la disputa sobre el libre albedrío se ha centrado típicamente en el determinismo más que en el epifenomenalismo, las explicaciones tienden a dividirse en términos de su compatibilidad o incompatibilidad con el determinismo; la tesis de que el futuro está fijado por las leyes de la naturaleza y por cómo eran las cosas en el pasado.

Las condiciones de libertad compatibilistas populares incluyen la capacidad de actuar sobre la base de las elecciones de uno (Moore 1903; Ayer1954; Inteligente1961. 1966; Luis1981; Berofsky2002), la capacidad de responder a razones (Fischer y Ravizza 1998; Lobo1990), y la capacidad de tomar decisiones basadas en los valores más profundos de uno (Frankfurt 1971, Dworkin 1970; Watson1975).

Los incompatibilistas suelen respaldar condiciones similares como necesarias para el libre albedrío, pero niegan que sean suficientes. También tienden a requerir que los agentes sean capaces, en un sentido sólido, de elegir lo contrario (Kane2000, 2002, 2004; Moya2006, 2007, 2011; Ekstrom2003; Elzein2017; Franklin2018; Kittle2018) o que los agentes son, en cierto sentido, las "fuentes últimas" de sus propias elecciones (Stump 1999a, B, 2003; Pereboom2000, 2001, 2003; Zagzebski2000, 2010; Timpe2007, 2008; Shabo2010; Más ancho2006, 2009). Por lo general, se piensa que el cumplimiento de estas condiciones requiere la falsedad del determinismo.

Tenga en cuenta que el determinismo no está relacionado con el epifenomenalismo. La cuestión de si alguna explicación de la libertad es compatible con el determinismo no tiene ninguna implicación para la cuestión de si es compatible con el epifenomenalismo. Si bien es sorprendentemente común encontrar los dos problemas combinados (Nahmias (2010) cita varios casos de este error), las dos tesis no están relacionadas.

¿Cómo llegamos de la premisa de que ciertos rasgos conscientes son epifenómenos a una conclusión sobre el libre albedrío? Debe haber algo requerido para el libre albedrío que sería plausiblemente excluido por el supuesto estado epifenoménico de esas características conscientes. Por lo tanto, deberíamos mirar las descripciones del libre albedrío comúnmente defendidas para ver si alguna de ellas incluye requisitos que podrían ser plausiblemente imposibles de cumplir si estas características conscientes resultan ser un epifenómeno.

Sin embargo, existen algunas restricciones sobre qué tipo de requisitos serían realmente fructíferos aquí. Los defensores del argumento empírico harían bien en buscar requisitos que no solo sean plausiblemente necesarios para el libre albedrío, sino que también cumplan con los siguientes criterios:

1. El requisito debe ser plausiblemente incompatible con el epifenomenalismo.

2. Si bien el requisito debe ser una condición necesaria para la acción libre y responsable , no debe ser también un requisito previo para cualquier acción (incluso las que no son libres).

3. El requisito debe ser coherente con la tesis de que lo mental sobreviene a lo físico.

La razón de la primera condición es obvia. A menos que el epifenomenalismo también descarte algún requisito de libertad, no podremos utilizarlo junto con el epifenomenalismo como base a partir de la cual inferir el escepticismo del libre albedrío.

El segundo requisito puede parecer misterioso. Si se requiere algo para la acción, debe, a fortiori , ser requerido para la acción libre . Por lo tanto, si podemos proporcionar una condición necesaria de acción que sería descartada por el epifenomenalismo, ciertamente tenemos un buen caso para el escepticismo del libre albedrío. Esto es cierto, pero significa que es probable que el argumento demuestre demasiado. Si bien se piensa comúnmente que el escepticismo sobre el libre albedrío es una conclusión sorprendente pero no obstante potencialmente convincente, el escepticismo sobre la agencia es mucho menos plausible y es probable que se considere una implicación desagradable. Algunos pueden estar dispuestos a morder esta bala, pero para otros la implicación de que no hay agentes o acciones es más probable que se considere una reducción.de cualquier argumento que lo condujo. Por lo tanto, el argumento perderá mucha plausibilidad si solo puede llegar a una conclusión escéptica sobre el libre albedrío a través de una conclusión escéptica mucho más fuerte sobre la agencia.

El requisito final, que debe ser coherente con la afirmación de que lo mental sobreviene a lo físico, parece un requisito previo básico para que tengamos alguna razón para tomar en serio la literatura neurocientífica en primer lugar. Toda la idea de estudiar la mente a través de una investigación del cerebro sería errónea a menos que estuviéramos dispuestos a conceder esta tesis.

La pregunta es si alguna de las cuentas estándar de libre albedrío postula requisitos que cumplen con estos criterios. Si bien las categorías de "incompatibilista" y "compatibilista" son útiles en relación con la disputa sobre el determinismo, no son tan relevantes para la amenaza del epifenomenalismo. Para los propósitos presentes, dividiré las supuestas condiciones previas del libre albedrío en aquellas que también son condiciones previas para cualquier acción y aquellas que son condiciones previas específicamente para la acción libre . Estos últimos también se dividirán en requisitos naturalistas y no naturalistas.

### Condiciones de acción supuestas {-}

¿En qué condiciones el comportamiento cuenta como acción genuina? Como mínimo, debe ser intencional o estar dirigido a un objetivo. Pero eso no es suficiente; el comportamiento de una máquina simple podría estar dirigido a un objetivo. De manera plausible, debe estar dirigido conscientemente a un objetivo. El agente debe tener alguna intención al actuar y debe ser consciente de ello. Esto es lo que parece faltar en el caso de la acción automatizada, como el sonambulismo, que no suele clasificarse como agencia genuina. Si bien los sonámbulos parecen llevar a cabo sus intenciones, no son conscientes de lo que están haciendo.

Esto ciertamente incluye una falta de conciencia de acceso; no pueden informar o reflexionar más sobre lo que están haciendo. Puede ser plausible suponer que los agentes que sueñan disfrutan de una conciencia fenoménica; son, en cierto sentido, conscientes de las cualidades fenoménicas que se les presentan en sus sueños. Pero estos agentes ciertamente carecen de una conciencia fenomenal con respecto a lo que realmente están haciendo. Las intenciones con las que actúan están desconectadas del comportamiento que realmente está ocurriendo.

Parece plausible que los agentes necesiten acceder a la conciencia para contar como actuantes, y plausible, aunque más controvertido, que los agentes puedan necesitar una conciencia fenoménica para contar como actuantes (Shepherd2015a). Esto último dependerá de si un "zombi fenomenal" aún podría realizar acciones; una pregunta que no es fácil de responder (Smithies2012).

Pero una cosa es suponer que la agencia requiere conciencia y otra muy distinta suponer que requiere que nuestros estados mentales sean causalmente eficaces en virtud de sus cualidades conscientes, o que la conciencia consciente debe preceder temporalmente al inicio de las elecciones.

Considere el comportamiento automático; del tipo que se realiza en "piloto automático". A menudo, los agentes carecen de conciencia cuando realizan acciones muy ensayadas; pero normalmente se piensa que cuenta como una actuación de todos modos. Esto se debe a que son fácilmente capaces de adquirir conciencia. Si está conduciendo, es posible que no se dé cuenta de que indica que debe girar, pero si alguien le pide que se explique, puede fácilmente darse cuenta de lo que está haciendo. En este caso, no es obvio que la conciencia deba preceder al inicio de la conducta; más bien, el comportamiento y las intenciones que lo motivan deben ser fácilmente accesibles a la conciencia (Levy y Bayne2004; Exacción2011; Exacción2013, 2014a).

La razón por la que la conciencia de acceso parece importante es porque parece caracterizar el tipo de procesos mentales que pueden parecer especialmente relevantes para nuestro control sobre nuestro comportamiento. Tendemos a ser capaces de informar conscientemente los tipos de procesamiento que pertenecen directamente a nuestros objetivos deliberados y que podrían ser susceptibles de reflexión y escrutinio racionales. Por el contrario, gran parte de la actividad que se produce por debajo del nivel de conciencia está fuera de nuestro control directo , pero, no obstante, puede estar gobernada en general por estos objetivos de nivel superior.

Varios autores han tratado de dilucidar la importancia de los tipos de procesamiento que tienden a estar disponibles para la conciencia de esta manera. Pastor2015b) argumenta que los tipos de procesamiento que están típicamente disponibles para la introspección consciente son aquellos involucrados en "funciones ejecutivas". Los tipos de procesos que no están disponibles para la conciencia consciente son aquellos que ocurren a un nivel subpersonal y no son directamente accesibles a la reflexión consciente. Estos suelen estar subordinados al procesamiento ejecutivo. Por ejemplo, nuestra intención explícita de recoger algo dirige nuestros procesos motores. En relación con esto, Gallagher (2006) señala que se puede esperar que conozcamos directamente las características de nuestra situación y entorno, mientras que los procesos subpersonales siguen siendo en gran medida inaccesibles en ese nivel de cognición, a pesar de estar ampliamente dirigidos por procesos en ese nivel. Otros han notado que nuestras intenciones proximales, incluso si se forman de manera bastante automática, pueden estar dirigidas por intenciones distales que normalmente están disponibles para la conciencia consciente (Nahmias2010; Schlosser2013).

La acción genuina generalmente involucra procesos de los que somos conscientes, ya que estos tienen un papel "ejecutivo" o "director". Pero no hay ninguna razón obvia para suponer que la conciencia consciente misma deba estar causando. La conciencia consciente es un indicador de que los procesos en cuestión son del tipo que caracteriza la agencia genuina. Pero esto no implica que tales procesos deban ser causados por la conciencia. Y ciertamente no parece que el "sentimiento fenomenal" deba causar el comportamiento (Walter2014). Parece muy dudoso suponer que nuestras intenciones deben ser causalmente efectivas en virtud de la conciencia de acceso o de la conciencia fenoménica, incluso si deben estar disponibles para cualquier tipo de conciencia consciente.

Una sugerencia más plausible es que debemos actuar en virtud de los contenidos intencionales o representativos de nuestros estados mentales para que se consideren auténticos actos; que lo que deseo y creo debe ser causalmente relevante para mi comportamiento. Pero este no es el foco de ninguna de las publicaciones empíricas que apuntan a socavar el libre albedrío. Solo se aborda realmente en la literatura filosófica. Además, esta amenaza, si se toma en serio, es mucho más amplia que una simple amenaza a la posibilidad del libre albedrío. Potencialmente, implica que todo el reino mental está desprovisto de toda influencia. Pocos filósofos abrazan esta conclusión.

Incluso si la agencia es posible, sin embargo, la agencia libre podría no serlo. Los argumentos epifenómenos pueden amenazar nuestra capacidad de actuar libremente o ser considerados moralmente responsables. Consideremos las condiciones de libertad ampliamente naturalistas; aquellos que no postulan fenómenos fuera del alcance de la investigación científica.

### Condiciones de libertad supuestamente naturalistas {-}

#### Actuar sobre la base de elecciones {-}

Se supone universalmente que la responsabilidad moral requiere la capacidad de actuar de acuerdo con nuestras elecciones. Si un agente es encarcelado o paralizado, o si existen limitaciones e impedimentos que obstaculizan su capacidad para actuar como pretende, esto socavaría su libertad y su responsabilidad moral (Moore1903; Ayer1954; Inteligente1961; Luis1981; Berofsky2002).

Pero los argumentos epifenómenos no representan una amenaza para esta capacidad. Este requisito no dice nada sobre la forma en que se inician nuestras decisiones o sobre las características en virtud de las cuales cuentan como causalmente eficaces. Por lo general, se entiende simplemente en términos de dependencia contrafáctica; un agente cumple con este requisito si actúa como ha elegido y habría actuado de otra manera si hubiera optado por actuar de otra manera. Los estudios de estilo Libet pretenden socavar la relevancia causal de la conciencia consciente para las elecciones de los agentes; no pretenden socavar la relevancia causal de las elecciones de los agentes para sus acciones posteriores.

#### Razones de capacidad de respuesta {-}

A menudo se supone que nuestras decisiones tendrían que responder a razones para que podamos contar como moralmente responsables (Wolf 1990; Fischer y Ravizza1998). Schlosser (2013) y Levy (2011, 2013, 2014a, B) han argumentado que existe un vínculo crucial entre la conciencia y la capacidad de responder a las razones. Ambos suponen que es (ampliamente) la conciencia de acceso lo que se requiere para esta capacidad, en oposición a la conciencia fenoménica.

La razón por la que podríamos suponer que la conciencia de acceso es crucial para la capacidad de respuesta a las razones es que solo este tipo de procesamiento consciente parece estar gobernado por normas de coherencia de tal manera que se integra potencialmente en una perspectiva racional. Nuestro procesamiento inconsciente tiende a funcionar de manera asociativa y no a regirse por normas de coherencia (Levy2013, 2014a, B).

Esto nos da razones para suponer que solo podemos ser moralmente responsables de los procesos que son accesibles a la conciencia consciente. Pero no parece implicar que nuestras elecciones deban iniciarse conscientemente, o que deban ser causalmente eficaces en virtud de características conscientes.

La acción automática suele estar impulsada por el tipo de intención que se puede llevar fácilmente a nuestra conciencia consciente, incluso si a menudo no nos damos cuenta al iniciar la acción (Levy y Bayne 2004; Exacción2011). No parece haber ninguna razón para suponer que tal comportamiento sea inmune a la introspección y al escrutinio racional.

Además, el punto crucial para la respuesta a las razones no es que la conciencia consciente en sí misma deba estar haciendo el trabajo causal, sino que los tipos de procesos de los que somos conscientes son los que están gobernados por estándares de coherencia racional. Incluso si tales procesos fueran iniciados por eventos inconscientes, esto no evitaría que se rijan por estas normas, por lo que no les impedirá ser razonables.

#### Armonía con valores más profundos {-}

Plausiblemente, si nuestras elecciones han de contar como gratuitas, deben estar impulsadas por deseos que no nos importa que nos conmuevan (Dworkin 1970). Quizás deben armonizar con nuestras voliciones de segundo orden, es decir, debemos ser movidos por los deseos de primer orden por los que queremos ser movidos (Frankfurt1971). Quizás, en última instancia, necesitamos que nuestras elecciones estén en armonía con nuestros valores más profundos (Watson1975). Podría pensarse que nuestro sistema de valores más profundo, aquellos con los que nos identificamos racionalmente, constituyen el “yo real”.

Hay un fuerte argumento para suponer que solo los procesos conscientes armonizan típicamente con nuestros valores más profundos. Dado que una perspectiva moral debe integrarse en un sistema coherente, también debe regirse por normas de coherencia. Los procesos inconscientes no obedecen estas normas (Levy2011, 2013). Además, es bien sabido que los agentes a menudo procesan inconscientemente la información de formas que van directamente en contra de sus valores; en los casos de prejuicios inconscientes, los agentes suelen encontrar que su comportamiento refleja actitudes que repudian conscientemente; a menudo están dispuestos a deshacerse del prejuicio o tomar medidas para evitar que influya en su comportamiento (Levy2013; Exacción2014a, B).

Una vez más, se suele argumentar que aquí es relevante la conciencia de acceso en lugar de la conciencia fenoménica; los tipos de procesos que podemos informar y sujetos a escrutinio son los que podemos esperar armonizar con nuestros valores. Lo que importa es que dicho tratamiento se rige por normas de coherencia racional y puede estar sujeto a escrutinio sobre la base de valores. Esto es lo que le permite armonizar con nuestros valores. Esto no requiere la conciencia en sí misma para causar nuestras decisiones o preceder su iniciación.

#### Posibilidades alternativas {-}

A menudo se piensa que las posibilidades alternativas son importantes para la responsabilidad moral, aunque esto ha sido muy controvertido desde el famoso argumento de Frankfurt sobre su irrelevancia (Frankfurt 1969).

Los compatibilistas tradicionalmente entienden este requisito en términos de una dependencia contrafáctica entre las elecciones y acciones de un agente. Ya hemos señalado que esto no se ve afectado por el epifenomenalismo. Los incompatibilistas, sin embargo, tienden a tener una comprensión diferente de las posibilidades alternativas. Por lo general, requieren que los agentes puedan hacer lo contrario manteniendo constantes las leyes de la naturaleza. El determinismo parece excluir las alternativas así entendidas.

Como ya se señaló, el epifenomenalismo no implica determinismo. Quizás, sin embargo, los estudios al estilo de Libet también deberían entenderse como evidencia de la tesis de que nuestras elecciones están determinadas causalmente. Soon et al. (2008) pudieron predecir la elección de un agente entre cuál de los dos botones presionar (es decir, una decisión con un 50% de probabilidad de ir en cualquier dirección) con un 60% de precisión, mucho antes de que los propios agentes se dieran cuenta de que decidían. Pero esto no constituye una prueba convincente para el determinismo; no implica que se garantice un resultado único. Los defensores del indeterminismo suponen típicamente que la causalidad es probabilística en oposición a determinista. Esto es consistente con eventos anteriores que aumentan la probabilidad de eventos posteriores.

### Condiciones de libertad supuestas no naturalistas {-}

Las condiciones naturalistas de la libertad parecen no haber sido tocadas por los argumentos a favor del epifenomenalismo, pero no es tan obvio que ocurra lo mismo con las no naturalistas.

A veces, se piensa que la libertad requiere habilidades divinas; que el libre albedrío implica ser un "motor inmóvil", capaz de originar acciones independientemente de cualquier evento anterior. Hay dos características que pueden parecer condiciones previas para esto; una implica que la mente consciente es la fuente causal última de elecciones, y la otra implica inmunidad frente a la influencia causal previa.

#### Originación consciente {-}

Los incompatibilistas de fuentes suponen típicamente que el determinismo amenaza el libre albedrío porque amenaza el estatus del agente como la fuente última de sus propias elecciones y acciones. ¿Los argumentos epifenomenalistas desafían esto? Depende de cómo ubiquemos a los agentes. Si los procesos cerebrales inconscientes se consideran parte de los esfuerzos del agente, entonces no es obvio que el agente solo podría estar iniciando una acción si los fenómenos conscientes la están iniciando. Los procesos mentales de un agente podrían estar haciendo el trabajo causal incluso si la conciencia consciente misma no estuviera involucrada en el inicio de las elecciones.

Si la conciencia se entiende simplemente como una forma de acceder a nuestros estados mentales, entonces esto simplemente no parece el tipo de cosa que podría figurar inteligiblemente en una relación causal. No es obvio cómo la mera disponibilidad de estados para la conciencia consciente podría causar nuestras elecciones. Y con respecto a la conciencia fenoménica, nuevamente, parece extraño suponer que la cruda sensación de tomar una decisión podría causarla (Walter2014).

Si la conciencia va a figurar de manera inteligible como una causa independiente, parece que tendremos que entenderla como algo más que una forma en que los estados mentales se presentan a la conciencia. Más bien, necesitaríamos suponer que los estados conscientes son parte de una entidad independiente que podría ejercer su propia influencia.

Quizás se considere que la conciencia es el elemento crucial de un alma cartesiana. Si suponemos que la libertad requiere el alma a la acción influyen de forma independiente de los eventos neuronales, entonces tal vez podría tener sentido suponer que la conciencia fenomenológica podría ser parte de algo causalmente influyente en su propio derecho. Si esto es lo que requiere el libre albedrío, entonces el caso empírico del epifenomenalismo, al mostrar que la conciencia llega demasiado tarde al juego, estaría demostrando que el agente (presumiblemente, idéntico al alma cartesiana y no a ningún precursor neuronal) no podría ser la fuente última de sus elecciones.

#### Inmunidad frente a influencias previas {-}

Este requisito podría complementarse con otro; quizás lo que se requiere para la libertad no es simplemente que nuestras elecciones sean causadas por una entidad consciente independiente, sino también que estas elecciones sean inmunes a la influencia causal previa.

Algunos suponen que incompatibilistas elecciones libres deben ser no causada (Ginet2002, 2007, 2008, 2016; McCann1998, 2012; Goetz1988, 2008). Presumiblemente, esto descarta incluso la causalidad probabilística. ¿Implica esto que no puede haber correlación entre las elecciones de un agente y los eventos neuronales que preceden a esas elecciones? Esto no es obvio. Los no causalistas generalmente suponen que las elecciones de un agente deben ser racionalmente explicables, incluso si no son causalmente explicables. Pero supongamos que algún patrón de actividad neuronal se asocia típicamente con la evaluación positiva de un curso de acción potencial. Este patrón también estaría correlacionado con la presencia de una razón positiva para elegirlo. Desde el punto de vista no causal, la elección del agente también debe correlacionarse con la presencia de tales razones. Por lo tanto, esperaríamos que la elección y el patrón neuronal también estuvieran correlacionados entre sí.

Sólo si presuponemos una explicación explícitamente no naturalista del agente y sus procesos mentales (por ejemplo, suponemos que no hay correlaciones entre los procesos neurales y la contemplación de las razones por parte del agente) que una explicación no causal descarta cualquier correlación entre las probabilidades de que un agente tome una decisión particular y precursores neuronales.

Supongamos que consideramos al agente como esencialmente idéntico a un alma cartesiana, y suponemos que un agente sólo puede tener libre albedrío en la medida en que cualquier explicación racional de su comportamiento emana completamente del alma independientemente de cualquier proceso cerebral. Los estudios al estilo Libet ciertamente parecen arrojar algunas dudas sobre si los agentes pueden cumplir con este requisito.

## Epifenomenalismo y escepticismo del libre albedrío {-}

Recuerde, argumentó que, si queremos alcanzar el escepticismo del libre albedrío sobre la base de la evidencia del epifenomenalismo, necesitaríamos identificar algún requisito para el libre albedrío que también cumpla con los siguientes criterios:

1. El requisito debe ser plausiblemente incompatible con el epifenomenalismo.
 
2. Si bien el requisito debe ser una condición necesaria para la acción libre y responsable , no debe ser también un requisito previo para cualquier acción (incluso las que no son libres).

3. El requisito debe ser coherente con la tesis de que lo mental sobreviene a lo físico.

Examiné tres categorías de supuestos requisitos para la libertad: condiciones de agencia básica, condiciones naturalistas del libre albedrío y condiciones no naturalistas del libre albedrío.

Obviamente, ninguna de esas condiciones que supuestamente son prerrequisitos para cualquier acción podrá cumplir con la condición 2: un argumento a partir de esas condiciones no solo establecerá el escepticismo del libre albedrío, sino que también mostrará que no hay agencia de ningún tipo. . Esto ciertamente socavaría el libre albedrío, pero viene con la inverosímil implicación de que las acciones tampoco existen.

Además, descubrimos que los tipos de conciencia que podrían resultar potencialmente epifenómenos por los argumentos empíricos probablemente fueran irrelevantes para las condiciones de acción. Si bien tales argumentos pueden mostrar que la conciencia fenoménica ocurre después del inicio de una elección, no es obvio que esta cuestión de tiempo sea especialmente relevante para el papel de la conciencia de acceso, y los argumentos empíricos no nos dicen nada sobre el papel causal de intencional o contenido representativo.

Sólo si se demuestra que este último es un epifenómeno, es posible que tengamos una seria amenaza para la agencia; Si bien podría pensarse que los argumentos filosóficos convierten el contenido intencional en un epifenómeno, los argumentos empíricos no parecen abordarlo en absoluto. El requisito de que seamos capaces de actuar en virtud de contenidos intencionales, si es un requisito del libre albedrío, no cumple en ningún caso la condición 2, y en relación con los tipos de epifenomenalismo plausiblemente implicados por la investigación empírica, no tampoco cumpla la condición 1.

Pasemos a los requisitos naturalistas del libre albedrío.

La posibilidad de cumplir con los supuestos requisitos naturalistas para el libre albedrío, sugerí, no está amenazada por el epifenomenalismo, por lo que estos requisitos no cumplen con el criterio 1.

Si bien nuestras elecciones solo pueden cumplir los requisitos de ser razonables y estar en armonía con nuestros valores más profundos si esas decisiones implican un procesamiento del tipo del que normalmente somos conscientes, no hay razón para suponer que cualquier tipo de conciencia consciente deba causar o incluso preceden temporalmente a dicho tratamiento para que sean motivos de respuesta o para armonizar con nuestros valores. Y los estudios empíricos no influyen en absoluto sobre si nuestras elecciones están determinadas causalmente.

Finalmente, los supuestos requisitos de libertad no naturalistas no cumplen con el criterio 3. Si se entiende que cumplen genuinamente con el criterio 1 (es decir, que involucran un papel causal para la conciencia en sí misma y / o que carecen de cualquier correlación con eventos neuronales previos) , esto requeriría que identifiquemos a los agentes con algo no físico; por ejemplo, un alma fantasmal, que es un motor inmóvil y es la fuente última de elecciones y acciones. Esto es incompatible con la tesis de que lo mental sobreviene a lo físico.

Podría decirse que tales estudios deberían importarle a alguien con una visión interaccionista cartesiana clásica. Dado que la conciencia fenoménica, según este punto de vista, reside en una mente no física independiente, y esto influye causalmente en la actividad cerebral, tal vez la conciencia fenoménica deba preceder al inicio de las elecciones. Pero el interaccionismo cartesiano es poco popular hoy en día. Hay razones para rechazarlo con total independencia del caso empírico del epifenomenalismo; muchas de estas razones fueron identificadas inmediatamente después de su inicio en el siglo XVII.

Como se señaló anteriormente, esto llevó a otros teóricos históricos a favorecer el monismo (idealista y materialista) oa favor de análisis paralelos u ocasionalistas de la relación entre lo mental y lo físico. El problema es, no es obvio que los defensores de las alternativas a interaccionismo que apoyan las cuentas altamente no naturalistas de libre tendrán ninguna buena razón para suponer que la investigación neurocientífica nos dice nada en absoluto acerca de la mente. Estos puntos de vista colocan a la mente completamente fuera del alcance de la investigación científica.

Además, los filósofos contemporáneos respaldan abrumadoramente el fisicalismo. Son raros los que se toman en serio las condiciones de libertad no naturalistas. Aquellos que respaldan esas condiciones junto con el interaccionismo cartesiano son aún más raros (una especie en peligro de extinción, si no extinta).

Los estudios de estilo Libet no presentan evidencia para suponer que no podamos cumplir con las condiciones naturalistas de libertad. Y en cuanto a los no-naturalista, cualquiera que se tome en serio la investigación neurocientífica tenía abrumadora razón para que nadie suponga que pudiera satisfacer los independientemente de estos estudios. En contraste, aquellos que sostienen que cumplimos con condiciones no naturalistas, en su mayor parte, deben considerar tales cosas como fuera del alcance de la investigación neurocientífica.

## Conclusión {-}

El panorama de la disputa por el libre albedrío no se ve afectado en gran medida por el caso empírico del epifenomenalismo. Sorprendentemente, parece que los investigadores empíricos han sido propensos a presuponer una imagen de libertad, desde el principio, que sería completamente inconsistente con una especie de fisicalismo mínimo en el que se basa toda la empresa de la neurociencia. De alguna manera, todavía están obsesionados por el fantasma del interaccionismo cartesiano.

En la medida en que respaldamos una imagen ampliamente naturalista y fisicalista de la mente (una imagen que creo que tenemos una abrumadora buena razón para abrazar), no es obvio que los datos experimentales presenten un desafío serio para cumplir con las condiciones de libertad que podrían ser plausiblemente. se reunió de acuerdo con esa imagen de todos modos. Por el contrario, para cualquiera que rechace explícitamente esa imagen, los datos empíricos se considerarán de dudosa relevancia desde el principio.

Creo que hay razones de peso sobre las cuales abrazar el escepticismo del libre albedrío. Pero estas razones tienen poco que ver con la presencia de precursores inconscientes de las decisiones que tomamos.