# Ensayo sobre economía humilde {#Capitulo_12}

```{r, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "html", results='asis', echo=FALSE}
cat('<hr style="background-color:#03193b;height:2px">')
```

El propósito de este ensayo es mostrar que el alejamiento de la rama walrasiana de la economía neoclásica podría conducir a la conceptualización de la economía como una ciencia humilde, es decir, una ciencia consciente de sus capacidades explicativas, pero también convencida de que no es posible descubrir regularidades inequívocas. . La economía humilde no pretende tener el poder de formular explicaciones que no necesiten más justificación. Se basa en una ontología de potencialidades donde no se encuentran leyes, sino capacidades, tendencias, naturalezas y dynameis aristotélicas. Se basa en el reconocimiento de que existe un misterio inherente al funcionamiento de la economía.

> El hombre que afirma que la ciencia económica tiene mucha exactitud es un charlatán. L. Robbins (1927, 176).
>
> Facultad de Ciencias Económicas de la Universidad de Varsovia y miembro del Comité de Política Monetaria del Banco Nacional de Polonia. Esta investigación fue financiada por una beca de investigación en el marco del Programa Nacional para el Desarrollo de las Humanidades (NPRH) (beca no 2bH 15 0266 83).

## Comentarios introductorios {-}

La economía se refiere a leyes, causas, regularidades, mecanismos o dependencias de naturaleza puramente probabilística. Sin embargo, estas cuestiones son objeto de acaloradas disputas entre los propios economistas. Muchos de ellos creen que la explicación de los fenómenos económicos a través de su subsunción bajo leyes no tiene sentido, mientras que a otros les gustaría que las leyes de la economía se parecieran al estatus de leyes casi universales de la naturaleza^[En aras de la simplicidad, equiparo tales leyes a regularidades universales (del tipo: si X , entonces Y ) que son omnitemporal y omnispacialmente verdaderas, y que al mismo tiempo se caracterizan por un alto nivel de necesidad (Hardt2017). Además, tales leyes no son iguales a las leyes naturales morales.]. L. Walras fue el primero en afirmar que “[…] la teoría pura de la economía es una ciencia que se asemeja a las ciencias físico-matemáticas en todos los aspectos” (Walras1874/ 1984, 71), y luego, casi 80 años después de la publicación de Éléments d'Économie Politique Pure de Walras , K. Arrow y R. Debreu ofrecieron una prueba matemáticamente expresada de la existencia de un equilibrio para una economía competitiva. Su artículo fue publicado cuando el modelo de explicación deductivo-nomológico estaba en su apogeo. Por lo tanto, estaba a solo un paso de proyectar la economía como la física de las ciencias sociales. Sin embargo, a fines de la década de 1960, la economía comenzó a ser cada vez más diversa y, en la filosofía de la ciencia misma, el modelo de Hempel-Oppenheim comenzó a fallar en sus cimientos. Se ha iniciado una discusión sobre si es apropiado explicar los fenómenos empíricos subsumiéndolos bajo leyes generales.

En la década de 1970 se produjeron muchos cambios importantes en la economía. En este período excepcional, un giro cognitivo impactó a la ciencia económica, los arquitectos clave del marco de equilibrio general demostraron que los macrofenómenos no se pueden reducir fácilmente a micro, y por lo tanto, la perspectiva mecanicista dominante ha comenzado a cuestionarse lentamente^[Aquí me refiero, entre otros factores, a las implicaciones del teorema de Sonnenschein-Mantel-Debreu que establece que las funciones de demanda agregada que se basan en preferencias individuales y otros postulados neoclásicos no cumplen con el axioma débil de preferencias reveladas (WARP). Y dado que se viola el WARP, entonces a nivel agregado es imposible probar la existencia de un equilibrio único y estable. Hahn1995) vio el teorema de SMD como el ataque más devastador a la economía neoclásica microfundada.]. Economistas como H. Simon, D. Kahneman, A. Tversky y V. Smith, en cierto sentido, lograron el sueño incumplido de A. Marshall que quería que la economía estuviera más arraigada en las ciencias biológicas^[Aquí me refiero a las conocidas palabras de Marshall: "La Meca del economista es la biología económica más que la dinámica económica" (1898, 43).]. K. Arrow mismo dijo muchos años después:

> […] La noción misma de lo que constituye una teoría económica tendrá que cambiar. Durante un siglo, algunos economistas han sostenido que lo biológico es un paradigma más apropiado para la economía que los modelos de equilibrio análogos a la mecánica. […] La teoría económica bien puede tomar un curso análogo (1995, 1617-1618).

Los cambios en la economía neoclásica a fines del siglo XX cobraron tal ímpetu que D. Colander en su perspicaz 2000El periódico escribió que la economía neoclásica está muerta^[Incluso fue P. Samuelson, el llamado Sr. Economía Neoclásica , quien afirmó en 1976 que “Hablar de teorías neoclásicas tiene ciertas implicaciones. Es más apropiado hablar de economía dominante ”(en: Pizano2009, 117). Entonces, incluso él fue de alguna manera influenciado por un espíritu cambiante de la economía en los años 70.]. El mensaje de su texto era que la economía es tan diversa y pluralista que no tiene sentido usar el término 'economía neoclásica' que está asociado con el marco de equilibrio general, y es mejor hablar simplemente de la economía dominante. Los años siguientes fueron testigos de una mayor expansión del explanandum y explanans económicos y, como resultado, surgieron disputas sobre si los límites de la economía deben definirse por sus métodos o por un conjunto de problemas a los que se puede aplicar la economía. Las acaloradas discusiones sobre el estado de la neuroeconomía son un buen ejemplo^[Véase, por ejemplo, un número especial de Journal of Economic Methodology (2010, no 2) que trata exclusivamente del estado metodológico de la neuroeconomía y su potencial explicativo.].

Lo anterior provoca la siguiente pregunta: ¿fue la economía neoclásica walrasiana solo un interludio a corto plazo en el desarrollo de la economía que, por lo demás, tiene una visión humilde de sus capacidades de investigación y comunica al público que solo puede adquirir conocimiento sobre tendencias contingentes, causas, o naturalezas de las cosas, pero no sobre las leyes universales y constantes de la naturaleza? La economía clásica fue en gran medida una ciencia tan humilde como lo ilustra la conocida declaración de N. Senior de que “las conclusiones [del economista], cualquiera que sea su generalidad y su verdad, no le autorizan a añadir una sola sílaba De consejo" (1836/ 1951, 2-3), o la afirmación de JS Mill de que las leyes económicas son únicamente declaraciones de tendencias. Los economistas clásicos fueron mucho más cuidadosos al dar fuerza vinculante a sus opiniones que sus sucesores neoclásicos (Colander2011).

El uso generalizado de modelos formales por parte de los economistas neoclásicos significó que la comprensión positivista de la ciencia se alineara cada vez menos con su práctica de investigación. Dado que el modelado se ha convertido en un signum specificum de la economía, su evaluación metodológica debe incluir referencias a diferentes formas de estudiar la ciencia, a saber, las que se suscriben a un ideal de ciencia basado en modelos, en lugar de a las ideas bien establecidas de la ciencia construida sobre las leyes de la ciencia. naturaleza. Esto también hace necesario alejarse de la mecánica determinista de Newton e implica la necesidad de enfrentarse a un mundo multicapa en el que los factores inobservables juegan un papel clave^[Incluso podemos tratar lo inobservable como un anatema para muchas concepciones empiristas de la ciencia. Además, permitir la entrada de inobservables en la ciencia hace que la metafísica sea necesaria en las explicaciones filosóficas de la ciencia (Chakravartty2007, dieciséis).].

El propósito de este ensayo es mostrar que el alejamiento de la rama walrasiana de la economía neoclásica conduce a la conceptualización de la economía como una ciencia humilde, consciente de sus capacidades explicativas, pero también convencida de que no es posible descubrir regularidades inequívocas. Esta humilde economía no pretende tener el poder de formular explicaciones que no necesiten más justificación. En otras palabras, simplemente no es posible eliminar el misterio inherente al funcionamiento de la economía.

El ensayo está organizado de la siguiente manera. Primero, se ofrecen algunas ideas preliminares sobre la forma en que entiendo una ciencia humilde. A continuación, se presentan algunas reflexiones sobre las raíces clásicas de la economía moderna. Se muestra que economistas como A. Smith, R. Ricardo, JS Mill y A. Marshall estaban en contra del dogmatismo en economía. Lo que sigue es un análisis de la metafísica que regresa a la reflexión filosófica sobre la economía. A continuación, comento el ensayo de D. Colander sobre la creación de economistas humildes (2016) y propongo que la falta de humildad en economía no puede evitarse tratando de persuadir a los economistas para que se comporten como ingenieros (como se sugiere en el artículo de Colander) sino más bien apegándose a la declaración metafísicamente rica de N. Cartwright de que conocimiento científico [en este caso conocimiento sobre la economía] no es conocimiento de leyes sino conocimiento de la naturaleza de las cosas ”(1999, 4). Siguen las conclusiones.

## Desenredando la idea de una ciencia humilde {-}

La ciencia se trata de conocer el mundo. Sin embargo, es importante darse cuenta de que no es un conocimiento ilimitado. Mantener la posición de que la ciencia por sí sola puede explicar todos los aspectos de la existencia conduce inevitablemente al cientificismo, que es una forma de dogmatismo científico. Sus defensores a menudo creen que esa posición puede hacerse desde dentro de la ciencia. Están equivocados. Los enunciados sobre ciencia no son enunciados científicos sino más bien metacientíficos y, por lo tanto, al reflexionar sobre el alcance de la ciencia, uno debería beneficiarse de las ideas de la filosofía de la ciencia^[J. Lenox también hace hincapié en el hecho de que el cientificismo se contradice a sí mismo: “La afirmación de que solo la ciencia puede conducir a la verdad no se deduce en sí misma de la ciencia. No es una declaración científica sino más bien una declaración sobre la ciencia, es decir, es una declaración metacientífica. Por lo tanto, si el principio básico del cientificismo es verdadero, el enunciado que expresa el cientificismo debe ser falso. El cientificismo se refuta a sí mismo. Por lo tanto, es incoherente ”(2009, 43).]. Y aquí, por ejemplo, podemos referirnos a la afirmación de K. Popper de que "Es importante darse cuenta de que la ciencia no hace afirmaciones sobre cuestiones fundamentales, sobre los enigmas de la existencia o sobre la tarea del hombre en este mundo" (1978, 342). Entonces, en primer lugar, una ciencia humilde no reclama el monopolio de proporcionarnos conocimiento sobre cómo funciona el mundo: "hay más en el mundo físico de lo que ha visto el ojo científico" (Polkinghorne1990, 88). Además, como L. Kołakowski afirma sabiamente, “Pero aunque no podemos perforar el misterio y convertirlo en conocimiento, nuestra conciencia de que hay misterio es en sí misma importante; aunque no podemos rasgar el velo de la realidad última, debemos saber que tal velo existe ”(2001, 10). Por lo tanto, no estoy de acuerdo con personas como P. Atkins (1994) quien afirma que “No hay nada que no se pueda entender” (1). Pero no me centraré demasiado en estudiar la naturaleza de los enunciados generales sobre ciencia. Mi objetivo es más bien discutir el carácter del conocimiento sobre el mundo que nos da la ciencia (aquí la economía) como tal.

Si nuestro objetivo es analizar la naturaleza del conocimiento científico, entonces deberíamos avanzar hacia la epistemología^[Sin embargo, no significa que debamos cometer una especie de "falacia epistémica", a saber, una reducción de la ontología a la epistemología.]. Aquí surgen preguntas sobre cómo conocemos las cosas y cómo podemos saber que las conocemos y pueden ser estudiadas desde diversas perspectivas que ofrecen numerosas teorías del conocimiento. El dilema tradicional del conocimiento también se aplica: ¿podemos conocer el mundo con certeza (absolutismo) o podemos simplemente conocerlo desde una mera perspectiva (relativismo) y, por lo tanto, nada se sabe con absoluto o certeza (escepticismo)? Simplemente hablando, existe una larga tradición en el pensamiento occidental de ver este mismo dilema como una cuestión de todo o nada, como una elección entre el dogmatismo y el escepticismo. Sin embargo, también hay una breve historia de pensamiento que busca un término medio en este debate. Mi opinión sobre una ciencia humilde se suscribe a esta última tradición.

Dado que el tema de este artículo es la economía, existe una justificación particular para referirse a Hume al estudiar el tema de la humildad epistemológica: además de ser uno de los filósofos más importantes que estudian la naturaleza del entendimiento humano, también fue una fuente crucial de inspiración. para Adam Smith. Al final de Una investigación sobre el entendimiento humano podemos encontrar la siguiente descripción de los seres humanos como inherentemente epistemológicamente humildes: “[La gente] debe actuar, razonar y creer; aunque no sean capaces, sea su más diligente investigación, de estar satisfechos con respecto al fundamento de estas operaciones ”(Hume1748/ 2004, 104). En el caso de Hume, su humildad epistemológica está fuertemente entrelazada con su humildad ontológica: “Nada en el mundo es perpetuo. Todo, sin embargo, aparentemente firme, está en continuo flujo y cambio. El mundo mismo da síntomas de fragilidad y disolución ”(1777/ 2006, 603). Como Holanda (2013, 31) escribe, “[…] nadie en la tradición filosófica europea tiene un sentido más agudo de los límites del conocimiento humano que David Hume”. Por lo tanto, saber algo con certeza es simplemente imposible para él y lo único que se puede lograr es tener "un grado de fe suficiente para nuestro propósito" (1740/ 2000, 122). Sin embargo, una creencia que esté libre de dudas es difícilmente posible: “La creencia, siendo una concepción viva, nunca puede ser completa si no se basa en algo natural y fácil” (ibid.). Curiosamente, Hume afirma que las creencias se encuentran en algún punto intermedio entre saber algo con certeza y saber algo solo con un determinado grado de probabilidad. Sin embargo, las creencias de Hume son subjetivas y se basan en impresiones sobre la estructura causal del mundo. Por tanto, siempre están sujetos a error, ya que solo sentimos una cierta necesidad en la conexión causal entre estados empíricos.

La introducción de las creencias por parte de Hume en la epistemología fue seguida por varios pensadores que ofrecieron a esta categoría un lugar legítimo en la filosofía de la ciencia moderna. Es importante destacar que, por ejemplo, Kant en su Crítica de la razón pura ofrece tres categorías de comprensión humana, a saber, opinión, conocimiento y creencia, y así escribe:

> Sostener la validez verdadera o subjetiva de un juicio en relación con la convicción (que es, al mismo tiempo, objetivamente válida) tiene los tres grados siguientes: opinión, creencia y conocimiento. La opinión es un juicio conscientemente insuficiente, tanto subjetiva como objetivamente. La creencia es subjetivamente suficiente, pero se reconoce que es objetivamente insuficiente. El conocimiento es suficiente tanto subjetiva como objetivamente (1781/ 1996, 749).

Aquí, como en Hume, la creencia es subjetiva. Sin embargo, Kant es un poco menos pesimista que Hume, ya que lo que sabemos sobre una cosa dada es el resultado de una interacción entre nuestra experiencia de este mismo objeto y su "cosa en sí". En lugar de ahondar más en Kant, pasaré a Charles Peirce, quien (junto con W. James) fundó el pragmatismo, un movimiento filosófico que afirma que “la justificación racional de las creencias científicas depende en última instancia de si el método que genera las creencias es el mejor disponible para avanzar en nuestras metas cognitivas de explicación y predicción precisa ”(Almeder2014, 103). Aquí está el famoso pasaje de Peirce sobre el papel de las creencias:

> La duda es un estado de inquietud e insatisfacción del que luchamos por liberarnos y pasar al estado de creencia; mientras que este último es un estado tranquilo y satisfactorio que no deseamos evitar o cambiar a una creencia en otra cosa. […] La irritación de la duda provoca una lucha por alcanzar un estado de fe. Llamaré a esta investigación de lucha (1877, 66–67).

Tal visión del mundo es a menudo criticada por rechazar la noción misma de verdad y enfocarse únicamente en la utilidad de las creencias (ver, por ejemplo, Rorty 1995). Creo que podemos dejar que los pragmáticos defiendan con tanta fuerza la utilidad de las creencias, pero al mismo tiempo afirman que al menos algunas de estas creencias son verdaderas. Además, las creencias verdaderas no tienen el estatus de regularidades humeanas, por ejemplo, creer que las tasas de interés más bajas deberían conducir a inversiones más altas aún puede ser cierto incluso si en una situación dada (digamos en Polonia en 2019) este no es el caso^[Esto puede ser así porque la inferencia puede ser de naturaleza puramente probabilística, las causas perturbadoras pueden estar presentes, etc.]. Lo que es muy importante en la postura de los pragmáticos sobre el carácter del conocimiento es que la forma en que se forman las creencias es importante para su justificación.

Espero que ahora esté claro que las ideas dadas por Hume, Kant y Peirce pueden considerarse como un apoyo al ideal de una ciencia humilde, que acepta la falibilidad de algunas de sus afirmaciones. O, para ser más precisos, una ciencia humilde no rechaza la posibilidad de que algunas de sus afirmaciones simplemente estén equivocadas. El carácter de la ciencia humilde también se puede ilustrar al contrastarla con su opuesto, a saber, una ciencia caracterizada por vicios, que incluyen arrogancia, vanidad, presunción, egoísmo, grandiosidad, pretenciosidad, esnobismo, impertinencia (presunción), altivez, justicia propia, dominación. , ambición egoísta y autocomplacencia (Roberts y Wood2003, 258). Si la forma en que practicamos la ciencia es importante para su éxito (como afirman los pragmáticos), cabe preguntarse si los científicos humildes siempre deben optar por una ciencia humilde. Aquí nos acercamos a la epistemología de la virtud donde muchos autores afirman que la humildad intelectual sirve como requisito previo para una ciencia humilde. Hazlett2012, 220) afirma que la humildad intelectual es “la disposición a no adoptar actitudes epistémicas de orden superior epistémicamente impropias”. Además, pero en un contexto ligeramente diferente, Whitcomb et al. (2015) afirman que ser un científico humilde significa conocer las propias limitaciones y, por lo tanto, estar abierto a la crítica. Roberts y Wood (2003, 272) describe muy bien a una humilde investigadora al retratar su antítesis:

> La persona intelectualmente vanidosa está demasiado preocupada por cómo 'se ve' ante las personas que cuentan: quiere impresionar y está muy preocupado por no parecer tonto en conferencias y frente a sus brillantes estudiantes. Esta preocupación puede inclinarlo a no admitir, y tal vez ni siquiera darse cuenta, cuando alguien ha puesto una buena objeción a sus puntos de vista. También puede inclinarlo a eludir los argumentos cuando cree que puede hacer que se vean lo suficientemente bien como para salirse con la suya. La persona intelectualmente vanidosa puede estar genuinamente preocupada por lograr fines epistémicos intrínsecos: descubrir qué es qué y dar a sus estudiantes una buena educación. Pero también tiene la preocupación extrínseca de verse bien intelectualmente, y estamos diciendo que esto es, en general, una desventaja epistémica. Por el contrario,

Decir que "todo el mundo hoy en día es, supongo, un falibilista sobre las teorías científicas" (Worrall 1989, 268) no significa que no podamos acercarnos a la verdad sobre el mundo y que no haya lugares donde las regularidades humeanas siempre puedan ser verdaderas. Pueden sostenerse, por ejemplo, en modelos teóricos. Lo que afirmo es que vicios como el orgullo, la altivez y la presunción pueden bloquear cualquier progreso científico, ya que uno puede concluir que él sabe todo sobre el mundo y no es necesaria ninguna investigación científica adicional. En otras palabras, el orgullo conduce a la pereza intelectual. Pero la humildad, por el contrario, hace que la gente sienta curiosidad por la forma en que funciona el mundo y, por lo tanto, "es la humildad la que hace a los hombres como ángeles" (San Agustín), y por lo tanto como McCloskey (2006) subraya al citar a T. Merton: “La humildad es una virtud, no una neurosis. Una humildad que congela nuestro ser y frustra toda actividad saludable no es humildad en absoluto, sino una forma disfrazada de orgullo ”(1956, 55). También se puede hacer referencia a la conferencia de San Juan Pablo II en la Universidad Jagellónica de Cracovia en 1997: “La razón debe actuar y ser activa en el clima espiritual de las virtudes morales, como la honestidad, el coraje, la humildad y la preocupación genuina por los seres humanos” (St . Juan Pablo II1997/ 2006, 988). Y en Fides et Ratio añade: “La sabiduría humana se niega a ver en su propia debilidad la posibilidad de su fuerza; sin embargo, san Pablo se apresura a afirmar: 'Cuando soy débil, entonces soy fuerte' (2 Co 12,10) ”(n. 23).

Al comienzo de esta sección escribí que una ciencia humilde es una especie de término medio entre el dogmatismo y el escepticismo. Ahora, puedo agregar a lo anterior que la humildad intelectual puede tratarse como un estado aristotélico mezquino entre el absolutismo de la certeza y la timidez de la incertidumbre. Por tanto, la humildad no es sólo una virtud moral, sino también epistémica. En cualquier caso, están entrelazados ya que ser una persona humilde facilita ser un científico humilde que puede practicar una ciencia humilde. En la siguiente sección, analizaré a los economistas clásicos y mostraré que la economía que practicaron puede tratarse como un ejemplo de una ciencia humilde.

## La economía clásica como ciencia humilde {-}

Al centrarse en la economía clásica, normalmente se parte del análisis de las obras de Adam Smith. Sin embargo, para entender a Smith conviene tomar nota de D. Hume y su reflexión sobre el carácter que nos ofrece la economía del conocimiento^[Hay una gran cantidad de literatura sobre la conexión Hume-Smith y no es necesario presentarla en detalle aquí, sin embargo, me gustaría citar a Smith de su carta escrita a W. Strahan poco después de la muerte de Hume: “Siempre lo he considerado , tanto en su vida como desde su muerte, tan cerca de la idea de un hombre perfectamente sabio y virtuoso, como tal vez lo permita la naturaleza humana de la fragilidad ”(Smith 1776, citado en: Rasmussen 2018, 51).]. Lo hicimos parcialmente en la sección anterior, pero ahora nos gustaría ser más precisos y centrarnos únicamente en su economía^[Escribir sobre la economía de Hume no significa que sin duda se le pueda llamar economista. Definitivamente fue un filósofo moral y solo más tarde comenzó a ser descrito como economista (Schumpeter1954/ 2006, 120).]. Hume utilizó muchos experimentos mentales en su investigación económica. Como Massey (1991) comenta “[…] quizás ningún otro filósofo ha realizado sus experimentos mentales con el grado de cuidado y sofisticación que Hume le otorgó” (293). Además, Schabas concluye su artículo sobre modelos en el pensamiento de Hume escribiendo que “todavía no he encontrado tal concentración de ejemplos [de experimentos mentales] desde los ideados por Hume” (2008, 168). Entonces, ¿cómo son los experimentos mentales de Hume? Aquí me gustaría referirme a uno de sus experimentos más importantes, a saber, el análisis que presentó en el Ensayo de interés (1758/1993, 181):

> Supongamos que, por milagro , todo hombre de Gran Bretaña debería tener cinco libras en el bolsillo en una noche; esto sería mucho más del doble de todo el dinero que hay actualmente en el reino; y sin embargo, no habría más prestamistas al día siguiente, ni por algún tiempo, ni variación en el interés (énfasis agregado).

Hacer referencia al “milagro” significa que estamos tratando aquí con una situación imaginaria, una especie de experimento mental, y no un modelo aislado y definido con precisión^[Aunque los modelos y los experimentos mentales son similares en muchos aspectos, también se deben notar diferencias importantes. Primero, los modelos están más desacoplados de sus objetivos que los experimentos mentales. En segundo lugar, tales experimentos (al menos en la interpretación de Hume) deberían referirse a objetivos empíricos que son al menos potencialmente posibles; los modelos, por otro lado, pueden describir mundos de cuento de hadas. En tercer lugar, las ideas de los experimentos mentales a menudo se ilustran con algunas referencias a dominios empíricos, pero las de los modelos generalmente se discuten en esquemas o imágenes puramente teóricos (Schabas2008).]. Además, esta aparición mágica de dinero adicional en los bolsillos de los sujetos británicos indica que Hume analiza únicamente la influencia de las variables monetarias en la economía; solo ellas tienen significado, y otros factores son fijos o están ausentes (ceteris paribus). Esto es importante porque le sirvió para mostrar la neutralidad del dinero. Explicar hechos empíricos a través de experimentos mentales presupone que los mecanismos descritos en ellos tienen sus contrapartes en la economía. Es difícil encontrar en el pensamiento de Hume algo que apoye mejor esta tesis que las siguientes palabras:

> Ahora bien, es evidente que las mismas causas que corregirían estas desorbitadas desigualdades, si ocurrieran milagrosamente, deben evitar que sucedan en el curso común de la naturaleza, y deben para siempre en todas las naciones vecinas, preservar el dinero casi proporcional al arte y la industria de cada nación (Hume 1758/1993, 191).

El primer fragmento del párrafo anterior del trabajo de Hume se refiere a la situación del experimento mental, mientras que la segunda parte apunta a la realidad empírica, de ahí el uso de la frase “casi proporcional”, no simplemente “proporcional”. Lo anterior muestra que Hume pasó voluntariamente del análisis en términos de un experimento mental al estudio de los fenómenos empíricos circundantes. En su texto Sobre el crédito público (1758/1993) podemos encontrar una referencia interesante a la entonces Gran Bretaña: “[la situación] a la que Gran Bretaña tiende visiblemente” (211)^[Esta frase no apareció en la primera edición del ensayo de Hume.]. Lo que siempre es cierto en el experimento mental, porque sucede “milagrosamente”, es decir, aislado de otras causas potencialmente perturbadoras, en realidad tiene lugar solo en una tendencia. Para ser más precisos, una causa dada produce una tendencia a un resultado particular y no necesariamente al resultado mismo. La certeza solo puede estar presente en construcciones de pensamiento, estrictamente axiomatizadas y definidas. Es en estos mundos modelo donde existen relaciones y leyes universalmente verdaderas. En su Tratado, mientras explica la naturaleza del conocimiento humano, escribe:

> Aquí quedan, por tanto, el álgebra y la aritmética como las únicas ciencias en las que podemos llevar a cabo una cadena de razonamiento con cualquier grado de complejidad y, sin embargo, conservar una perfecta exactitud y certeza. Es imposible para el ojo determinar que los ángulos de un quiliagon sean iguales a los ángulos rectos de 1996, o hacer alguna conjetura que se acerque a esta proporción (Hume 1740/ 2000, 51).

Antes de comentar este pasaje, me gustaría citar a continuación la siguiente declaración del ensayo de Mill de 1836 Sobre la definición de economía política :

> Las conclusiones de la geometría no son estrictamente ciertas para las líneas, ángulos y figuras que pueden construir las manos humanas. Pero nadie, por tanto, sostiene que las conclusiones de la geometría no son de utilidad, o que sería mejor callar los Elementos de Euclides y contentarnos con la 'práctica' y la 'experiencia' (Mill. 1836/ 2008, 46).

Tanto Hume como Mill afirman que de forma aislada, es decir, en un modelo dado (Mill) o en un experimento mental particular (Hume), la certeza es posible y que los enunciados verdaderos en estos mundos teóricos se convierten en aproximaciones de la verdad si se relacionan con hechos empíricos. - un triángulo dibujado por el autor de este ensayo debe tener solo aproximadamente 180 °, y esto es aún más sorprendente en el caso hipotético de un quiliagón. Por lo tanto, nunca tendremos leyes precisas y universalmente vinculantes que también sean independientes del contexto.

Ahora, y antes de pasar a Smith, es de destacar que en el Tratado de Hume se pueden encontrar algunas reflexiones interesantes sobre la humildad y el orgullo . Por ejemplo, en la sección titulada De la grandeza de la mente, Hume comienza su análisis afirmando claramente que “Un orgullo excesivo o una presunción arrogante de nosotros mismos siempre se considera vicioso y es odiado universalmente; como la modestia, o un justo sentido de nuestra debilidad, se estima virtuosa y procura la buena voluntad de todos ”(Hume1740/ 2000, 378). Anteriormente en el texto afirma que “la humildad exalta; pero el orgullo nos mortifica ”(ibid., 193). Aunque estas palabras se exponen en las secciones de su obra que tratan de la moral y no de la comprensión humana como tal, se pueden aplicar a la cuestión de la naturaleza del conocimiento humano en vista del análisis de Hume presentado en su Investigación sobre la comprensión humana . En la investigación de Hume Podemos encontrar una afirmación clara que niega la posibilidad de alcanzar el conocimiento último, mientras que al mismo tiempo afirma que es la modestia lo que facilita que los investigadores sean humildes al evaluar el carácter del conocimiento que poseen sobre el mundo: “Por lo tanto, podemos descubrir la razón por la que no El filósofo, que es racional y modesto, ha pretendido siempre asignar la causa última de cualquier operación natural, o mostrar claramente la acción de ese poder, que produce cualquier efecto único en el universo ”(Hume 1748/ 2004, 17). Aquí se hace referencia a los filósofos pero hoy en día también podemos aplicarlo a los economistas. La visión de Hume del conocimiento humano es entonces muy cercana a la que describimos anteriormente como una ciencia humilde.

En lo que respecta a las ideas de Adam Smith sobre la naturaleza de las leyes en economía, se puede decir que son de alguna manera contradictorias. Sin embargo, son tales solo en la superficie y no dan terreno a otro problema de Das Adam Smith . Dado que Smith fue enormemente influenciado por Newton, compartió con él una visión mecanicista del mundo en la que uno tiene estructuras, mecanismos y relaciones que nunca cambian. Es decir, ambos conciben una realidad en la que son posibles conjunciones constantes omnispacial y omnitemporalmente. Tomemos, por ejemplo, la siguiente idea de La teoría de los sentimientos morales: “La sociedad humana, cuando la contemplamos bajo una cierta luz abstracta y filosófica, aparece como una gran, una inmensa máquina, cuyos movimientos regulares y armoniosos producen mil efectos agradables. (1759/ 2013, 280). En los Ensayos sobre sujetos filosóficos de Smith hay otra observación claramente expresada: "El universo fue considerado como una máquina completa, como un sistema coherente, gobernado por leyes generales y dirigido a fines generales" (1795/ 1980, 113). Por otro lado, también podemos encontrar afirmaciones de Smith que parecen totalmente antinómicas a las anteriores. En La teoría de los sentimientos morales, escribe: "En el gran tablero de ajedrez de la sociedad humana, cada pieza tiene un principio de movimiento propio" (1759/ 2013, 204). Por tanto, parece que no tenemos reglas universales de comportamiento humano, pero cada sujeto humano tiene sus propios principios de conducta. Entonces, ¿cómo podemos reconciliar las dos visiones aparentemente contradictorias sobre la naturaleza del conocimiento sobre la economía? Aquí el propio Smith puede ayudarnos con la siguiente afirmación:

> Los sistemas en muchos aspectos se parecen a las máquinas. Una máquina es un pequeño sistema, creado para realizar, así como para conectar, en realidad, los diferentes movimientos y efectos para los que el artista tiene ocasión. Un sistema es una máquina imaginaria inventada para conectar en la fantasía esos diferentes movimientos y efectos que ya se realizan en la realidad. Las máquinas que se inventaron por primera vez para realizar cualquier movimiento en particular son siempre las más complejas, y los artistas posteriores generalmente descubren que, con menos ruedas, con menos principios de movimiento, de los que se habían empleado originalmente, el mismo efecto puede producirse más fácilmente. Los primeros sistemas, de la misma manera, son siempre los más complejos, y generalmente se considera necesaria una cadena o principio de conexión particular para unir cada dos apariencias aparentemente disociadas: 1795/ 1980, 66).

¿No está Smith simplemente escribiendo sobre el modelado de fenómenos económicos? Sus “máquinas imaginarias” son modelos que sirven para “descubrir principios”, incluidos los que gobiernan los sistemas económicos. En su interpretación del extracto citado anteriormente, Condorcet concluyó que “en todas las artes, las verdades de la teoría se modifican necesariamente en la práctica” (Condorcet1804, 292)^[M. de Condorcet fue uno de los intérpretes más importantes de las ideas de Smith (Rothschild 2001). Aunque investigó mucho en teoría de la probabilidad, era consciente de que los sistemas económicos son tan complejos que las interacciones entre varios eventos no son de naturaleza probabilística y, por lo tanto, a menudo se refería a las creencias como algo intermedio entre el conocimiento y la probabilidad.]. Entonces, en modelos o experimentos mentales uno puede tener regularidades perfectas e inmutables, pero una vez que los referimos a dominios empíricos, solo tenemos algunas creencias o “algunos grados de certeza que podemos esperar alcanzar” (ibid., 138). Refiriéndonos a un ejemplo más reciente, se puede decir que en el modelo de competencia perfecta el precio es siempre igual al costo marginal de producción, pero fuera del modelo, cuando apelamos a la economía real, p =  MC no significa, de hecho, obtener. Los modelos económicos no nos dan un conocimiento cierto sobre el mundo. Por lo tanto, lo máximo que podemos hacer es hacer inferencias humildes de los modelos a sus objetivos.

JS Mill fue otro economista del siglo XIX que cuestionó la posibilidad de formular leyes económicas precisas y universalmente vinculantes. En cambio, propuso la siguiente definición de leyes económicas: "Todas las leyes de causalidad, como consecuencia de su responsabilidad de ser contrarrestadas, requieren ser expresadas en palabras afirmativas de tendencias solamente, y no de resultados reales" (Mill1843, 523). Mill también escribió sobre la idea de "verdad abstracta", es decir, la verdad de las afirmaciones teóricas en la medida en que se colocan en lugares abstractos (modelos). Sin embargo, “las conclusiones deducidas correctamente de estos supuestos [modelos], serían tan verdaderas en abstracto como las de las matemáticas; y sería una aproximación lo más cercana posible a la verdad abstracta, a la verdad en lo concreto ”(Mill1836/ 2008, 49). Curiosamente, las tendencias de Mill son poderes de actuación que hacen que las cosas sucedan (ibid., 56). Desarrollaré este punto en la siguiente sección.

Ahora, antes de cerrar nuestro estudio sobre los economistas clásicos, recordaré a A. Marshall, quien es correctamente tratado como uno de los padres fundadores de la economía neoclásica, pero cuya economía no perdió sus raíces clásicas (Colander 2011). Incluso se puede argumentar que la rama marshalliana de la economía neoclásica está más cerca de las ideas de Smith, Ricardo y Mill que de la rama walrasiana del neoclasicismo. Esto es particularmente cierto en las ideas de Marshall sobre la naturaleza de las leyes económicas. Basta con citar algunas de sus opiniones seleccionadas aquí: "Si el tema de una ciencia pasa por diferentes fases de desarrollo, las leyes de la ciencia deben tener un desarrollo correspondiente a las cosas de las que tratan" (Marshall1890, sesenta y cinco); “Toda causa tiende a producir algún resultado definido si no ocurre nada que lo obstaculice. Así, la gravitación tiende a hacer que las cosas caigan al suelo: pero cuando un globo está lleno de un gas más liviano que el aire, la presión del aire lo hará subir a pesar de la tendencia de la gravitación a hacerlo caer ”(Marshall1920/ 2013, 26); “No hay tendencias económicas que actúen de manera tan constante y puedan medirse tan exactamente como puede hacerlo la gravitación: y, en consecuencia, no hay leyes de la economía que puedan compararse en cuanto a precisión con la ley de la gravitación” (ibid.). Entonces, simplificando un poco, cada economía no solo tiene su propio conjunto de leyes, sino que estas leyes son solo declaraciones sobre tendencias. Por lo tanto, no ser humildes al evaluar nuestras habilidades para comprender los sistemas económicos sería simplemente un error.

En lo que sigue, volveré a las tendencias de Mill, pero de una manera metafísicamente más rica. Al hacerlo, afirmaré que, al evaluar la naturaleza de nuestro conocimiento sobre la economía, no podemos abstraernos del carácter mismo del ámbito económico. En otras palabras, los fundamentos ontológicos de los sistemas económicos son importantes para el alcance y la certeza de nuestro conocimiento sobre ellos. O, como Lawson2015 afirma que “[…] el método debe encajar con la naturaleza de su objeto” (13), y así, por ejemplo, Róna afirma que “parece urgentemente necesaria una claridad sobre la ontología de la materia objeto de las ciencias sociales” (2018a, 5).

## Metafísica de los sistemas económicos {-}

Si quisiéramos describir una realidad económica, deberíamos preguntarnos cómo llegan a ser sus partes organizadoras. Más fundamentalmente, es necesario un estudio de la naturaleza de elementos específicos de esta realidad. Aquí se afirma que "todas las características de la realidad pueden verse bajo el aspecto de su ser" (Lawson2014, 19). Y la ontología científica puede entenderse como principalmente interesada en investigar la naturaleza de objetos económicos particulares. Se diferencia de la ontología filosófica que se ocupa de los aspectos generales del ser^[M. Bunge, por ejemplo, describe esta diferencia de la siguiente manera: “La ontología se puede clasificar en general y especial (o regional). La ontología general estudia todos los existentes, mientras que cada ontología especial estudia un género de cosa o proceso físico, químico, biológico, social, etc. Así, mientras que la ontología general estudia los conceptos de espacio, tiempo y evento, la ontología de lo social investiga tales conceptos sociológicos generales como los de sistema social, estructura social y cambio social ”(Bunge1999, 200). Nuestra ontología científica, y la ontología económica en particular, es un ejemplo de la ontología especial de Bunge.]. Como muestro en mi reciente libro sobre Economía sin leyes (2017), y lo que acabo de indicar con respecto a la economía clásica, el mundo económico no está gobernado por leyes universales como siempre que A, luego (siempre) B , sino más bien por entidades tales como poderes, mecanismos, tendencias y estructuras. Un mundo así es un mundo de potencialidades únicamente. Además, hablando metafóricamente, un mundo así es un mundo en el que las partes que lo constituyen interactúan "químicamente" y no "mecánicamente"^[Aquí me refiero al análisis de Mill presentado en su capítulo Sobre la composición de causas en un sistema de lógica. Según Mill, cuando las causas interactúan químicamente, entonces no podemos usar el método de aislamiento y, por lo tanto, los mismos fundamentos ontológicos de la economía clásica (y neoclásica) deben cuestionarse. En palabras de Mäki, “Esta es la cuestión de si las causas de los fenómenos económicos se combinaron 'mecánicamente' o 'químicamente', para usar las frases de Mill. Cuando las causas se combinan 'mecánicamente', sus efectos se pueden 'sumar' como vectores […]. Por otro lado, cuando las causas se combinan 'químicamente', se producen algunos resultados novedosos y cualitativos emergentes ”(1992, 349).]. En tal ámbito, los macro fenómenos emergen de sus micro fundamentos en lugar de ser reducibles a sus partes constituyentes. Entonces, como dice Lawson:

> […] Estas o las nociones relacionadas [declaraciones de tipo legal en economía] deben concebirse en términos de potenciales; como potenciales que pueden o no expresarse, y si se expresan, pueden o no actualizarse debido a tendencias compensatorias […] (Lawson 1997, 106).

Y antes también escribe que:

> […] La ciencia tiene como objetivo descubrir los factores causales, es decir, se preocupa por identificar las estructuras, los mecanismos y las tendencias que fundamentan, que producen, gobiernan o facilitan los fenómenos en un nivel diferente. Y si el objetivo de la ciencia es iluminar las estructuras que gobiernan los fenómenos superficiales, entonces las leyes o los enunciados de leyes no son enunciados empíricos (enunciados sobre experiencias) ni enunciados sobre eventos o sus regularidades (ya sean incondicionales o sujetos a restricciones ceteris paribus ), sino precisamente enunciados dilucidar las estructuras y sus modos característicos de actividad (ibid., 24; cursiva en el original).

Tres ideas de las declaraciones anteriores de Lawson son importantes para nuestro propósito, a saber, aquellas que tratan sobre tendencias, modos característicos de actividades y cláusula ceteris paribus. Entonces, permítanme comenzar con las tendencias. Pueden definirse haciendo referencia a la filosofía de las potencialidades de N. Cartwright, es decir: “Sustituyendo la palabra 'capacidad' por la palabra 'tendencia' de Mill, su afirmación es exactamente lo que pretendo establecer en este libro […]. Sugiero que el lector tome mi 'capacidad' y la 'tendencia' de Mill como sinónimos ”(Cartwright1989, 170). Lo siguiente puede servir como ejemplo: Mill afirmaría que las tasas de interés más bajas producen una tendencia al alza de las inversiones. Cartwright preferiría decir que las tasas de interés más bajas tienen la capacidad de generar mayores inversiones. O, para usar el ejemplo favorito de Cartwright, decir que la aspirina alivia los dolores de cabeza debe interpretarse como una afirmación de que la aspirina tiene la capacidad de aliviar los dolores de cabeza^[Como lo expresó el autor de Metafísica : “Se dice que algo es una capacidad [potencialidad, poder] cuando es un punto de partida de movimiento o cambio en otra cosa o en una cosa en tanto que otra” (Aristóteles2016, 83).]. Ahora, nos acercamos a la segunda idea subrayada anteriormente por Lawson, a saber, los modos de actividad característicos de las cosas. En términos de Cartwright, uno debería decir simplemente que la naturaleza misma de A es producir B. Por ejemplo, la naturaleza de las tasas de interés más bajas es aumentar las inversiones. Pero, como en el caso de la aspirina, una capacidad particular puede estar inactiva o su funcionamiento puede verse contrarrestado por algunos factores perturbadores. Entonces, uno puede tener tasas de interés bajas sin un cambio correspondiente en la inversión. No hay leyes universales, por favor, pero solo las naturalezas son reales, y hacen que los eventos económicos sucedan: "La noción de naturaleza de Aristóteles es mucho más adecuada que el concepto de ley , regularidad y propiedad presente para describir el tipo de conocimiento que tenemos" (Cartwright1999, 78; cursiva original). Afirmar lo contrario nos conduciría a un fundamentalismo al que deberíamos oponernos.

¿Qué pasa ahora con la cláusula ceteris paribus? ¿No sería suficiente como base para una economía humilde? No lo sería siempre y cuando se entienda simplemente como una restricción de 'otras cosas siendo constantes'. Además, tales leyes son empíricamente falsas (porque ocurren factores perturbadores) o son trivialmente verdaderas (si se entienden como declaraciones puramente analíticas). Se han escrito innumerables artículos sobre cómo se pueden defender estas leyes. Aquí me referiría a dos de esas defensas que interpretan las leyes ceteris paribus como declaraciones humildes sobre el mundo. Primero, justo antes de estudiar la cláusula ceteris paribus en el tercer capítulo de sus Principios A. Marshall escribió lo siguiente: “Y siguiendo nuestra definición de una ley económica, podemos decir que el curso de acción que se puede esperar bajo ciertas condiciones de los miembros de un grupo industrial es la acción normal de los miembros de ese grupo relativamente a esas condiciones "(Marshall 1920/ 2013, 28). Marshall habla aquí de una cláusula ceteris normalibus que dice que un enunciado particular solo es verdadero cuando las condiciones son normales. Por ejemplo, un aumento del desempleo ceteris normalibus reduce la inflación. Tal afirmación solo es cierta en un modelo neokeynesiano particular en el que se puede tener una curva de Philips no plana. Fuera de tal modelo, solo podemos creer que tal relación puede sostenerse imperfectamente. Y aquí estamos volviendo de alguna manera a la comprensión de Cartwright del ámbito económico mencionado anteriormente, donde las leyes ceteris normalibus simplemente se convierten en declaraciones del siguiente tipo: ceteris normalibus A conduce a B , y significa que la naturaleza de A es producir B. Entonces, una y otra vez, tenemos una forma humilde de interpretar las leyes de la economía. Como Cartwright lo describe muy bien:

> Existe una tendencia a pensar que todos los hechos deben pertenecer a un gran esquema y, además, que este es un esquema en el que los hechos de la primera categoría tienen un estatus especial y privilegiado. Son ejemplares de la forma en que se supone que funciona la naturaleza. Los demás deben adaptarse a ellos. Este es el tipo de doctrina fundamentalista que creo que debemos resistir (1994, 316).

Vivimos en un mundo moteado donde no tenemos teorías que lo abarquen todo y que nos den un sentido de certeza. Aquí estoy de acuerdo con Rodrik (2015, 17), quien humildemente dice: “La respuesta correcta a casi cualquier pregunta en economía es: depende”. Pero incluso si tenemos un conjunto apropiado de enunciados teóricos elaborados para un dominio empírico dado, entonces seremos capaces de describir meramente las capacidades, naturalezas y poderes de los objetos bajo investigación. La reflexión anterior es de importancia clave para mi tesis sobre la necesidad de humildad en la construcción de explicaciones económicas. Dado que los modelos producen creencias que los economistas tienen sobre el mundo y si son creíbles cuando la estructura de un modelo dado está cerca de su objetivo empírico, resulta que, por ejemplo, las leyes económicas (incluso si se entienden como declaraciones sobre tendencias únicamente) que Dar una descripción precisa de los países altamente desarrollados no tiene por qué ser adecuado para explicar los fenómenos en los países menos desarrollados. Por lo tanto,A, luego (siempre) B gobierna y, por lo tanto, las capacidades también lo son (casi) todo.

## D. El alegato de Colander para crear economistas humildes {-}

En un importante artículo sobre el estado actual de la profesión económica, D. Colander (2016) afirma que el problema crucial al que se enfrenta la economía es la “falta de humildad” (737). Por lo tanto, escribe que “nosotros, los economistas, tenemos una tendencia a transmitir más certeza científica en nuestras posiciones políticas de lo que la teoría y la evidencia objetivamente permitirían” (ibid.). Posteriormente propone el camino para tener economistas más humildes. Su solución es tratar a los economistas no como científicos aplicados, sino como ingenieros. El argumento de Colander a favor de tal solución se basa en el supuesto de que el objetivo de la ciencia "es encontrar la verdad" (738) mientras que el de la ingeniería "se aplica por naturaleza" (739). Y cita la afirmación de Koen de que el método de ingeniería es “La estrategia para provocar el mejor cambio en una situación incierta o mal entendida dentro de los recursos disponibles” (ibid.). Lo que importa también es el hecho de que la comprensión de Colander de la verdad es bastante sencilla: “una verdad científica es atemporal” (ibid.). A continuación, afirma que la mayoría de los economistas son en realidad ingenieros y que son por naturaleza más humildes que los científicos puros.

Los argumentos de Colander son más o menos similares a los de B. Bernanke, quien, mientras encabeza la FED, en su discurso de Princeton 2010 afirma que, de hecho, tenemos tres áreas en las que debemos centrarnos, a saber, ciencia económica, ingeniería económica y gestión económica. En su opinión, tenemos más problemas con los dos últimos conceptos que con el primero. No estoy del todo de acuerdo ni con Colander ni con Bernanke, pero encuentro los argumentos del ex presidente de la FED un poco más atractivos ya que también creo que no tenemos problemas con la economía como tal, sino que tenemos algunos problemas con la comprensión correcta de las afirmaciones. hace. Sin embargo, el acto mismo de comprender correctamente las ideas de la economía no pertenece a la ingeniería económica ni en el sentido de Bernanke ni de Colander. En otras palabras, Bernanke se equivoca al afirmar que la ciencia económica ofrece generalizaciones teóricas y empíricas, y Colander está igualmente equivocado al afirmar que la economía debería moverse más hacia la ingeniería y no hacia la ciencia. Lo que me gustaría enfatizar, y lo que con suerte debería quedar claro a partir de las ideas sugeridas en las secciones anteriores, es que puede haber una ciencia, también la ciencia económica, que no nos ofrece generalizaciones estrictas eternas e inmutables, sino que nos informa sobre las capacidades de factores potencialmente causales. Puede informarnos sobre algunos comportamientos estrictamente definidos solo en la medida en que aparecen en modelos teóricos cerrados. Tales reglas de comportamiento generalmente no se cumplen perfectamente una vez que pasamos de los modelos a sus objetivos, en lugar de generalizaciones, preferimos tener algunas creencias sobre las economías reales. Es más,leyes ceteris normalibus o, para ser aún más precisos, como leyes mixtas cn-cp, por ejemplo, ceteris normalibus (para mercados ideales, es decir, en algunas condiciones del modelo) y ceteris paribus (teniendo otras variables sin cambios), una disminución en la tasa de interés conduce a un aumento de las inversiones. Además, un determinado ceteris normalibus cláusula puede entenderse no sólo como sinónimo a una condición modelo dado, sino más bien como un metafísicamente acondicionador rico, a saber, la naturaleza de A es producir B . Aquí estamos cerca del nuevo aristotelismo. Por tanto, no sólo es posible la ciencia sin leyes. La ciencia que no ofrece verdades intemporales también es posible. Y así, parafraseando a Giere (2000, 523), lo que tradicionalmente se ha interpretado como leyes de la naturaleza que describen diversas economías, resultan ser meras declaraciones que describen el comportamiento de los modelos económicos teóricos. Quien se da cuenta de esto, está muy cerca de una economía humilde.

La insistencia de Colander en el hecho de que el problema más importante al que se enfrenta la economía es la falta de humildad en el comportamiento de los economistas es definitivamente cierta. Además, mi afirmación de que necesitamos una economía humilde, es decir, una economía consciente del tipo de conocimiento que produce (como se discutió anteriormente) necesariamente implica que necesitamos economistas que entiendan la economía de esa manera. Mi desacuerdo con la propuesta de Colander es que no tenemos que transformar a los economistas en ingenieros para lograr tal cambio. No debemos abandonar la ciencia en general y la economía en particular, y el camino a seguir es hacia una ciencia humilde y, en nuestro caso, una economía humilde.

## Conclusiones {-}

Hay un debate en curso sobre el estado de la economía moderna. Algunos acusan a la economía de "confundir la belleza, revestida de impresionantes matemáticas, con la verdad" (Krugman2009); otros señalan el hecho de que no tenemos ningún problema con la ciencia económica, sino con la ingeniería y la gestión económicas (p. ej., Bernanke2010); algunos enfatizan el hecho de que tenemos problemas no con la economía como tal sino con los economistas y su falta de humildad (Colander2016). En las reflexiones presentadas en este artículo también me centré en la falta de humildad, pero en un sentido algo diferente. La atención se centró aquí en el problema que enfrenta a un gran número de economistas en muchas áreas de la economía, a saber, su sueño de encontrar leyes universales que gobiernen los sistemas económicos. Sin embargo, estas leyes no existen. Como Róna (2018b, 189) afirma, por ejemplo: “El tema apropiado de la economía, por lo tanto, no puede ser la búsqueda de generalidades similares a leyes basadas en la naturaleza con poder predictivo y explicativo confiable, porque no existen tales generalidades”. Aunque muchos economistas estarían de acuerdo en que las leyes que descubren no tienen el estatus de leyes de la naturaleza, todavía tienen muchos problemas para rechazar la cosmovisión que considera que el mundo se rige por tales leyes. Sin embargo, una y otra vez, las leyes de la naturaleza no gobiernan el mundo y, por lo tanto, buscar leyes científicas que lo hagan es inútil. Lo que podemos buscar es identificar capacidades, causas, mecanismos, tendencias y algunas regularidades empíricas imperfectas. Las leyes inmutables y omniespacial y temporalmente vinculantes solo pueden aplicarse dentro de los modelos teóricos. Afirmar que deben mantenerse de la misma manera más allá de los modelos es un error. En otras palabras, tomar el modelo erróneamente como su objetivo empírico puede conducir fácilmente a una forma de dogmatismo científico. Como dice Rodrik amablemente: “no existe tal cosa comoel modelo, pero siempre es un modelo ”(2015, 43). Entonces, explicar el funcionamiento de los sistemas económicos mediante el uso de modelos es inherentemente imperfecto. Dicho de otra manera, las inferencias de los modelos a sus objetivos deben hacerse con la debida humildad.

Aunque todavía nos enfrentamos al problema del fracaso de la economía para comprender adecuadamente el estado de sus afirmaciones y de asignarles demasiada certeza (como se discutió anteriormente), hay muchas señales que indican que la profesión económica está ahora girando (aunque lentamente) en la dirección correcta. Un ejemplo es lo que a menudo se denomina un giro empírico en la economía, lo que significa que cada vez se aplican más artículos y se centran en los datos en lugar de solo en la teoría. Por lo tanto, se puede afirmar que existe un riesgo cada vez menor de llevar las afirmaciones de los modelos fuera de sus dominios adecuados. Pero aún así, tal giro en la economía no hace que la ciencia económica sea menos propensa a las críticas, sino que cambia qué se critica y cómo. Los estudios basados ​​en ensayos controlados aleatorios pueden servir como ejemplo. Y ahí tenemos un problema de validez externa. Si desea que los resultados de los ECA se apliquen en otros lugares de una manera simple, comete el mismo error que los autores de modelos teóricos en economía: quieren que sus conocimientos funcionen más allá de sus dominios adecuados. Dado que los experimentos (incluidos los ECA) son modelos, sus resultados deben interpretarse con la debida humildad. Escribiendo sobre ECA Deaton y Cartwright (2017) afirman lo siguiente: “A menudo aprendemos mucho al llegar a comprender por qué falló la replicación y podemos usar ese conocimiento para buscar cómo los factores que causaron el resultado original podrían operar de manera diferente en diferentes entornos”. En otras palabras, las causas de varios fenómenos económicos identificados en el trabajo empírico deben recibir una interpretación cuidadosa (humilde), por ejemplo, son solo condiciones INUS para resultados particulares^[La causalidad INUS se debe a Mackie (1974), y la cláusula INUS significa partes insuficientes pero no redundantes de una condición que en sí misma es innecesaria pero suficiente para contribuir al resultado.]. Dejame explicar. Imagine que una tasa de interés más baja hace que aumente la inversión. Lo que debe tenerse en cuenta con respecto a esta declaración es la presencia de empresas que desearían invertir pero necesitan capital barato y algunas reglas regulatorias que permiten las inversiones de las empresas. Juntos, estos factores son innecesarios pero suficientes para aumentar la tasa de inversión (ya que muchos otros eventos ciertamente podrían conducir a una mayor inversión, por ejemplo, una empresa determinada puede recibir un subsidio del gobierno, etc.). Dentro de este mismo conjunto de tres eventos, la reducción de la tasa de interés es insuficiente (ya que la reducción de la tasa de interés solamente, sin empresas dispuestas a invertir, por ejemplo, no causaría una mayor inversión) pero no redundante (porque una mayor inversión no lo haría). ocurrir sin ella, ceteris paribus) parte de una condición que es en sí misma innecesaria pero suficiente para que se produzca el resultado. Por lo tanto, una tasa de interés más baja es una condición del INUS para una mayor inversión. Entonces, nuevamente nos enfrentamos al tema de la interpretación adecuada del conocimiento sobre el mundo que nos brinda el experimento empírico. Aquí nuevamente, una forma correcta de abordarlo es tratarlo con humildad. Con respecto al ejemplo anterior, lo máximo que se puede afirmar es que la naturaleza de una tasa de interés más baja es estimular la inversión. Esta es la forma en que Cartwright en sus escritos parece interpretar la causalidad de INUS, incluida la identificada a través de ECA. Aquí nuevamente, una forma correcta de abordarlo es tratarlo con humildad. Con respecto al ejemplo anterior, lo máximo que se puede afirmar es que la naturaleza de una tasa de interés más baja es estimular la inversión. Esta es la forma en que Cartwright en sus escritos parece interpretar la causalidad de INUS, incluida la identificada a través de ECA. Aquí nuevamente, una forma correcta de abordarlo es tratarlo con humildad. Con respecto al ejemplo anterior, lo máximo que se puede afirmar es que la naturaleza de una tasa de interés más baja es estimular la inversión. Esta es la forma en que Cartwright en sus escritos parece interpretar la causalidad de INUS, incluida la identificada a través de ECA.

Como acabamos de ver, aunque el giro empírico es un paso en la dirección correcta para la economía, no garantiza por sí solo un avance hacia una economía más humilde. Se puede decir que solo puede tratarse como una condición INUS para hacer la economía más humilde. Otros desarrollos, como hacer que la economía sea más pluralista y, por lo tanto, sensible al contexto, también pueden (potencialmente) hacerla más humilde. Sin embargo, incluso en la economía así modificada, algunos investigadores aún pueden dar demasiada certeza a los conocimientos que producen. Por lo tanto, para un movimiento genuino hacia una economía humilde se necesita una economía basada en una ontología de potencialidades donde no se encuentran leyes, sino capacidades, tendencias, naturalezas y dynameis aristotélicas. Como mínimo, espero que la filosofía de la economía contribuya un poco a que se produzca tal cambio al hacer que la economía sea más autocrítica.