# Entre la racionalidad individual y colectiva {#Capitulo_19}

```{r, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "html", results='asis', echo=FALSE}
cat('<hr style="background-color:#03193b;height:2px">')
```

El artículo plantea la cuestión de la irreductibilidad de la racionalidad colectiva a la racionalidad individual. La irreductibilidad de la racionalidad colectiva a la racionalidad individual se explica por el fenómeno de la complejidad y el carácter complejo de la naturaleza humana. Tomando el enfoque de la teoría de la complejidad para el análisis de las instituciones, se discute la cuestión de la dependencia de la racionalidad individual de la racionalidad colectiva. Se afirma que la racionalidad colectiva surge no meramente de la capacidad humana para el razonamiento racional, sino de una variedad de otras capacidades humanas que influyen en la formación y funcionamiento de las instituciones socioeconómicas. Las instituciones, a su vez, se entienden aquí como una encarnación específica de la racionalidad colectiva.

## Introducción {-}

El concepto de racionalidad es uno de los elementos fundamentales y más controvertidos de la teoría económica. Dado que el supuesto de racionalidad constituye la base de muchos modelos macroeconómicos, principalmente los convencionales, influye en la política macroeconómica. Por tanto, las teorías de la racionalidad pueden tener efectos de gran alcance en la realidad económica.

En general, la racionalidad económica está asociada a la optimización y la eficiencia. En la economía moderna, el concepto de racionalidad se relaciona principalmente con la doctrina neoclásica que se centra en el comportamiento de los individuos (consumidores, empresas) y asume que su estrategia racional consiste en la maximización de su utilidad subjetiva esperada. Este es exactamente un núcleo de la teoría dominante de la elección racional, que también está asociada con el positivismo, el instrumentalismo y el individualismo metodológico. Sin embargo, a pesar de la popularidad del enfoque neoclásico, el concepto de racionalidad se ha abordado desde varios ángulos y, en la literatura, se pueden encontrar varias definiciones y clasificaciones de racionalidad. Por ejemplo, Herbert Simon (1955) hizo una importante distinción entre “racionalidad sustantiva” y “racionalidad procesal”, prestando especial atención a esta última. Otros autores distinguen entre racionalidades metodológicas y materiales (o entre formales y prácticas). En el sentido analítico, la definición de racionalidad tiene dos componentes: el primero se refiere a la elección racional de objetivos, y el segundo, los medios para alcanzar los objetivos^[Véase, por ejemplo, Hogan y Marcelle (2017).]. Además de eso, algunos economistas destacados, en particular Vernon Smith (2008), distinguen formas de racionalidad constructivista y ecológica.

Se puede continuar con la lista de otras clasificaciones posibles. Dado que el sistema económico como sistema complejo consta de muchos niveles diferentes (por ejemplo, nivel micro, nivel meso, nivel macro), tiene sentido considerar una jerarquía específica de diferentes racionalidades. Estas diferencias están determinadas por el objetivo perseguido por un sistema en consideración, el nivel de un sistema (desde el nivel individual al meta), los criterios de tiempo y espacio. En esta jerarquía, la racionalidad neoclásica ocupa solo uno de los lugares y, al mismo tiempo, puede divergir de otros tipos de racionalidad. Por ejemplo, imagine una comunidad de personas que para sobrevivir a corto plazo, de acuerdo con la racionalidad neoclásica, tala un bosque para su venta inmediata. Sin embargo, a largo plazo, la deforestación puede causar tales cambios en el ecosistema (como el problema de las inundaciones), que luego pueden poner en peligro la existencia de esta comunidad y los costos asociados con estas consecuencias superan con creces los beneficios obtenidos de la recolección. Este ejemplo demuestra tanto la contradicción entre las racionalidades a corto y largo plazo, como la inconsistencia que es posible entre las racionalidades individuales y colectivas. La elección que parece racional desde el punto de vista individual puede ser irracional desde el punto de vista de la elección colectiva y viceversa. y la inconsistencia que es posible entre las racionalidades individuales y colectivas. La elección que parece racional desde el punto de vista individual puede ser irracional desde el punto de vista de la elección colectiva y viceversa. y la inconsistencia que es posible entre las racionalidades individuales y colectivas. La elección que parece racional desde el punto de vista individual puede ser irracional desde el punto de vista de la elección colectiva y viceversa.

Usando la comprensión simplista de la racionalidad, corremos el riesgo de no poder explicar los fenómenos más complejos como, por ejemplo, el funcionamiento de algunas instituciones sociales fundamentales, que están asociadas con la racionalidad colectiva. El objetivo del artículo es demostrar la irreductibilidad de la racionalidad colectiva a la racionalidad individual. Además, utilizando el enfoque de la teoría de la complejidad, planteamos la cuestión de la dependencia de la racionalidad individual de la racionalidad colectiva, es decir, afirmamos que la primera está condicionada por la segunda y no al revés. Alan Kirman, uno de los principales especialistas en economía de la complejidad, hace una suposición similar cuando escribe que “es el tipo de organización más que el comportamiento individual lo que es fundamental para lograr la coordinación. Una vez en su lugar, la estructura organizativa, en sí misma,

Uno de los problemas clave que se abordan aquí se refiere a la cuestión de la influencia de las emociones humanas en la toma racional de decisiones. Para explicar la racionalidad colectiva, si partimos de la racionalidad individual, que implica que la toma de decisiones se basa en una elección consciente (calculada), inevitablemente perdemos el componente emocional del comportamiento humano. Sin embargo, algunas emociones humanas (como el afecto, la confianza, la curiosidad, la desesperación, el miedo, el orgullo, la empatía, la confianza y otras) juegan un papel importante en la formación de valores sociales y el funcionamiento de una serie de instituciones sociales. Las instituciones, a su vez, se entienden aquí como una encarnación específica de la racionalidad colectiva. Por tanto, se asume que la racionalidad colectiva contiene inevitablemente un componente de las emociones humanas,

## El problema de la irreductibilidad de la racionalidad colectiva a la racionalidad individual {-}

Una de las premisas básicas de la teoría de la elección racional es que el comportamiento social agregado resulta del comportamiento de actores individuales, cada uno de los cuales toma sus decisiones individuales. Un concepto central en esta teoría es el principio de transitividad y la agregación de preferencias individuales como un modo para definir una elección social (racional) colectiva. El principio de transitividad es fundamental en la teoría de la utilidad ordinal y ordena las preferencias de un agente económico en una escala ordinal. Significa que si un consumidor (agente económico) que decide entre tres bienes (resultados, opciones de elección) X, Y y Z, prefiere X a Y e Y a Z, debe preferir X a Z. Este principio se considera una característica importante del comportamiento racional del agente económico ya que el principio de transitividad se relaciona con las leyes de la lógica.

Esta visión de la racionalidad también está estrictamente relacionada con la comprensión de la economía como ciencia positivista, es decir, libre de juicios y valores subjetivos. Los investigadores señalan que los primeros economistas neoclásicos "todavía tenían rastros de la antigua y honorable preocupación de los escritores clásicos, como Adam Smith, por el bienestar de la sociedad" (Walsh2007), y fue Lionel Robbins quien, en la década de 1930, jugó un papel importante en la transformación de la economía neoclásica en la ciencia de la racionalidad instrumental que está "libre de valores" y relacionada con una elección de (escasos) medios para alcanzar (alternativas ) propósitos (fines) (Cedrini y Novarese 2014). Vivian Walsh (2007, 64), en particular, señala que este cambio metodológico se produjo no sin la influencia del positivismo lógico, todavía popular en ese momento, y “la afirmación positivista de que existía una marcada dicotomía entre cuestiones de hecho (el dominio de la ciencia) y valores ”.

Sin embargo, al seguir el principio de transitividad para determinar la elección colectiva corremos el riesgo de llegar a conclusiones paradójicas. De hecho, el teorema de imposibilidad de Arrow, que considera los sistemas de votación, y el dilema del prisionero demuestran el problema mismo de la conversión de las preferencias individuales en actos de elección deseables para toda la comunidad. Como observa Amartya Sen, la consistencia interna de la elección "es esencialmente confusa, y no hay forma de determinar si una función de elección es consistente o no sin referirse a algo externo a la conducta de elección (como objetivos, valores o normas)" (2002, 122).

Asimismo, en línea con el individualismo metodológico, las elecciones que se hacen en base a la racionalidad individual conducen a la mejor asignación de recursos posible, por lo que son los garantes de la racionalidad sistémica entendida como racionalidad macroeconómica. En otras palabras, los resultados del mercado, como el equilibrio o la eficiencia de asignación, son resultados del comportamiento individual de los agentes que maximizan racionalmente su utilidad (beneficios). En esta línea, la racionalidad macroeconómica se asocia con el estado óptimo de Pareto, bajo el cual la situación de uno de los participantes del mercado no puede mejorarse sin empeorar la situación de los demás.

Sin embargo, esta afirmación no está respaldada por datos empíricos y, en particular, por la economía experimental. Por ejemplo, sobre la base de experimentos de laboratorio con el uso de simulaciones por computadora, Shyam Sunder (2002) concluyó que "una forma débil de racionalidad individual, muy por debajo de la maximización, cuando se combina con las instituciones de mercado apropiadas, puede ser suficiente para que los resultados del mercado se acerquen a las predicciones del primer teorema fundamental" (de acuerdo con este teorema, bajo ciertas condiciones idealizadas, cualquier equilibrio competitivo conduce a una asignación de recursos Pareto eficiente), y que “los mercados pueden exhibir elementos de racionalidad ausentes en los agentes económicos”. (La racionalidad de los mercados se relaciona aquí en particular con la eficiencia de los mercados, es decir, su capacidad para asignar las cantidades limitadas de recursos de una manera que maximice la satisfacción de los consumidores).

De manera similar, Alan Kirman desafía el enfoque, según el cual "si comenzamos con individuos que se comportan bien, obtendremos agregados que se comportan bien" y "los individuos que se comportan bien tienen un comportamiento bien estructurado derivado de su comportamiento optimizador" (Kirman 2010, 20). Utilizando el ejemplo de los mercados de pescado, demuestra que la “regularidad” del comportamiento es más evidente a nivel agregado que a nivel individual. En general, en su opinión, la relación entre el comportamiento de los participantes individuales y el mercado en su conjunto está mediada por la forma en que el mercado está organizado, es decir, la forma en que el mercado asigna los recursos depende del tipo de institución de mercado. (Kirman2010, 60–66).

## La racionalidad limitada frente a la variedad de la naturaleza humana {-}

Para explicar el problema de irreductibilidad presentado anteriormente, es importante considerar al menos las siguientes tres preguntas. Primero, los individuos no son racionales en el sentido neoclásico. En segundo lugar, incluso si los individuos no se comportan racionalmente en el sentido neoclásico, pueden alcanzar metas que son racionales. En tercer lugar, el comportamiento racional de los individuos puede conducir a resultados irracionales.

### Los individuos no son racionales en el sentido neoclásico {-}

Una de las características de los modelos neoclásicos básicos, como los modelos de comportamiento del consumidor que utilizan las curvas de indiferencia y las líneas presupuestarias (elaborado por F. Edgeworth, E. Slutsky, J. Hicks), es la suposición implícita sobre un consumidor que tiene información perfecta. . En otras palabras, un consumidor, maximizando la utilidad y eligiendo una combinación de los dos bienes (por ejemplo, las tazas de café y los trozos de tarta), conoce perfectamente de antemano el sabor de estos bienes, su futuro placer por su consumo, etc. . Parece plausible que, si un consumidor realiza las mismas acciones con regularidad, carece del espíritu de experimentación o (y) la capacidad de conocer lo nuevo, le resulte más fácil comprender su utilidad acumulativa esperada. Sin embargo, si nuestro consumidor decide sacrificar tazas de café adicionales en nombre de una unidad adicional de un producto, que es absolutamente nuevo para él, corre un riesgo muy serio de desilusión. Por tanto, estos modelos son en realidad estáticos.

El supuesto de información perfecta también está implícitamente ligado al supuesto de disponibilidad de tiempo, suficiente para tomar la mejor decisión. Por ejemplo, en el caso aquí considerado, el consumidor necesita disponer de tiempo suficiente para recopilar (obtener) la información necesaria para tomar la decisión óptima. Este período de tiempo puede extenderse también al pasado, formando suficiente experiencia para tomar decisiones en el futuro. Por un lado, si el consumidor toma una decisión con mucha rapidez y no dispone al mismo tiempo de la información necesaria, es decir, de forma irracional, corre el riesgo de hacer una elección que puede ilustrarse como un punto alejado del punto que corresponde a la máxima utilidad. (punto de equilibrio). Por otro lado, si nuestro consumidor tiene un tiempo infinitamente largo para ejercer su mejor opción, corre el riesgo de repetir la suerte del asno de Buridan: al no elegir entre dos montones de heno idénticos, el pobre animal finalmente muere de hambre. Por tanto, desde el punto de vista de la dinámica y viabilidad del agente económico, debería ser mejor para él consumir menos utilidad pero estar en el momento adecuado que en un esfuerzo por maximizar la utilidad perderla por completo.

La crítica más conocida al concepto neoclásico de racionalidad provino de los economistas del comportamiento, especialmente de Herbert Simon, cuyo nuevo concepto de racionalidad limitada se refiere a la limitada capacidad humana para procesar información (resultante, entre otros, de la falta de tiempo, atención y capacidad de concentrado). En particular, Herbert Simon se refiere críticamente a la comprensión del interés propio como el objetivo más importante y a la forma de entender la racionalidad como una elección de alternativas de acción preferidas mediante un sistema de valores que permite evaluar los resultados de las actividades^[Véase, por ejemplo, Simon (1997).]. Su crítica se refiere al realismo del supuesto sobre el pleno conocimiento de una persona sobre las posibles alternativas, así como a la posibilidad física de su mente de procesar esta información y la voluntad de hacer tal valoración. Por esta razón, el comportamiento de toma de decisiones individual no se deriva del cálculo de todas las variantes y la selección de la óptima, sino de los valores y criterios disponibles, que son considerados por el sujeto como base para la selección. La falta de realismo de los supuestos neoclásicos se manifiesta también en el hecho de que, por ejemplo, para un hombre racional neoclásico sería racional violar las reglas sociales (si no implica costos), pero la gente a menudo se abstiene de hacerlo. Entonces, según Herbert Simon, la racionalidad de la toma de decisiones en el sentido neoclásico no es posible. En lugar de la racionalidad neoclásica, propone el concepto de racionalidad limitada, que da cuenta de una elección racional que tiene en cuenta las limitaciones cognitivas tanto del conocimiento como de la capacidad cognitiva. Simón (1997) enfatiza el importante papel del hábito, que permite el uso económico de los esfuerzos espirituales y mentales.

La opinión de que “la economía no está gobernada solo por actores racionales” y “gran parte de la actividad económica está gobernada por espíritus animales ” (es decir, las personas tienen motivos no económicos) ya fue expresada por John Maynard Keynes en su The General Theory (1936). Refiriéndose a Keynes, George Akerlof y Robert Shiller, en su libro Animal Spirits (Akerlof and Shiller2009) han proporcionado una ilustración detallada de esta idea. En particular, demuestran que, al tomar decisiones de inversión importantes, los actores económicos a menudo no se comportan de acuerdo con las prescripciones de la teoría económica estándar. Este último, a su vez, afirma que, para tomar decisiones racionales, las personas consideran todas las opciones disponibles para ellos, consideran los resultados de todas estas opciones y cuán ventajoso sería cada resultado, consideran las probabilidades de cada una de estas opciones, y luego tomar una decisión (Akerlof y Shiller2009, 13). Sin embargo, en condiciones de incertidumbre, es imposible definir con precisión esas opciones y probabilidades. Entonces, en realidad, las personas no actúan racionalmente, sino que actúan de acuerdo con lo que creen que es verdad (racional). Esto también significa que las decisiones de los actores económicos dependen en gran medida de sus creencias y confianza. Akerlof y Shiller enfatizan el gran papel de la confianza, por ejemplo, en el crecimiento o declive de los mercados crediticios, y remarcan que el significado de un término confianza va más allá de lo racional y está relacionado con los sentimientos humanos o, en otras palabras, “animal espíritu".

### El comportamiento que parece irracional puede conducir a resultados racionales {-}

Los economistas del comportamiento, como por ejemplo Gerd Gigerenzer, Daniel Kahneman, Amos Tversky y muchos otros, señalan el papel de las técnicas, distintas del razonamiento lógico, que ayudan a las personas a resolver problemas y tomar las mejores decisiones rápidamente. Enfatizan el papel del esfuerzo y el tiempo que una persona debe dedicar al análisis racional. La actividad mental está asociada con un alto consumo de energía (el cerebro absorbe la mayor cantidad de energía), por lo que las personas, con el objetivo de minimizar el gasto de energía, aplican heurísticas, el llamado pensamiento "rápido" en lugar de analizar lógicamente el problema (pensamiento "lento") , que reclama menos costes (calculados por tiempo y esfuerzo)^[Kahneman (2012).]. La heurística es una técnica asociada a una forma simplificada de pensar, una forma sencilla de llegar a una conclusión sin recurrir a cálculos matemáticos o pensamiento científico. Como Gerd Gigerenzer (2008, 20) subraya, “a diferencia de los procedimientos de optimización estadística, la heurística no intenta optimizar (es decir, encontrar la mejor solución), sino satisfacer (es decir, encontrar una solución suficientemente buena)”; los modelos de cognición heurística se centran en situaciones en las que las personas necesitan actuar con rapidez. Hay muchas heurísticas, como, por ejemplo, una regla empírica, un método de prueba y error, "imitar a la mayoría", "imitar al exitoso", etc. Daniel Kahneman (2012) discute particularmente las heurísticas de disponibilidad, heurísticas de representatividad (utilizadas en la situación de evaluación de enunciados referidos a probabilidades) y heurísticas de anclaje y emparejamiento (se utiliza para la evaluación cuantitativa). Las personas utilizan diferentes heurísticas según la situación y el entorno, y la misma heurística puede tener éxito o no según las circunstancias. En general, el uso de la heurística puede explicarse por una diversidad de capacidades humanas. Como señala Gigerenzer, “sin las capacidades desarrolladas, la heurística no podría hacer su trabajo”. Entre otros ejemplos menciona la capacidad humana de reconocimiento de la memoria (como reconocimiento de rostro, voz y nombre), la capacidad de imitar y la capacidad evolucionada para el altruismo recíproco (2008, 25).

Se puede ver que el método heurístico está conectado con las habilidades humanas que van más allá de los límites de la actividad consciente, y revela la riqueza de la naturaleza humana, una parte importante de la cual está formada por las emociones (simpatía, antipatía, afecto, miedo, confianza, etc.). en). En particular, con respecto a la racionalidad a largo plazo, la parte emocional de la naturaleza humana a veces es capaz de desafiar los límites de la racionalidad individual basada en la comprensión hedonista de la maximización de la utilidad. A modo de ilustración, imagine a un hombre codicioso que intenta “remar por sí mismo”, es decir, tomar más de otras personas que darles. Al final, corre el riesgo de perder amigos y su posible apoyo en caso de necesidad, etc. Una persona racional, que es capaz de comprender las consecuencias de largo alcance de sus acciones, puede ser conscientemente generosa con sus amigos (es decir, “Invertir” en sus amigos). Estos son dos motivos diferentes para el comportamiento, pero aquí es posible ver cómo las necesidades y capacidades específicamente humanas (la necesidad de amistad, la capacidad de ser generoso y amable) pueden compararse en el exterior con el comportamiento de un hombre cuya racionalidad se extiende durante un largo período de tiempo.

En la misma línea, podemos percibir la relación del ser humano con el medio natural. Aparte de las personas que no contaminan el medio natural solo porque hay prohibiciones externas (públicas) o por razones puramente económicas (de acuerdo con una lógica de los imperialistas económicos), hay personas que no contaminan y no dañan la naturaleza porque siente cariño por él y considéralo como un ser vivo. Por lo tanto, el amor humano por la naturaleza contribuye a la preservación a largo plazo del hábitat natural, al igual que lo harían las acciones racionales basadas en el complejo cálculo matemático de las consecuencias futuras del daño presente de la naturaleza.

Hay muchos otros ejemplos como este, por ejemplo, en el ámbito de la educación y la inversión en capital humano, la creación de familia, aportes previsionales, etc. Pero todos ellos de una forma u otra demuestran que la racionalidad acotada y la naturaleza humana acotada ( en el sentido de pobreza de naturaleza humana) convergen en un punto determinado. En otras palabras, la diversidad de la naturaleza humana compensa las limitaciones de la mente humana relacionadas con la falta de información y la incapacidad de realizar cálculos a largo plazo. De hecho, parece que, hasta cierto punto, las partes racional y emocional de la naturaleza humana se sustituyen y mejoran entre sí.

> **El comportamiento racional de las personas puede conducir a resultados irracionales**

En su libro mencionado anteriormente, Akerlof y Shiller describen situaciones en las que, como sucedió antes de la Recesión de 2001 y la Gran Recesión de 2007-2008, los individuos en los mercados financieros se comportaron de acuerdo con la teoría de la elección racional, ya que estaban siguiendo sus propias intereses propios (2009, 35). Sin embargo, dado que invirtieron en activos financieros de riesgo, su “racionalidad” no condujo a un equilibrio macroeconómico, sino a burbujas especulativas y finalmente a una crisis financiera. Por tanto, al final, su comportamiento no fue racional desde la perspectiva de la economía en su conjunto y, finalmente, desde la perspectiva de los propios inversores "racionales".

## Información, complejidad y principio de emergencia {-}

¿Es racional un burro que va tras la zanahoria que cuelga de un palo delante de su hocico? Habiendo visto una zanahoria, un burro teóricamente puede tener una razón para dar un paso hacia ella. En teoría, puede dar algunos pasos más. No podemos llamar irracionales los primeros pasos del animal, porque al burro lo impulsa la esperanza, el optimismo y la ausencia de experiencia. Si el burro es terco en su esperanza, entonces podemos llamarlo burro. La conclusión general de este ejemplo: el sujeto económico se comporta de manera irracional, cuando no usa (no intenta usar) la experiencia acumulada. Es decir, no acumula información (su recurso de información es igual a cero), no la utiliza, es decir, no aprende y se caracteriza por un (perfecto) desconocimiento. En este ejemplo, el problema de la racionalidad limitada, como ha sido formulado por Simon,

La acumulación (conservación y transmisión) de información es una característica de los sistemas complejos. La complejidad también puede definirse por otras consideraciones, incluidas las del tiempo y el espacio. El sistema económico con una vida útil más corta es más simple en comparación con un sistema relevante con una vida útil más larga. Por lo tanto, la racionalidad asociada con una maximización de la utilidad a corto plazo debe caracterizarse como atomista y también debe ser una característica de un sistema (socioeconómico) muy simple. Dado que el período de tiempo en cuestión está relacionado con la complejidad, no es accidental que, por ejemplo, en la economía experimental los resultados de los juegos de una sola vez (compárelos con un sistema a corto plazo) difieran de los resultados de los juegos repetidos (compárelos con un sistema de larga duración más complejo). Es decir, de acuerdo con los principales hallazgos de la economía experimental,2008). A la luz de lo anterior, dado que un sistema socioeconómico tiene un alto nivel de complejidad y, en consecuencia, de diversidad y heterogeneidad, una de las posibles respuestas a la pregunta sobre la irreductibilidad de la racionalidad macro (sistémica) hacia el individuo, puede residir en el principio de aparición. Esto último, a su vez, significa que “el todo es mayor que la suma de sus partes”, es decir, que un sistema complejo como entidad demuestra propiedades que están ausentes en los constituyentes del sistema, debido a interacciones entre estas partes constituyentes.

Además, asumiendo la conexión entre la racionalidad y la capacidad de información de un sistema, y ​​también considerando una mayor capacidad de información de un sistema más complejo, podemos suponer que la racionalidad individual está determinada por la racionalidad colectiva en lugar de un sistema (colectiva) la racionalidad está determinada por el individual. En general, está en consonancia con el hecho de que un ser humano como ser razonable sólo es posible como producto de la sociedad ("animal social"). Como escribió Friedrich Hayek, “[La] interacción de los individuos, que poseen diferentes conocimientos y diferentes puntos de vista, es lo que constituye la vida del pensamiento. El crecimiento de la razón es un proceso social basado en la existencia de tales diferencias ”(Hodgson2015, 292).

También está en consonancia con la tesis (resultado de la investigación) de que las especies biológicas con un alto nivel de cooperación tienen una mayor propensión a aprender, adaptarse, sobrevivir y, en general, al desarrollo evolutivo. Los investigadores señalan que el proceso evolutivo cultural depende fundamentalmente del tamaño y la interconexión de nuestras poblaciones y redes sociales; es la capacidad de intercambiar información libremente lo que acelera la evolución cultural adaptativa y crea innovación y, a nivel de población, es mucho mejor ser social que inteligente (Henrich2015).

En otras palabras, entre otras cosas, la racionalidad de los individuos depende de su capacidad para aprender unos de otros y de la experiencia (para utilizar la información acumulada). Tal punto de vista parece ser similar al enfoque de la economía evolutiva y de la complejidad. En particular, Alan Kirman remarca que, en los mercados, “los hábitos y relaciones que las personas han desarrollado a lo largo del tiempo parecen corresponder mucho más a lo aprendido por la fuerza de la experiencia que al cálculo consciente”, y una atribución de racionalidad de los agentes. , cuando están eligiendo una estrategia, es que “es más probable que hagan lo que ha demostrado ser exitoso en el pasado” (2010, 92, 85).

Los ejemplos inspiradores de la superioridad de la racionalidad colectiva sobre la racionalidad individual los dan las ciencias naturales, en particular la ecología del comportamiento. Por ejemplo, según la investigación de Susan Edwards y Stephen Pratt, las colonias de hormigas pueden evitar cambios irracionales en las preferencias que pueden mostrar animales individuales y humanos (Williams2009). Edward y Pratt probaron la irracionalidad en colonias de hormigas Temnothorax eligiendo entre dos sitios de anidación que variaban en atributos, de modo que ninguno de los sitios de anidación era claramente superior. En situaciones similares, los animales individuales muestran cambios irracionales en sus preferencias cuando se introduce una tercera opción relativamente poco atractiva. Estas sociedades actúan como tomadores de decisiones unitarios, capaces de seleccionar conjuntamente una única dirección de viaje, ubicación de alimentación o sitio de anidación entre muchas opciones. El análisis detallado de esta especie ha demostrado cómo el consenso depende de una minoría de hormigas activas que buscan hogares potenciales y evalúan su calidad. La resolución de problemas por parte de las sociedades de insectos se basa en un procesamiento de información altamente descentralizado. Esto refleja en parte limitaciones cognitivas y de procesamiento de la información: los insectos individuales no pueden manejar estos problemas solos, y las colonias carecen de estructuras jerárquicas que puedan fomentar la toma de decisiones centralizada. Los resultados de este estudio apoyan otra ventaja: el filtrado de errores sistémicos que de otro modo surgirían de las limitaciones cognitivas de los animales individuales.

El ejemplo de las hormigas se hace eco de la idea de Hayek citada por varios economistas conocidos según los cuales la información de la economía permanece dispersa y nunca se reúne en señales disponibles para todos^[Véase, por ejemplo, Hodgson (2015, 292), Kirman (2010, 12), Smith (2008).]:

> El problema de un orden económico racional está determinado precisamente por el hecho de que el conocimiento de las circunstancias de las que debemos hacer uso nunca existe en forma concentrada o integrada, sino únicamente como los fragmentos dispersos de conocimiento incompleto y frecuentemente contradictorio que todos los individuos separados poseer". “El conjunto actúa como un solo mercado, no porque alguno de sus miembros inspeccione todo el campo, sino porque sus limitados campos de visión individuales se superponen lo suficiente como para que, a través de muchos intermediarios, la información relevante se comunique a todos (1945, 519; 526).

Una de las principales características de un sistema complejo es la diversidad, que, a su vez, está relacionada con la capacidad de información de un sistema. Entonces, primero, de acuerdo con la teoría de la información, la estructura homogénea se caracteriza por cero información. En segundo lugar, de acuerdo con la ley de la variedad requerida de W. Ross Ashby, para poder resistir los impactos impredecibles variables del ambiente externo y por lo tanto ser conservado, el sistema abierto debe tener la variedad y complejidad requeridas de su estructura interna; sólo la variedad absorbe variedad.

En resumen, por un lado, si un sistema social consta principalmente de "átomos" (es decir, maximizadores egoístas), su racionalidad colectiva es más reducible a la racionalidad atomista y, al mismo tiempo, tal sistema es más mecanicista, muy vulnerable. a factores externos (fuentes de energía), y menos duraderos. Por otro lado, en el caso de una débil reducibilidad (o irreductibilidad) de la racionalidad sistémica a la individual, el sistema considerado es más complejo, se caracteriza por una mayor capacidad de información y diversidad, y es más duradero.

## Complejidad e instituciones: las instituciones como encarnación de la racionalidad colectiva {-}

Un ejemplo de la influencia de la racionalidad colectiva en la racionalidad individual puede ser el papel que desempeñan las instituciones y las normas. Después de todo, en los sistemas socioeconómicos, son las instituciones y la cultura las que cumplen la función de preservación y conservación de la información, es decir, sirven como portadores y transmisores fundamentales de la información. Así como un cuerpo humano “sabe” funcionar debido a la información contenida a nivel de genes (código genético), los seres humanos muchas veces saben qué hacer porque siguen las normas y reglas establecidas en una sociedad.

Varios economistas destacados enfatizan el vínculo entre instituciones e información. Por ejemplo, en opinión de Douglass North (1991), se forman instituciones para reducir la incertidumbre en el intercambio humano con la ayuda de la estructuración de la vida cotidiana; sirven como indicadores de las interacciones humanas; en condiciones de información incompleta y capacidades informáticas imperfectas, las limitaciones (institucionales) reducen los costos de la interacción humana en comparación con la ausencia de instituciones; en un mundo de racionalidad instrumental e información completa, las instituciones son innecesarias. También Geoffrey Hodgson (1988) señala el papel informativo de las instituciones y las rutinas, en particular, cuando escribe que las instituciones realmente crean y difunden ampliamente información adicional ya por el hecho mismo de su existencia.

Para comprender mejor cómo las instituciones y las reglas predeterminan la racionalidad individual, consideremos el siguiente experimento mental. Imagínese un observador externo mágico que observa a las personas que cruzan la calle. Supongamos también que no ve los semáforos (y no sabe de su existencia). Y suponga que no hay infractores de las reglas de tráfico. Consideremos los dos escenarios siguientes: primero, cuando funciona el semáforo y, segundo, cuando el semáforo no funciona. Entonces, en el primer caso, nuestro observador puede ver el orden perfecto y pensar en la racionalidad perfecta tanto de los peatones como de los conductores: los peatones son racionales, porque cruzan la calle cuando los autos están parados; los conductores son racionales, porque se detienen cuando los peatones cruzan la calle. En el segundo caso, sin embargo, el panorama cambia y se vuelve más caótico: la gente puede cruzar la calle incluso cuando los vehículos están en movimiento; los coches pueden seguir circulando incluso cuando hay personas cruzando la calle. Por lo tanto, nuestro observador mágico puede concluir que tanto los peatones como los conductores se volvieron menos racionales. ¿Es realmente el caso? A sus propios ojos, los peatones conservaban ambos: una meta (fin) - cruzar una carretera, y un medio - un deseo de conservar sus vidas evitando los autos. Los conductores conservaron su objetivo de continuar su camino y el movimiento, evitando a los peatones. En otras palabras, su racionalidad individual no cambió (o cambió ligeramente). Pero algo sucedió con el sistema general de reglas y los participantes del proceso en consideración estaban desorientados. los coches pueden seguir circulando incluso cuando hay personas cruzando la calle. Por lo tanto, nuestro observador mágico puede concluir que tanto los peatones como los conductores se volvieron menos racionales. ¿Es realmente el caso? A sus propios ojos, los peatones conservaban ambos: una meta (fin) - cruzar una carretera, y un medio - un deseo de conservar sus vidas evitando los autos. Los conductores conservaron su objetivo de continuar su camino y el movimiento, evitando a los peatones. En otras palabras, su racionalidad individual no cambió (o cambió ligeramente). Pero algo sucedió con el sistema general de reglas y los participantes del proceso en consideración estaban desorientados. los coches pueden seguir circulando incluso cuando hay personas cruzando la calle. Por lo tanto, nuestro observador mágico puede concluir que tanto los peatones como los conductores se volvieron menos racionales. ¿Es realmente el caso? A sus propios ojos, los peatones conservaban ambos: una meta (fin) - cruzar una carretera, y un medio - un deseo de conservar sus vidas evitando los autos. Los conductores conservaron su objetivo de continuar su camino y el movimiento, evitando a los peatones. En otras palabras, su racionalidad individual no cambió (o cambió ligeramente). Pero algo sucedió con el sistema general de reglas y los participantes del proceso en consideración estaban desorientados. los peatones conservaron ambos: una meta (fin) - cruzar una carretera, y un medio - un deseo de conservar sus vidas evitando los autos. Los conductores conservaron su objetivo de continuar su camino y el movimiento, evitando a los peatones. En otras palabras, su racionalidad individual no cambió (o cambió ligeramente). Pero algo sucedió con el sistema general de reglas y los participantes del proceso en consideración estaban desorientados. los peatones conservaron ambos: una meta (fin) - cruzar una carretera, y un medio - un deseo de conservar sus vidas evitando los autos. Los conductores conservaron su objetivo de continuar su camino y el movimiento, evitando a los peatones. En otras palabras, su racionalidad individual no cambió (o cambió ligeramente). Pero algo sucedió con el sistema general de reglas y los participantes del proceso en consideración estaban desorientados.

Este experimento mental demuestra, primero, que la racionalidad individual no es idéntica a la racionalidad colectiva y, segundo, que la racionalidad del comportamiento individual depende del sistema de reglas de una sociedad. En otras palabras, podemos tomar a los peatones y conductores para representar a los actores económicos, y un semáforo puede considerarse como un representante de las instituciones, reglas y rutinas dominantes en el sistema en consideración. Pero, como Richard Langlois (1998) comenta, “la elección económica, tal como la pensamos normalmente, sólo puede suceder en un mundo estable y predecible en el que la mayor parte de la carga cognitiva se lleva a cabo mediante reglas y rutinas”. De modo que el cambio o el daño de las viejas instituciones y reglas influyen en el carácter de la elección individual, que en condiciones de creciente incertidumbre parece volverse menos racional.

Es un hecho común que la cultura, las normas y las instituciones influyen, por ejemplo, en los gustos y, por tanto, en las decisiones de los consumidores. De manera similar, el entorno institucional influye en las decisiones de inversión. Es digno de mención que Akerlof y Shiller, señalando los lados débiles de las teorías convencionales del ahorro (que se construyen alrededor del supuesto sobre la racionalidad individual), señalan que “el ahorro se basa en gran medida en diferentes marcos institucionales y mentales” (2009, 123). y, en particular, dar ejemplos de las grandes diferencias de ahorro entre China y Estados Unidos, que están conectadas a diferencias institucionales y culturales.

En realidad, el fenómeno de la racionalidad individual bajo la influencia del entorno institucional se describe mediante el concepto de racionalidad ecológica. El término de racionalidad ecológica fue acuñado por Gerd Gigerenzer (2008) y también es utilizado por Vernon Smith, el principal creador de la economía experimental, quien considera que hay dos tipos de racionalidad, la constructivista y la ecológica, que conviven y se complementan. El concepto de racionalidad constructivista está asociado con el proceso deductivo consciente de la razón humana y el uso de la razón para crear deliberadamente reglas de acción y crear instituciones socioeconómicas humanas. Exactamente este tipo de racionalidad está cerca de la comprensión de la racionalidad por parte de la economía neoclásica. La racionalidad ecológica, a su vez, está asociada con la inteligencia incorporada en las reglas, normas e instituciones de nuestra herencia cultural y biológica que se crean a partir de interacciones humanas, pero no por un diseño humano deliberado. En particular, uno de los principales hallazgos de la economía experimental es que,2008).

Así, con base en lo anterior, surge la pregunta sobre conceptualizar las instituciones como la encarnación de la racionalidad colectiva (o irracionalidad), que, a su vez, afecta la racionalidad individual. Con eso llegamos a una hipótesis idéntica a la suposición de Alan Kirman, a saber, que “es el tipo de organización más que el comportamiento individual lo que es fundamental para lograr la coordinación. Una vez en su lugar, la estructura organizacional, en sí misma, coordina las actividades individuales y las hace consistentes ”(2010, 6). En otras palabras, en la interrelación entre la racionalidad individual y colectiva, tenemos que partir no de la racionalidad individual en su sentido neoclásico, sino viceversa.

## Instituciones y emociones humanas {-}

Las instituciones no son solo producto de la racionalidad constructivista. Como una forma de interacciones humanas, junto con otros factores, pueden basarse en ciertas emociones humanas o explotar esas emociones, que, a su vez, proporcionan (o promueven) interacciones humanas. En otras palabras, supongamos que uno de los componentes más importantes, que está integrado en la racionalidad colectiva, pero que está excluido por la racionalidad individual en su comprensión neoclásica, es la parte emocional de la naturaleza humana.

En contraste con el modelo egoísta de maximización de la utilidad de un individuo en la economía dominante, los representantes de la heterodoxia económica (como por ejemplo la economía evolutiva y antropológica) señalan las características altruistas y cooperativas de la naturaleza humana, que se deben tanto a la evolución humana genética como a la cultural. , y que son importantes para la supervivencia del individuo y los grupos sociales (Hodgson 2015, 68–69). Enfatizan el papel de las emociones para nuestra existencia social y señalan que “en una cultura compleja, las reglas emocionalmente empoderadas pueden ayudar a mejorar las nociones de justicia y moralidad”. En particular, Geoffrey Hodgson señala que estas características de la naturaleza humana, como las capacidades emocionales desarrolladas por la selección natural, son "particularmente importantes para el funcionamiento de la ley y el estado" (Hodgson2015, 72–73).

A diferencia de los representantes del imperialismo económico que amplían el principio de la racionalidad económica individual sobre otras relaciones humanas, no comerciales, e intentan presentar el comportamiento altruista y cooperativo de los seres humanos a la luz de la lógica del homo economicus^[Véase, por ejemplo, Becker (1974).], es decir, tratan el altruismo como otro interés propio^[La crítica de este enfoque ver, por ejemplo, en Cedrini y Novarese (2014).], los partidarios del enfoque de la complejidad argumentan que tanto las motivaciones para el interés propio como la generosidad coexisten, ya que la obligación coexiste con la libertad (Cedrini y Novarese2014).

De hecho, las instituciones socioeconómicas y políticas fundamentales, como, por ejemplo, las instituciones de la democracia y el mercado, se basan tanto en la racionalidad individual constructivista como en el componente emocional de la naturaleza humana relacionado con el comportamiento no egoísta. Por ejemplo, la capacidad de los seres humanos para confiar en los demás es uno de los fundamentos de las transacciones de mercado. Según diferentes investigaciones, esta capacidad jugó un papel importante en la evolución humana, ya que ayudó a los seres humanos a convivir y aprovechar las ventajas de la cooperación y la división del trabajo. Por lo tanto, aunque los mercados se asocian tradicionalmente con la competencia y la búsqueda de beneficios personales, las características de la naturaleza humana, como la adherencia a los principios morales y la capacidad de confiar, también juegan un papel importante para asegurar el funcionamiento de los mercados.2008), refiriéndose a las ideas de Adam Smith y su Teoría de los sentimientos morales (1759), señala el hecho de la dependencia de los mercados de las virtudes humanas y señala que, de lo contrario, los costos de vigilancia y aplicación serían insoportables.

En su discusión sobre los “espíritus animales”, junto con la confianza de Robert Shiller y George Akerlof, entre otros, prestan mucha atención a sentimientos humanos como la justicia y la fe en las historias. En particular, señalan con ironía que, aunque algunos libros de texto "mencionan la equidad como motivo, todavía lo degradan al estado de final de capítulo, final de libro", y "está reservado para aquellas secciones que el estudiante saben que pueden saltarse cuando estudian para el examen ”(2009, 20). Tan poca atención a la equidad parece paradójica si tenemos en cuenta, por ejemplo, qué lugar dedicó Adam Smith a considerar “el sentido de la justicia” en su The Theory of Moral Sentiments y que, en particular, concluyó:

> La beneficencia es un adorno que embellece el edificio, no los cimientos que lo sostienen; por lo que es bueno que se recomiende, pero no es necesario que se imponga. En contraste con eso, la justicia es el pilar principal que sostiene todo el edificio. Si se elimina, toda la sociedad humana debe desmoronarse en un momento en átomos (Smith1759)^[Consulte la Parte II, Sección 2, Cap. 3 .].

En resumen, no solo una capacidad humana de razonamiento racional sino una variedad (complejidad) de la naturaleza humana en general, incluida su parte emocional, tiene el impacto en la racionalidad colectiva ya que influye en la formación y funcionamiento de las instituciones socioeconómicas, mientras que esta última, como se demostró anteriormente, debe considerarse como una encarnación específica (o acumuladores) de la racionalidad colectiva. Por lo tanto, tiene sentido pensar en algunos conceptos e instituciones clave de una economía de mercado, que tradicionalmente están conectados con la racionalidad neoclásica, desde el punto de vista de las emociones incrustadas en estas instituciones.

## La institución del espíritu empresarial innovador {-}

Sin tener en cuenta la complejidad de la naturaleza humana, es imposible, en particular, explicar adecuadamente el fenómeno del emprendimiento innovador como motor impulsor del desarrollo económico (en la comprensión de Josef Schumpeter (2017)). Por ejemplo, según William Baumol, “los esfuerzos de los empresarios se reasignan mediante cambios en los sectores de la economía y las líneas de actividad donde parece más fácil obtener ganancias” (1993, 13). En nuestra opinión, esta es una tesis importante que explica los flujos de capitales intersectoriales, y es un inversor financiero muy sensible a las ganancias (si lo comparamos con los actores económicos del llamado sector real de la economía). Entonces, es uno de los motivos básicos del capitalista financiero (usamos este controvertido término aquí por conveniencia). Como su tarea es “hacer dinero”, es (al menos teóricamente) indiferente en qué invertir el dinero siempre que sea rentable. En otras palabras, le es indiferente invertir dinero en la producción de computadoras o en la producción de pantuflas o en especulaciones financieras. Aquí no negamos la importancia del inversor financiero en la actividad empresarial, atentos a la tesis de Schumpeter sobre la conexión entre el mercado de capitales y el desarrollo de la economía.

Nos atrevemos a suponer que la motivación de los grandes emprendedores-innovadores es mucho más compleja, y el fenómeno del emprendimiento no puede explicarse exclusivamente por el principio de “facilidad de obtención de beneficios” y (o) maximización de beneficios. Para muchos de estos personajes debemos reconocer el papel combinativo de la racionalidad y las emociones (como, por ejemplo, la propensión al riesgo en la parte no relacionada con los cálculos matemáticos de resultados probabilísticos). Por ejemplo, Henry Ford, quien sin duda fue uno de los más grandes empresarios de la era industrial, dijo que “el mayor uso del capital no es ganar más dinero, sino ganar dinero para hacer más por mejorar la vida”, y que “una el negocio que no genera más que dinero es un mal negocio ”. Steve Jobs, cuyo nombre está asociado con la revolución informática, dijo: “Ser el hombre más rico del cementerio no me importa. Acostarse por la noche diciendo que hemos hecho algo maravilloso, eso es lo que me importa ”; “Tu trabajo va a ocupar gran parte de tu vida, y la única forma de estar verdaderamente satisfecho es haciendo lo que crees que es un gran trabajo. Y la única forma de hacer un gran trabajo es amar lo que haces ”. También reconoció: “Tengo un gran respeto por la mejora incremental y he hecho ese tipo de cosas en mi vida, pero siempre me han atraído los cambios más revolucionarios. No sé por qué. Porque son más duros. Son mucho más estresantes emocionalmente. Y normalmente pasas por un período en el que todo el mundo te dice que has fracasado por completo ”. “Tu trabajo va a ocupar gran parte de tu vida, y la única forma de estar verdaderamente satisfecho es haciendo lo que crees que es un gran trabajo. Y la única forma de hacer un gran trabajo es amar lo que haces ”. También reconoció: “Tengo un gran respeto por la mejora incremental y he hecho ese tipo de cosas en mi vida, pero siempre me han atraído los cambios más revolucionarios. No sé por qué. Porque son más duros. Son mucho más estresantes emocionalmente. Y normalmente pasas por un período en el que todo el mundo te dice que has fracasado por completo ”. “Tu trabajo va a ocupar gran parte de tu vida, y la única forma de estar verdaderamente satisfecho es haciendo lo que crees que es un gran trabajo. Y la única forma de hacer un gran trabajo es amar lo que haces ”. También reconoció: “Tengo un gran respeto por la mejora incremental y he hecho ese tipo de cosas en mi vida, pero siempre me han atraído los cambios más revolucionarios. No sé por qué. Porque son más duros. Son mucho más estresantes emocionalmente. Y normalmente pasas por un período en el que todo el mundo te dice que has fracasado por completo ”. pero siempre me han atraído los cambios más revolucionarios. No sé por qué. Porque son más duros. Son mucho más estresantes emocionalmente. Y normalmente pasas por un período en el que todo el mundo te dice que has fracasado por completo ”. pero siempre me han atraído los cambios más revolucionarios. No sé por qué. Porque son más duros. Son mucho más estresantes emocionalmente. Y normalmente pasas por un período en el que todo el mundo te dice que has fracasado por completo ”^[https://www.brainyquote.com/quotes].

Es de destacar que Richard Langlois, al considerar la cuestión de la racionalidad en relación con el emprendedor-innovador que se enfrenta a situaciones novedosas (es decir, toma decisiones en condiciones de incertidumbre), cita las palabras de Schumpeter: “Aquí el éxito de todo depende de la intuición, la capacidad de ver las cosas de una manera que luego resulta ser cierta, aunque no pueda establecerse en el momento, y de captar el hecho esencial, descartando lo no esencial, aunque no se puedan dar cuenta de los principios por los que esto es hecho"^[Schumpeter (1934/2017); Langlois1998).].

En sus Espíritus animales , George Akerlof y Robert Shiller también señalan que “el futuro de cualquier país está en manos de los empresarios que deciden sobre las inversiones, y depende en gran medida de su psicología”; “Los negocios, al menos los negocios exitosos, prosperan con la emoción de crear el futuro” (2009, 143-144).

## El dilema del prisionero, la “sombra del futuro” y la institucionalización de las emociones {-}

La pregunta importante se refiere a la cuestión del tipo neoclásico de racionalidad individual en su relación con las instituciones socioeconómicas. Si partimos de la microrracionalidad en el sentido neoclásico, corremos el riesgo de concluir con la imposibilidad de cooperación y la viabilidad de las instituciones sociales. Uno de los ejemplos más conocidos es el dilema del prisionero, ya que ilustra que el comportamiento individualmente racional no conduce necesariamente a un resultado socialmente óptimo.

El dilema del prisionero, cuyos creadores son Merrill Flood, Melvin Dresher y Albert William Tucker^[Véase, por ejemplo, Tucker (1983).], es un ejemplo estándar de un juego analizado en teoría de juegos. Muestra por qué dos individuos completamente racionales podrían no cooperar, incluso si parece que lo mejor para ellos es hacerlo. Imagínese que dos miembros de una banda criminal, A (I) y B (II), son arrestados y encarcelados. Cada preso se encuentra en régimen de aislamiento sin medios para comunicarse con el otro. A cada preso se le da la oportunidad de traicionar al otro testificando que el otro cometió el crimen ("estrategia de deserto"), o de cooperar con el otro permaneciendo en silencio. La oferta es: si A y B se traicionan mutuamente, cada uno de ellos cumple 2 años de prisión; si A traiciona a B pero B permanece en silencio, A será puesto en libertad y B cumplirá 3 años de prisión (y viceversa); si A y B permanecen en silencio,
 	
| I / II      | Cooperación | Deserción |
|-------------|:-----------:|:---------:|
| Cooperación |    (1, 1)   |   (3, 0)  |
| Deserción   |    (0, 3)   |   (2, 2)  |

Este escenario hipotético demuestra que la opción de traicionar es una estrategia dominante porque la deserción siempre resulta en una mejor recompensa que la cooperación, independientemente de la elección del otro jugador. La deserción mutua es el único equilibrio fuerte de Nash en el juego (es decir, el único resultado del cual cada jugador solo podría hacerlo peor cambiando unilateralmente la estrategia). El dilema, entonces, es que la cooperación mutua produce un resultado mejor que la deserción mutua, pero no es el resultado racional porque la opción de cooperar, desde una perspectiva de interés propio, es irracional.

De hecho, el dilema del prisionero tiene que ver con el enfoque perfectamente atomista de la racionalidad, ya que ignora el entorno institucional y considera a dos prisioneros que son miembros de la misma banda criminal de una manera que el hecho de la existencia de esta banda criminal no influye en la elección de la misma. prisioneros, y no tienen miedo al castigo de otros miembros de esta pandilla. Tal racionalidad se asemeja más bien a la reacción reflexiva de un animal sobre un trozo de comida frente a su hocico, pero no es un trabajo de la mente y el razonamiento humanos. ¿No es cierto que la mente todopoderosa de la racionalidad individual, que implica conocimiento ilimitado y posesión de información, resulta ser sólo un reflejo primitivo de la animalidad ávida de placeres?

Además, en tal tipo de interacción (un juego), la suposición de que cada jugador está interesado en sí mismo y siempre elige la mayor de las dos recompensas inmediatas para sí mismo, se asemeja extrañamente al principio de aumento de entropía: si consideramos la evolución de un sistema aislado, este sistema inestable dejado solo será destruido, convirtiéndose gradualmente en estados más probables y estables; Al mismo tiempo, aumentan tanto la probabilidad como la entropía (Brillouin1964). Dado que la entropía está asociada con un desorden en un sistema, la analogía antes mencionada nos inspira a dudar de la racionalidad tal como la presenta la economía neoclásica, y a pensar en la racionalidad en un contexto más amplio, es decir, en los términos del proceso de ordenación y ordenación. complejidad del sistema.

Además, el dilema del prisionero no presume afecto emocional y confianza (que puede contrarrestar la estrategia defectuosa) entre personas porque no toma en cuenta su interacción pasada, y también asume que dos individuos están destinados a no volver a encontrarse nunca más. En esta situación, "no importa lo que haga el otro, la elección egoísta de la deserción produce una recompensa mayor que la cooperación" (Axelrod y Hamilton1981, 1391). En su artículo fundamental La evolución de la cooperación , Robert Axelrod y William Hamilton (1981) señalan que, en muchos entornos biológicos, los mismos dos individuos pueden encontrarse más de una vez. Según su modelo, la probabilidad de cooperación (correspondientemente, la probabilidad de una estrategia de deserción, pero en la dirección opuesta) depende de "la historia de interacción hasta ahora" y la probabilidad del evento, que después de la interacción actual los mismos dos individuos (jugadores) nos volveremos a encontrar. Este último también se expresa como “la sombra del futuro” que debe ser larga; ningún jugador debería saber cuándo terminará el juego (Axelrod1984).

Para la evolución de la cooperación es muy importante que “un individuo no debe poder salirse con la suya al desertar sin que el otro individuo pueda tomar represalias de manera efectiva”; para ello es necesario que “el desertor no se pierda en un mar anónimo de otros”. Axelrod y Hamilton (1981) notan que los organismos superiores evitan este problema por su capacidad bien desarrollada para reconocer muchos individuos diferentes de otras especies (tienen una memoria más compleja, un procesamiento de información más complejo; en los humanos, una mejor capacidad para distinguir entre diferentes individuos se basa en gran medida sobre el reconocimiento de rostros).

Partiendo de la teoría de juegos y de las ideas de Robert Axelrod, podría resultar interesante concebir algunas instituciones desde el punto de vista de su papel en la formación y apoyo de “la sombra del futuro” y, por tanto, en la promoción cooperativa (no- comportamiento defectuoso. Por ejemplo, puede ser la institución de la iglesia, es decir, la institucionalización de esas emociones y sentimientos humanos, que están conectados con el miedo a la muerte, la fe en Dios (dioses), la fe en el más allá, el miedo al castigo por los pecados (por ejemplo, la fe en karma). En otras palabras, la fe sostenida por la iglesia en la otra vida y los castigos de Dios, prolongando la “sombra del futuro”, podrían facilitar la evolución de la cooperación social; y este es uno de los ejemplos más obvios de cómo las emociones se integran en las instituciones, formando una racionalidad colectiva (o irracionalidad).

## Observaciones finales {-}

La racionalidad se relaciona con la información (conocimiento), su acumulación y uso. Por tanto, la racionalidad es una característica de los sistemas vivos primarios y complejos. Una característica de los sistemas complejos (vivos) es la acumulación de energía e información (libres), por lo que la característica fundamental de la racionalidad es prevenir el proceso de desorden y el crecimiento de la entropía en un sistema. En este sentido, la racionalidad es una acción (fenómeno o rasgo) que tiene como objetivo contrarrestar los procesos de entropía y el crecimiento del caos en el sistema, y, por tanto, tiene funciones similares a las instituciones, ya que el objetivo de ambas debe ser la organización en un sistema. sistema relevante. A su vez, la racionalidad neoclásica en su conexión con la idea de optimalidad y eficiencia debe considerarse como un caso particular de este fundamento antientrópico general de la racionalidad.

En el proceso de producción de información colectiva se involucra no solo la capacidad humana de razonar sino también otras habilidades humanas como el apetito por el riesgo y la búsqueda de lo nuevo, ya que incrementan la experiencia colectiva. No solo los cálculos egoístas de los resultados futuros, sino también las emociones humanas como los sentimientos de afecto, confianza y equidad juegan un papel importante en la convivencia colectiva y, por lo tanto, influyen en las interacciones sociales que adoptan la forma de diferentes instituciones e influyen en la formación. y carácter de racionalidad colectiva. La racionalidad colectiva está incorporada en las instituciones sociales y no puede reducirse a la racionalidad individual en su estrecho significado neoclásico.

Según la psicología social y la neuropsicología modernas, las decisiones basadas en emociones difieren de las decisiones basadas en la razón, pero ayudan a sustentar la macrorracionalidad ya que nos permiten considerar los intereses de los demás en nuestras decisiones. El llamado imperialismo económico, que extiende el principio de racionalidad económica individual a otras relaciones humanas, no conectadas directamente con la actividad económica, ignora la complejidad de la naturaleza humana, el papel de las emociones humanas y el altruismo, y sobrevalora las capacidades de cálculo del cerebro humano. El surgimiento y funcionamiento de muchas instituciones socioeconómicas importantes no puede explicarse por una comprensión estrictamente egoísta de la racionalidad individual.

Una persona es capaz de actuar tanto de forma egoísta como altruista y la forma en que eventualmente actuará depende del entorno. Una sociedad que tiene mucha más información que un individuo aporta valores específicos que luego se convierten en criterios para las decisiones futuras de los individuos. Los procesos políticos, como la democracia sostenida por medios libres, ayudan a la sociedad a distinguir valores cruciales y a encontrar y definir los problemas que la sociedad en cuestión quiere resolver. A su vez, la 'voluntad' realizada y expresada de una sociedad toma la forma de instituciones relevantes que luego no solo brindan los criterios de 'ser racionales' y eficientes, sino que también tienen instrumentos para prevenir o hacer que la sociedad actúe de acuerdo con estos criterios. .

En este sentido, si las instituciones existentes favorecen el altruismo y no solo el egoísmo, habrá mucho más espacio y oportunidades para que los individuos desarrollen sus rasgos altruistas, especialmente si la conducta altruista es considerada por una sociedad como racional. La ideología neoliberal, a través de sus instituciones formales y no formales, expande la convicción de que el comportamiento altruista no es racional. Al mismo tiempo, los estudios del comportamiento y la psicología social abren una nueva visión, a saber, que el altruismo puede dar sus frutos y, al final, ser una estrategia racional. Las sociedades con democracias desarrolladas parecían haber aprendido que la diversidad les permite actuar de manera más racional como el todo e inculcar los valores del todo en los individuos a través de instituciones relevantes.

La codicia y la generosidad humanas, el egoísmo y el altruismo, la razón y la emocionalidad están incrustadas en diferentes actividades que pueden ser igualmente importantes para la existencia de la sociedad humana en su conjunto. Sin embargo, el predominio de la característica única, empujando a todas las demás, conduce, en palabras de Ortega y Gasset, a una homogeneidad perniciosa. Entonces, partiendo de un estrecho individualismo egoísta, positivismo y cortoplacismo, corremos el riesgo de encontrarnos con el “hombre unidimensional” (término utilizado por Herbert Marcuse) que de manera similar al “hombre de masas” de José Ortega y Gasset (Ortega y Gasset1930), es capaz de destruir la civilización humana, incluida la inteligencia que es la base de la racionalidad humana.